<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Misallocation of Epistemic Credit in Socially Embedded Learning: An Empirically Anchored Agent-Based Model of Information Search and Debate – MOVICI</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-172ba59bd5e0b52282274ba0c0cc16fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">MOVICI</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-working-papers" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Working Papers</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-working-papers">    
        <li>
    <a class="dropdown-item" href="../../working-papers/wp01-cavl/index.html">
 <span class="dropdown-text">WP01 — CAVL</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../working-papers/wp02-information-search/index.html">
 <span class="dropdown-text">WP02 — Information Search</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../working-papers/wp03-debate/index.html">
 <span class="dropdown-text">WP03 — Debate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../working-papers/wp04-search-debate/index.html">
 <span class="dropdown-text">WP04 — Information Search &amp; Debate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../working-papers/wp05-agent-based-model/index.html">
 <span class="dropdown-text">WP05 — Agent-Based Model</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../team.html"> 
<span class="menu-text">Project Team</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../funding.html"> 
<span class="menu-text">Funding &amp; Support</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#video-presentation" id="toc-video-presentation" class="nav-link active" data-scroll-target="#video-presentation">Video Presentation</a></li>
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a></li>
  <li><a href="#theoretical-framework-learning-from-a-socially-structured-world" id="toc-theoretical-framework-learning-from-a-socially-structured-world" class="nav-link" data-scroll-target="#theoretical-framework-learning-from-a-socially-structured-world">2. Theoretical Framework: Learning from a Socially Structured World</a>
  <ul class="collapse">
  <li><a href="#two-learning-pathways" id="toc-two-learning-pathways" class="nav-link" data-scroll-target="#two-learning-pathways">2.1. Two Learning Pathways</a></li>
  <li><a href="#structural-and-interactional-embeddedness" id="toc-structural-and-interactional-embeddedness" class="nav-link" data-scroll-target="#structural-and-interactional-embeddedness">2.2. Structural and Interactional Embeddedness</a></li>
  <li><a href="#cooperation-competition-and-goal-structure" id="toc-cooperation-competition-and-goal-structure" class="nav-link" data-scroll-target="#cooperation-competition-and-goal-structure">2.3. Cooperation, Competition, and Goal Structure</a></li>
  <li><a href="#epistemic-credit-and-misallocation" id="toc-epistemic-credit-and-misallocation" class="nav-link" data-scroll-target="#epistemic-credit-and-misallocation">2.4. Epistemic Credit and Misallocation</a></li>
  <li><a href="#what-the-model-adds-to-existing-simulations" id="toc-what-the-model-adds-to-existing-simulations" class="nav-link" data-scroll-target="#what-the-model-adds-to-existing-simulations">2.5. What the Model Adds to Existing Simulations</a></li>
  </ul></li>
  <li><a href="#empirical-basis-the-movici-experiment" id="toc-empirical-basis-the-movici-experiment" class="nav-link" data-scroll-target="#empirical-basis-the-movici-experiment">3. Empirical Basis: The MOVICI Experiment</a>
  <ul class="collapse">
  <li><a href="#protocol" id="toc-protocol" class="nav-link" data-scroll-target="#protocol">3.1. Protocol</a></li>
  <li><a href="#empirical-results-used" id="toc-empirical-results-used" class="nav-link" data-scroll-target="#empirical-results-used">3.2. Empirical Results Used</a></li>
  </ul></li>
  <li><a href="#the-agent-based-model" id="toc-the-agent-based-model" class="nav-link" data-scroll-target="#the-agent-based-model">4. The Agent-Based Model</a>
  <ul class="collapse">
  <li><a href="#purpose-of-the-model" id="toc-purpose-of-the-model" class="nav-link" data-scroll-target="#purpose-of-the-model">4.1. Purpose of the Model</a></li>
  <li><a href="#agents-and-information-environment" id="toc-agents-and-information-environment" class="nav-link" data-scroll-target="#agents-and-information-environment">4.2. Agents and Information Environment</a></li>
  <li><a href="#an-information-search-episode" id="toc-an-information-search-episode" class="nav-link" data-scroll-target="#an-information-search-episode">4.3. An Information-Search Episode</a></li>
  <li><a href="#a-debate-episode" id="toc-a-debate-episode" class="nav-link" data-scroll-target="#a-debate-episode">4.4. A Debate Episode</a></li>
  <li><a href="#what-cooperation-and-competition-change" id="toc-what-cooperation-and-competition-change" class="nav-link" data-scroll-target="#what-cooperation-and-competition-change">4.5. What Cooperation and Competition Change</a></li>
  <li><a href="#sequencing-search-and-debate" id="toc-sequencing-search-and-debate" class="nav-link" data-scroll-target="#sequencing-search-and-debate">4.6. Sequencing Search and Debate</a></li>
  <li><a href="#measuring-the-use-of-expertise" id="toc-measuring-the-use-of-expertise" class="nav-link" data-scroll-target="#measuring-the-use-of-expertise">4.7. Measuring the Use of Expertise</a></li>
  <li><a href="#mathematical-formalization-with-intuitive-interpretation" id="toc-mathematical-formalization-with-intuitive-interpretation" class="nav-link" data-scroll-target="#mathematical-formalization-with-intuitive-interpretation">4.8. Mathematical Formalization with Intuitive Interpretation</a></li>
  </ul></li>
  <li><a href="#simulation-experiments" id="toc-simulation-experiments" class="nav-link" data-scroll-target="#simulation-experiments">5. Simulation Experiments</a>
  <ul class="collapse">
  <li><a href="#the-six-main-scenarios" id="toc-the-six-main-scenarios" class="nav-link" data-scroll-target="#the-six-main-scenarios">5.1. The Six Main Scenarios</a></li>
  <li><a href="#what-an-episode-means" id="toc-what-an-episode-means" class="nav-link" data-scroll-target="#what-an-episode-means">5.2. What an Episode Means</a></li>
  <li><a href="#group-composition-and-partner-rotation" id="toc-group-composition-and-partner-rotation" class="nav-link" data-scroll-target="#group-composition-and-partner-rotation">5.3. Group Composition and Partner Rotation</a></li>
  <li><a href="#same-agent-counterfactual-comparison" id="toc-same-agent-counterfactual-comparison" class="nav-link" data-scroll-target="#same-agent-counterfactual-comparison">5.4. Same-Agent Counterfactual Comparison</a></li>
  <li><a href="#mechanism-robustness-and-sensitivity-tests" id="toc-mechanism-robustness-and-sensitivity-tests" class="nav-link" data-scroll-target="#mechanism-robustness-and-sensitivity-tests">5.5. Mechanism, Robustness, and Sensitivity Tests</a></li>
  <li><a href="#why-30-replications" id="toc-why-30-replications" class="nav-link" data-scroll-target="#why-30-replications">5.6. Why 30 Replications?</a></li>
  </ul></li>
  <li><a href="#empirical-anchoring-and-first-episode-checks" id="toc-empirical-anchoring-and-first-episode-checks" class="nav-link" data-scroll-target="#empirical-anchoring-and-first-episode-checks">6. Empirical Anchoring and First-Episode Checks</a></li>
  <li><a href="#simulation-results" id="toc-simulation-results" class="nav-link" data-scroll-target="#simulation-results">7. Simulation Results</a>
  <ul class="collapse">
  <li><a href="#search-saturates-in-a-fixed-world-and-continues-in-a-renewed-world" id="toc-search-saturates-in-a-fixed-world-and-continues-in-a-renewed-world" class="nav-link" data-scroll-target="#search-saturates-in-a-fixed-world-and-continues-in-a-renewed-world">7.1. Search Saturates in a Fixed World and Continues in a Renewed World</a></li>
  <li><a href="#a-small-socioeconomic-differential-produces-cumulative-advantage-in-an-expanding-information-environment" id="toc-a-small-socioeconomic-differential-produces-cumulative-advantage-in-an-expanding-information-environment" class="nav-link" data-scroll-target="#a-small-socioeconomic-differential-produces-cumulative-advantage-in-an-expanding-information-environment">7.2. A Small Socioeconomic Differential Produces Cumulative Advantage in an Expanding Information Environment</a></li>
  <li><a href="#a-single-debate-produces-little-learning-but-repeated-debates-can-accumulate" id="toc-a-single-debate-produces-little-learning-but-repeated-debates-can-accumulate" class="nav-link" data-scroll-target="#a-single-debate-produces-little-learning-but-repeated-debates-can-accumulate">7.3. A Single Debate Produces Little Learning, but Repeated Debates Can Accumulate</a></li>
  <li><a href="#in-the-model-the-cooperative-regime-mainly-increases-social-receptivity" id="toc-in-the-model-the-cooperative-regime-mainly-increases-social-receptivity" class="nav-link" data-scroll-target="#in-the-model-the-cooperative-regime-mainly-increases-social-receptivity">7.4. In the Model, the Cooperative Regime Mainly Increases Social Receptivity</a></li>
  <li><a href="#ablations-distinguish-influence-general-receptivity-and-differential-allocation" id="toc-ablations-distinguish-influence-general-receptivity-and-differential-allocation" class="nav-link" data-scroll-target="#ablations-distinguish-influence-general-receptivity-and-differential-allocation">7.5. Ablations Distinguish Influence, General Receptivity, and Differential Allocation</a></li>
  <li><a href="#results-are-robust-to-several-scenario-changes" id="toc-results-are-robust-to-several-scenario-changes" class="nav-link" data-scroll-target="#results-are-robust-to-several-scenario-changes">7.6. Results Are Robust to Several Scenario Changes</a></li>
  <li><a href="#search-re-anchors-the-self-model" id="toc-search-re-anchors-the-self-model" class="nav-link" data-scroll-target="#search-re-anchors-the-self-model">7.7. Search Re-Anchors the Self-Model</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">8. Discussion</a>
  <ul class="collapse">
  <li><a href="#the-central-problem-is-converting-expertise-into-learning" id="toc-the-central-problem-is-converting-expertise-into-learning" class="nav-link" data-scroll-target="#the-central-problem-is-converting-expertise-into-learning">8.1. The Central Problem Is Converting Expertise into Learning</a></li>
  <li><a href="#cumulative-inequalities-connections-with-economics-and-sociology" id="toc-cumulative-inequalities-connections-with-economics-and-sociology" class="nav-link" data-scroll-target="#cumulative-inequalities-connections-with-economics-and-sociology">8.2. Cumulative Inequalities: Connections with Economics and Sociology</a></li>
  <li><a href="#credibility-deficits-status-and-epistemic-injustice" id="toc-credibility-deficits-status-and-epistemic-injustice" class="nav-link" data-scroll-target="#credibility-deficits-status-and-epistemic-injustice">8.3. Credibility Deficits, Status, and Epistemic Injustice</a></li>
  <li><a href="#cooperation-competition-and-the-strategic-value-of-others" id="toc-cooperation-competition-and-the-strategic-value-of-others" class="nav-link" data-scroll-target="#cooperation-competition-and-the-strategic-value-of-others">8.4. Cooperation, Competition, and the Strategic Value of Others</a></li>
  <li><a href="#receptivity-calibration-and-epistemic-inclusion" id="toc-receptivity-calibration-and-epistemic-inclusion" class="nav-link" data-scroll-target="#receptivity-calibration-and-epistemic-inclusion">8.5. Receptivity, Calibration, and Epistemic Inclusion</a></li>
  <li><a href="#humanmachine-learning-and-trust-calibration" id="toc-humanmachine-learning-and-trust-calibration" class="nav-link" data-scroll-target="#humanmachine-learning-and-trust-calibration">8.6. Human–Machine Learning and Trust Calibration</a></li>
  <li><a href="#what-the-model-can-explain" id="toc-what-the-model-can-explain" class="nav-link" data-scroll-target="#what-the-model-can-explain">8.7. What the Model Can Explain</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">9. Limitations</a></li>
  <li><a href="#data-code-and-reproducibility" id="toc-data-code-and-reproducibility" class="nav-link" data-scroll-target="#data-code-and-reproducibility">10. Data, Code, and Reproducibility</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">11. Conclusion</a></li>
  <li><a href="#appendix-a.-correspondence-with-code-and-replication-parameters" id="toc-appendix-a.-correspondence-with-code-and-replication-parameters" class="nav-link" data-scroll-target="#appendix-a.-correspondence-with-code-and-replication-parameters">Appendix A. Correspondence with Code and Replication Parameters</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Misallocation of Epistemic Credit in Socially Embedded Learning: An Empirically Anchored Agent-Based Model of Information Search and Debate</h1>
<p class="subtitle lead">MOVICI Working Paper 05</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="movici-author">
MOVICI Research Programme
</div>
<div class="movici-meta">
Working paper · 2026 · Preprint — not peer reviewed
</div>
<div class="resources">
<p><span class="resources-title">Resources</span> <a class="resource-link" href="files/MOVICI_WP05.pdf">Download PDF</a> <a class="resource-link" href="files/MOVICI_WP05_agent_based_model_Replication_Package.zip">Data &amp; replication package</a></p>
</div>
<section id="video-presentation" class="level2">
<h2 class="anchored" data-anchor-id="video-presentation">Video Presentation</h2>
<div class="video-embed">
<iframe src="https://www.youtube.com/embed/PDsRrFG375M" title="MOVICI Working Paper 05 video presentation" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="">
</iframe>
</div>
</section>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<div class="abstract-block">
<p>Access to correct information is not sufficient for learning. One must still encounter it, evaluate it, assign sufficient credit to its source, and allow that information to modify one’s own knowledge. We study this chain with an agent-based model built from the MOVICI experiment. The 96 agents inherit characteristics from 96 real participants. The model distinguishes two learning pathways—Web information search and debate—as well as several stages between available expertise and effective learning. The first episode reproduces the main orders of magnitude observed in MOVICI: search yields a factual gain of about 1.4 points out of 20, whereas a single debate produces no substantial average gain. Subsequent episodes are generative experiments repeated up to 50 times, with 30 Monte Carlo replications for the main scenarios and the same-agent counterfactual. Two results dominate. First, in an information environment that continues to expand, a small differential associated with socioeconomic resources produces a growing absolute gap in knowledge stock, while the gap in knowledge density remains much smaller. Second, the simulated cooperative regime barely improves raw expertise recognition; instead, it mainly increases receptivity to partners in general. Agents give more weight to more knowledgeable partners, but also to less knowledgeable ones. This openness reduces missed corrective opportunities and increases factual knowledge acquisitions, while also increasing some losses; the advantage in net knowledge balance is therefore more variable. An ablation that neutralizes the credit-to-influence link removes the main social-learning advantage, whereas an ablation that preserves mean receptivity but removes differential allocation across partners leaves the mechanism largely intact. The model thus suggests that epistemic inclusion can improve without an equivalent improvement in social-calibration accuracy, and that small structural or interactional differences can generate cumulative trajectories when repeated.</p>
</div>
<div class="keywords">
<p><strong>Keywords:</strong> agent-based model; epistemic vigilance; epistemic credit; social receptivity; information search; debate; cumulative advantage; metacognition; social learning</p>
</div>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>Much of what we know comes from others. We learn from books, search engines, teachers, colleagues, and people close to us. This dependence makes the accumulation of knowledge possible. It also creates a simple problem: correct information may be available without being recognized, weighted, or used.</p>
<p>Epistemic vigilance refers to the mechanisms by which people evaluate information and the sources that convey it (Sperber et al., 2010). Such vigilance is not limited to deciding whether a source is reliable. At least four operations should be distinguished: identifying who appears benevolent and competent, assigning that person credit, giving weight to what they say, and then integrating—or not integrating—their information.</p>
<p>Research on groups has long shown that the presence of expertise does not guarantee its use (Hinsz et al., 1997; Hollingshead, 2000). The sociology of status likewise shows that recognized competence and influence can be shaped by social characteristics independent of objective performance (Berger et al., 1972; Foschi, 2000; Ridgeway, 2014). The central problem is therefore less ‘who knows?’ than ‘how does available knowledge become a resource for others?’</p>
<p>The MOVICI experiment provides a setting in which to study this problem. Participants first search for information on the Web and then debate in small groups. Their factual knowledge increases after search. After a single debate, the average factual gain is close to zero. The cooperative or competitive context is nevertheless associated with differences in how partners are evaluated. Most importantly, participants who direct their competence judgments more accurately toward partners who are objectively more knowledgeable show greater factual progress.</p>
<p>A short experiment cannot reveal what these mechanisms produce after dozens of episodes. This is where the agent-based model becomes useful. It is not intended to predict exactly what would happen after fifty real debates. Rather, it asks a mechanistic question: what follows from repeatedly applying local rules that are compatible with the observed data? This approach belongs to the tradition of generative explanation (Epstein, 1999) and empirically grounded agent-based modelling (Windrum et al., 2007; Stefanelli &amp; Seidl, 2017; Banisch &amp; Shamon, 2024).</p>
<p>Our question is therefore: how can small differences in opportunities to learn and in the credit assigned to others become cumulative? We examine information search, debate, and their sequence separately. We also test which mechanisms are necessary for the resulting patterns and whether the effect of the social regime depends on better discrimination among experts or on more general receptivity to others’ contributions.</p>
</section>
<section id="theoretical-framework-learning-from-a-socially-structured-world" class="level2">
<h2 class="anchored" data-anchor-id="theoretical-framework-learning-from-a-socially-structured-world">2. Theoretical Framework: Learning from a Socially Structured World</h2>
<section id="two-learning-pathways" class="level3">
<h3 class="anchored" data-anchor-id="two-learning-pathways">2.1. Two Learning Pathways</h3>
<p>The first pathway is learning from documents. Individuals must encounter information, devote attention to it, evaluate it, and integrate it. Previously acquired knowledge facilitates some forms of processing and can also reduce the cost of understanding new information.</p>
<p>The second pathway is learning through communication. It adds another difficulty: content arrives together with a human source. The learner must therefore evaluate both what is said and the person who says it. CAVL describes this situation as vigilant learning: cognitively resource-bounded, guided by prior knowledge, and dependent on cues about sources and the social context (Vayre et al., 2026d).</p>
<p>The model also distinguishes objective knowledge from each person’s estimate of their own competence. This distinction matters. Metacognitive judgments can be informed by actual performance, but also by cues of familiarity or fluency that are not always diagnostic (Nelson &amp; Narens, 1990; Koriat, 1997). Online search can, in particular, increase the feeling of knowing faster than information is actually retained in memory (Fisher et al., 2015).</p>
</section>
<section id="structural-and-interactional-embeddedness" class="level3">
<h3 class="anchored" data-anchor-id="structural-and-interactional-embeddedness">2.2. Structural and Interactional Embeddedness</h3>
<p>We use the term structural embeddedness when opportunities to learn depend on unequally distributed resources: time, equipment, familiarity with tools, digital skills, networks, or educational experience. In the model, the socioeconomic indicator is a simplified representation of these differences in conditions of existence. It is never interpreted as an intrinsic cognitive capacity.</p>
<p>This interpretation is consistent with research on digital inequalities. That literature shows that disparities concern not only material access, but also skills, uses, and the benefits obtained from technologies (Hargittai, 2010; Helsper, 2012; van Deursen &amp; Helsper, 2015; Scheerder et al., 2017).</p>
<p>We use the term interactional embeddedness when the local situation changes how information from others is processed. The partners who are present, their visibility, their way of interacting, and the group’s goal structure can all alter the credit they receive. This idea is compatible with Granovetter’s (1985) approach to embeddedness: decisions are neither purely individual nor wholly imposed by an abstract structure; they acquire meaning within concrete relationships.</p>
</section>
<section id="cooperation-competition-and-goal-structure" class="level3">
<h3 class="anchored" data-anchor-id="cooperation-competition-and-goal-structure">2.3. Cooperation, Competition, and Goal Structure</h3>
<p>The manipulation draws on social interdependence theory. In the cooperative condition, success is presented as shared. In the competitive condition, relative performance among participants is more salient. When goals are positively interdependent, another person’s contribution can help each participant achieve their own goal. When goals are negatively interdependent, another person’s relative success can become strategically ambivalent (Johnson &amp; Johnson, 2009).</p>
<p>This interpretation also connects with research on achievement goals. A mastery-oriented context makes revision and error more compatible with learning, whereas a performance-oriented context makes social comparison more central (Dweck &amp; Leggett, 1988; Ames, 1992; Elliot &amp; McGregor, 2001). Work on sociocognitive conflict shows more directly that mastery goals favour content-focused regulation, whereas performance goals favour more relational forms of regulation centred on relative competence (Darnon et al., 2006; Sommet et al., 2014). MOVICI does not, however, measure these individual goals. We therefore use this literature to interpret the experimental framing, not to attribute a measured motivational state to each participant.</p>
</section>
<section id="epistemic-credit-and-misallocation" class="level3">
<h3 class="anchored" data-anchor-id="epistemic-credit-and-misallocation">2.4. Epistemic Credit and Misallocation</h3>
<p>We define epistemic credit as the value assigned to a person as a source of knowledge. Assigning substantial credit to a competent person can facilitate learning. By contrast, assigning too little credit to someone who is more knowledgeable than oneself can mean losing an opportunity for correction.</p>
<p>The model therefore measures epistemic credit misallocation relative to objective competence. This concept is narrower than epistemic injustice. Testimonial injustice requires an unfair credibility deficit produced by prejudice or by a relevant social relation in the receiver’s judgment (Fricker, 2007). Recent methodological work emphasizes the need to distinguish empirically between a credibility deficit, prejudice, and the causal link between them (Arcila-Valenzuela &amp; Páez, 2024). The current model does not directly represent stigmatized social categories. Moreover, its main index is intentionally directional: it targets the underuse of available corrective expertise rather than all symmetric errors in credit calibration.</p>
<p>Perceived competence can also depend on imperfect social cues. Displayed confidence, dominance, or prestige can increase a person’s influence without directly measuring objective competence (Price &amp; Stone, 2004; Anderson &amp; Kilduff, 2009; Cheng et al., 2013). This distinction justifies separating actual competence from recognized competence.</p>
</section>
<section id="what-the-model-adds-to-existing-simulations" class="level3">
<h3 class="anchored" data-anchor-id="what-the-model-adds-to-existing-simulations">2.5. What the Model Adds to Existing Simulations</h3>
<p>Several agent-based models have already formalized epistemic vigilance. Butler et al.&nbsp;(2019, 2020) study deliberation and opinion diffusion with agents able to resist insufficient arguments. Reisinger et al.&nbsp;(2023) model plausibility, criticism, and gullibility. Laskowski et al.&nbsp;(2023) and Rybnik et al.&nbsp;(2023) also examine source competence and cooperation.</p>
<p>MOVICI-CAVL differs through four complementary choices. First, the outcome to be explained is a change in factual knowledge, rather than only an opinion or decision. Second, the model explicitly separates a partner’s actual competence, the competence attributed to that partner, the epistemic credit assigned to them, the effective weight of their information, and the learning that follows. Third, agents are initialized from real participants and the first episode is anchored to empirical signatures from MOVICI. Fourth, subsequent episodes extend these rules over time, and ablation tests distinguish mechanisms that are necessary from regularities that are merely associated. This combination of empirical anchoring, mechanistic decomposition, generative extension, and ablation tests is the model’s specific contribution to the social-simulation literature.</p>
</section>
</section>
<section id="empirical-basis-the-movici-experiment" class="level2">
<h2 class="anchored" data-anchor-id="empirical-basis-the-movici-experiment">3. Empirical Basis: The MOVICI Experiment</h2>
<section id="protocol" class="level3">
<h3 class="anchored" data-anchor-id="protocol">3.1. Protocol</h3>
<p>MOVICI includes 96 participants: 49 in the cooperative condition and 47 in the competitive condition. Participants first answer a 20-item factual-knowledge questionnaire on animal proteins. They then conduct approximately twenty minutes of open Web search. After recalling and evaluating the sources and arguments encountered, their knowledge is measured a second time. Participants then debate for twenty minutes, evaluate their partners, recall and assess arguments, and complete the factual questionnaire a third time. Table 1 summarises how this experimental sequence is translated into the model.</p>
<p>Debate groups contain two, three, or four participants. Condition assignment was not strictly randomised.</p>
<p>Table 1. From the Human Experiment to the Model</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Time point</strong></th>
<th style="text-align: left;"><strong>What the participant does</strong></th>
<th style="text-align: left;"><strong>What the model retains</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Before search</td>
<td style="text-align: left;">20 factual questions + self-estimated knowledge</td>
<td style="text-align: left;">Initial knowledge and self-estimate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Web search</td>
<td style="text-align: left;">Open search for approximately 20 minutes</td>
<td style="text-align: left;">Information exposure and direct learning</td>
</tr>
<tr class="odd">
<td style="text-align: left;">After search</td>
<td style="text-align: left;">Recall, evaluation, second factual questionnaire</td>
<td style="text-align: left;">Updated knowledge state and self-estimate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Debate</td>
<td style="text-align: left;">Discussion under cooperation or competition</td>
<td style="text-align: left;">Partner evaluation, assigned credit, social influence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">After debate</td>
<td style="text-align: left;">Partner evaluation, recall, third factual questionnaire</td>
<td style="text-align: left;">Final observed state</td>
</tr>
</tbody>
</table>
</section>
<section id="empirical-results-used" class="level3">
<h3 class="anchored" data-anchor-id="empirical-results-used">3.2. Empirical Results Used</h3>
<p>Information search produces a mean gain of 1.396 points out of 20 between the first and second measurements (Vayre et al., 2026a). Initial knowledge remains the main predictor of subsequent knowledge. A socioeconomic indicator also makes a positive contribution, whereas the future debate condition has no robust effect before the interaction.</p>
<p>The contrast between the second and third measurements is -0.229 points out of 20 and is not significantly positive (Vayre et al., 2026b). A single debate therefore produces no substantial average factual gain. The condition is, however, associated with differences in social evaluation. Participants in the cooperative condition report, in particular, higher perceived benevolence and better self-calibration; the analyses also converge on greater under-crediting in the competitive condition. Because condition assignment was not strictly randomised, these human differences are used as observational constraints rather than as causal estimates.</p>
<p>One result is particularly important for the model. A partner’s objective competence predicts very little of the competence attributed to that partner on average. Yet participants who allocate their competence judgments more strongly toward partners who are objectively more knowledgeable show greater factual progress. To measure this allocation quality, we transform the competence ratings assigned to partners into relative weights that sum to 1. We then calculate the partners’ mean factual score using those weights. A positive score means that the evaluator concentrates more attention on the more knowledgeable partners. A one-standard-deviation increase in this index predicts a +0.295-point increase at the final measurement, controlling for the previous knowledge level (p = .021; N = 73; 22 debates). Table 2 summarises the empirical results used to calibrate or check the model.</p>
<p>Table 2. Empirical Results That Constrain or Evaluate the Model</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 26%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>MOVICI observation</strong></th>
<th style="text-align: left;"><strong>Main value</strong></th>
<th style="text-align: left;"><strong>Role in the model</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gain after search</td>
<td style="text-align: left;">+1.396 / 20</td>
<td style="text-align: left;">Sets the order of magnitude for direct learning</td>
</tr>
<tr class="even">
<td style="text-align: left;">Effect of socioeconomic level after search</td>
<td style="text-align: left;">positive; standardised b = .472, p = .016</td>
<td style="text-align: left;">Introduces a small repeated opportunity/efficiency differential</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Effect of future condition on search</td>
<td style="text-align: left;">not robust; p = .440</td>
<td style="text-align: left;">No direct cooperation bonus during search</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gain after a single debate</td>
<td style="text-align: left;">-0.229 / 20; p = .176</td>
<td style="text-align: left;">Debate should remain close to zero in episode 1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cooperation and perceived benevolence</td>
<td style="text-align: left;">strong positive effect; p &lt; .001</td>
<td style="text-align: left;">Social context changes partner evaluation</td>
</tr>
<tr class="even">
<td style="text-align: left;">Allocation of competence toward the best partners</td>
<td style="text-align: left;">+0.295 points per SD; p = .021</td>
<td style="text-align: left;">Better credit orientation is associated with more learning</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="the-agent-based-model" class="level2">
<h2 class="anchored" data-anchor-id="the-agent-based-model">4. The Agent-Based Model</h2>
<p>This section follows the ODD protocol, widely used in JASSS. ODD stands for ‘Overview, Design concepts, and Details’ (Grimm et al., 2020). We therefore present the model’s purpose, agents, and sequence of operations first. The equations and parameters follow. This allows readers to understand the general logic before moving into the formalization.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 99%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>The Model in 30 Seconds</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Each agent represents a MOVICI participant. Agents possess factual knowledge and an estimate of their own competence. During search, they encounter information and may acquire or lose factual knowledge. During debate, they evaluate partners, assign them more or less credit, and then give more or less weight to what those partners know. The model repeats these episodes to observe what accumulates. Cooperation and competition never award knowledge points directly: they only change how partners and the self are evaluated.</td>
</tr>
</tbody>
</table>
<section id="purpose-of-the-model" class="level3">
<h3 class="anchored" data-anchor-id="purpose-of-the-model">4.1. Purpose of the Model</h3>
<p>The model seeks to explain how two short-term mechanisms can generate long-term trajectories: first, small repeated differences in opportunities to learn during search; and second, repeated differences in the credit and receptivity assigned to partners during debate. The first episode is anchored in MOVICI. Episodes 2 to 50 are generative virtual experiments rather than chronological forecasts.</p>
</section>
<section id="agents-and-information-environment" class="level3">
<h3 class="anchored" data-anchor-id="agents-and-information-environment">4.2. Agents and Information Environment</h3>
<p>The model contains 96 agents. Each agent inherits data from a real participant: factual responses, self-estimated knowledge, a socioeconomic indicator, and selected indices describing visibility and relational style during debate.</p>
<p>The information environment initially contains 20 facts corresponding to the 20 questionnaire items. We examine two environments. In the fixed world, no new facts appear. In the renewed world, 3 new facts are added from the second episode onward; their difficulty is drawn from the distribution observed in MOVICI. After the first empirically anchored episode, both environments use the same exposure budget. The comparison therefore distinguishes learning in a finite world from learning in an information environment that continues to expand.</p>
</section>
<section id="an-information-search-episode" class="level3">
<h3 class="anchored" data-anchor-id="an-information-search-episode">4.3. An Information-Search Episode</h3>
<p>Simulated search comprises two successive regimes. The first episode provides empirical anchoring: the calibrated transition kernel is applied to the 20 initial items to remain directly comparable with MOVICI. From the second episode onward, FIXED and RENEWED use the same limited-exposure engine: each agent has ten information encounters per episode; in RENEWED, up to two may be reserved for newly introduced facts. Encounter reliability is set to 0.80 as a scenario assumption, not as an empirical estimate of Web reliability. Table 3 summarises this sequence.</p>
<p>Table 3. Sequence of an Information-Search Episode</p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 80%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Step</strong></th>
<th style="text-align: left;"><strong>What happens</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. Anchoring / world update</td>
<td style="text-align: left;">In episode 1, the 20 MOVICI facts form the full pool. From episode 2 onward, RENEWED adds new facts; FIXED remains at 20 facts.</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. The agent encounters facts</td>
<td style="text-align: left;">Episode 1: the calibrated kernel is applied to the full pool. Episodes 2–50: ten encounters per agent in both FIXED and RENEWED; up to two are reserved for new facts in RENEWED.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. The encounter may be reliable or misleading</td>
<td style="text-align: left;">From episode 2 onward, an encounter is reliable with probability 0.80. This value is a scenario assumption, not an estimate of Web reliability.</td>
</tr>
<tr class="even">
<td style="text-align: left;">4. The agent may acquire or lose a fact</td>
<td style="text-align: left;">A reliable encounter can produce an acquisition; a misleading encounter can produce a loss. Probabilities depend on prior knowledge, socioeconomic level, fact difficulty, and an information-vigilance state.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5. The agent revises the self-estimate</td>
<td style="text-align: left;">The estimate depends on the previous self-estimate, new knowledge, and a navigation index based on search-engine results pages.</td>
</tr>
</tbody>
</table>
</section>
<section id="a-debate-episode" class="level3">
<h3 class="anchored" data-anchor-id="a-debate-episode">4.4. A Debate Episode</h3>
<p>Debate adds a social layer. Partners do not automatically transmit what they know. A partner’s information must first receive enough credit to affect learning. A social update can lead to an acquisition (0→1) when the partner possesses a fact the agent lacks, but also to a loss or erroneous revision (1→0) when a heavily weighted partner does not possess a fact currently held by the agent. Table 4 summarises the sequence.</p>
<p>Table 4. Sequence of a Debate Episode</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 88%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Step</strong></th>
<th style="text-align: left;"><strong>What happens</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. Group formation</td>
<td style="text-align: left;">Agents are grouped only with others from the same condition. The main scenario reproduces as closely as possible the observed distribution of groups of 2, 3, and 4.</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. Partner rotation</td>
<td style="text-align: left;">In the main scenario, partners rotate at each episode. Fixed partners are tested separately as a robustness check.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. Evaluation of each partner</td>
<td style="text-align: left;">Each agent estimates partners’ competence and benevolence. These evaluations depend on observed cues and on the cooperative or competitive condition, plus a stochastic component.</td>
</tr>
<tr class="even">
<td style="text-align: left;">4. Credit assignment</td>
<td style="text-align: left;">Perceived competence and benevolence are combined to obtain the value assigned to the partner as a source of knowledge.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5. From credit to influence</td>
<td style="text-align: left;">Partner credit is compared with the agent’s self-estimate. The more a partner is credited relative to the self, the more weight their information receives.</td>
</tr>
<tr class="even">
<td style="text-align: left;">6. Possible fact transfer</td>
<td style="text-align: left;">For each directed evaluator–partner relation, one fact is drawn from the available world. Partner weight modulates a possible factual acquisition (0→1) when the partner has the fact and the agent does not, or a possible loss (1→0) when the agent has the fact but a heavily weighted partner does not.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7. Self-model update</td>
<td style="text-align: left;">The agent also revises their estimate of their own competence. Under cooperation, factual knowledge re-anchors this estimate more strongly.</td>
</tr>
</tbody>
</table>
</section>
<section id="what-cooperation-and-competition-change" class="level3">
<h3 class="anchored" data-anchor-id="what-cooperation-and-competition-change">4.5. What Cooperation and Competition Change</h3>
<p>The difference between cooperation and competition is restricted to specific social mechanisms. It does not directly change the probability of knowing a fact. In the model, the social regime changes partners’ perceived competence, their perceived benevolence, and the way the agent updates their self-estimate. Factual consequences can arise only afterward, if these differences alter epistemic credit, the weight assigned to partners, and thus the use of their information.</p>
<p>This construction translates a hypothesis from social interdependence theory: cooperation makes using another person’s contribution more compatible with the group goal, whereas competition makes performance comparison more salient (Johnson &amp; Johnson, 2009). It is also consistent with work showing that social motivation directs the search for and use of information in groups (De Dreu et al., 2008), that performance goals favour relational forms of conflict regulation (Darnon et al., 2006; Sommet et al., 2014), and that a cooperative or competitive mindset changes the effect of social comparison on self-evaluation (Colpaert et al., 2015). We do not assume, however, that each participant has a measured mastery or performance goal.</p>
</section>
<section id="sequencing-search-and-debate" class="level3">
<h3 class="anchored" data-anchor-id="sequencing-search-and-debate">4.6. Sequencing Search and Debate</h3>
<p>In the coupled scenario, each cycle begins with search and is followed by debate. The debate therefore uses the knowledge and self-estimate that were just updated by search. In the renewed environment, new facts are added during search; they are not added a second time during debate.</p>
<p><img src="figures/image1.png" style="width:6.3in;height:3.39379in"></p>
<p>Figure 1. General logic of the model. The first search episode anchors the model to MOVICI; subsequent episodes use a limited exposure budget. Debate adds source recognition, epistemic credit, receptivity, and information weighting before a possible acquisition or loss of a fact.</p>
</section>
<section id="measuring-the-use-of-expertise" class="level3">
<h3 class="anchored" data-anchor-id="measuring-the-use-of-expertise">4.7. Measuring the Use of Expertise</h3>
<p>We use several complementary indicators that answer different questions. In particular, we distinguish expertise recognition, mean epistemic credit, the weight assigned to more- or less-knowledgeable partners, the use of corrective opportunities, and calibration errors. Code variable names are deliberately kept out of the main text and are provided in the Appendix for replication. Table 5 defines these indicators in plain language.</p>
<p>Table 5. Main Social Indicators</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 78%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Question</strong></th>
<th style="text-align: left;"><strong>Measure in plain language</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Does the agent know who is more knowledgeable?</td>
<td style="text-align: left;">Accuracy in ranking partners by their actual competence.</td>
</tr>
<tr class="even">
<td style="text-align: left;">How much credit does the agent assign to partners?</td>
<td style="text-align: left;">Mean credit assigned to others as sources of knowledge.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Does the agent give more weight to genuinely better partners?</td>
<td style="text-align: left;">Mean weight assigned to partners who know more than the agent.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Does the agent use available corrective opportunities?</td>
<td style="text-align: left;">Share of potential corrective knowledge that actually receives weight.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">How many corrective opportunities are missed?</td>
<td style="text-align: left;">Complement of the preceding measure.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Is credit misallocated?</td>
<td style="text-align: left;">Mean of three directional errors: (1) missed corrective opportunities; (2) a credit-rank reversal when a partner is more knowledgeable; (3) underweighting a more knowledgeable partner. Over-crediting less knowledgeable partners is measured separately.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Does the agent also give weight to less knowledgeable partners?</td>
<td style="text-align: left;">Mean weight assigned to partners who know less than the agent; a diagnostic of general receptivity and potential over-crediting.</td>
</tr>
</tbody>
</table>
</section>
<section id="mathematical-formalization-with-intuitive-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="mathematical-formalization-with-intuitive-interpretation">4.8. Mathematical Formalization with Intuitive Interpretation</h3>
<p>The preceding subsections are sufficient to understand the model’s logic. We now provide the equations used in the RStudio package. The essential point is where the numbers come from. They are not all chosen in the same way. Some coefficients are estimated directly from MOVICI. Others are calibrated to preserve an empirical signature when the model is extended. Finally, a small number of parameters are modelling conventions and are therefore examined through sensitivity analysis.</p>
<section id="where-do-the-coefficients-come-from" class="level4">
<h4 class="anchored" data-anchor-id="where-do-the-coefficients-come-from">Where Do the Coefficients Come From?</h4>
<p>Factual search. The constants, the effect of knowledge level, the socioeconomic effect, and the effect of fact difficulty come from a logistic calibration of item-level transitions observed in MOVICI. The small socioeconomic effect is therefore not chosen to manufacture long-term divergence: it is fixed from episode 1 and then repeated without retuning.</p>
<p>Metacognition. The coefficients linking the previous self-estimate, factual knowledge, and the share of time spent on search-engine results pages come from a regression estimated on the 96 participants. In MOVICI, subjective change tracks factual gain only weakly, and a greater relative amount of time on results pages predicts higher subjective knowledge at controlled factual knowledge. This exploratory result is compatible with the ‘illusion of knowledge’ described by Fisher et al.&nbsp;(2015), without by itself demonstrating a general illusion in MOVICI (Vayre et al., 2026a).</p>
<p>Debate. The effects of condition, partner visibility, and relational style on perceived competence and benevolence are estimated from MOVICI’s dyadic evaluations. Persistence in the self-estimate and its re-anchoring by knowledge under cooperation are also estimated from MOVICI. By contrast, the contribution of benevolence to credit (0.169) is a calibration parameter retained from earlier ABM development, and the scale transforming the credit gap into weight (1.0) is a modelling convention. The RStudio package explicitly tests sensitivity to the former parameter (0; 0.169; 0.338) and to the credit-to-weight scale. These parameters should therefore not be presented as coefficients directly estimated in the experiment.</p>
<p>Three notations are sufficient to read the equations.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 99%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Three Notations to Know</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">g(x) = 1 / [1 + exp(-x)] transforms any score into a probability between 0 and 1. z(x) simply indicates a value’s position relative to the sample mean, in standard-deviation units. Finally, I_coop is an indicator: it equals 1 under cooperation and 0 under competition.</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>P(learn a fact) = g[-0.3975 + 0.0527·z(knowledge) + 0.1357·z(socioeconomic level) + 0.9881·fact ease + 0.1400·z(vigilance during search)]</li>
</ol>
<p>In plain language. For a fact encountered during search, learning becomes slightly more likely when the agent has more prior knowledge, when socioeconomic resources are more favorable, when the fact is easier to learn, and when the agent’s information-vigilance state is more favorable. These coefficients come from item-level calibration on MOVICI. The socioeconomic coefficient is small in episode 1; the simulation experiment examines what its repetition produces.</p>
<ol start="2" type="1">
<li>P(lose a known fact) = g[-0.7216 - 0.2155·z(knowledge) - 0.1357·z(socioeconomic level) - 0.9881·fact ease - 0.1400·z(vigilance during search)]</li>
</ol>
<p>In plain language. The model also allows loss or incorrect integration. The preceding factors then act in the opposite direction. The coefficients in this equation are calibrated using the same item-level transition data as the learning equation.</p>
<ol start="3" type="1">
<li>next self-estimate = bound[1,4](2.3646 + 0.2797·z(previous self-estimate) + 0.1810·z(current knowledge) + 0.1289·navigation index + noise)</li>
</ol>
<p>In plain language. The agent does not reassess competence from scratch. The previous judgment matters, current knowledge matters, and the share of time spent on search-engine results pages provides an additional cue. All three coefficients are estimated from MOVICI. The last captures the exploratory association between relative time on results pages and subjective knowledge, controlling for factual knowledge (Vayre et al., 2026a).</p>
<ol start="4" type="1">
<li>partner’s perceived competence = 0.1580 - 0.0127·visibility - 0.4093·Icomp + 0.3714·visibility·Icomp + noise</li>
</ol>
<p>In plain language. Perceived competence depends on a visibility index observed during debate and on condition. These coefficients are estimated from MOVICI’s dyadic evaluations. The interaction indicates that visibility does not play the same role under cooperation and competition.</p>
<ol start="5" type="1">
<li>perceived benevolence = 0.3652 + 0.0880·relational style - 0.7447·Icomp + noise</li>
</ol>
<p>In plain language. Perceived benevolence depends on a relational index observed in the exchanges and on condition. The strong negative competition term reproduces the empirical result that perceived benevolence is substantially higher in the cooperative condition (Vayre et al., 2026b).</p>
<ol start="6" type="1">
<li>credit assigned to partner = perceived competence + 0.169·perceived benevolence</li>
</ol>
<p>In plain language. Epistemic credit combines perceived competence and perceived benevolence. The coefficient 0.169 is not directly estimated in the final dyadic regression; it is a calibration parameter retained from model development. Its function is to allow a relational component, weaker than the competence component, to contribute to credit.</p>
<ol start="7" type="1">
<li>partner weight = g[(partner credit - self-estimate) / 1]</li>
</ol>
<p>In plain language. The same partner does not receive the same weight from every agent. If the partner’s credit exceeds the agent’s self-estimate, that partner’s information receives greater weight. The transformation scale is fixed at 1 by convention and then varied in the sensitivity analysis.</p>
<ol start="8" type="1">
<li>P(learn from partner) = P(learn content) × partner weight</li>
</ol>
<p>In plain language. A partner may possess relevant information without that information being integrated. Social weight acts as a gate for uptake and revision. The credit-to-influence link is tested through an ablation that fixes every partner’s weight at 0.5. This intervention is a causal-necessity test within the model; by itself, it does not identify the causal mechanism in the human participants.</p>
<ol start="9" type="1">
<li>next self-estimate = 0.7446·previous self-estimate + 0.1295·z(knowledge)·Icoop + 0.6297·noise</li>
</ol>
<p>In plain language. The self-estimate is persistent. The coefficients 0.7446 and 0.1295 are estimated in a constrained model fitted to MOVICI. Under cooperation, factual knowledge contributes to re-anchoring self-evaluation; under competition, this direct term is fixed at zero in the retained specification. This asymmetry corresponds to the empirical differences in self-calibration observed across conditions (Vayre et al., 2026b).</p>
<ol start="10" type="1">
<li>expertise-use efficiency = Σ(corrective opportunities × partner weight) / Σ(corrective opportunities)</li>
</ol>
<p>In plain language. In the implementation, the corrective opportunity offered by a partner is the positive difference between that partner’s knowledge stock and the agent’s. It is zero when the partner does not know more. Expertise-use efficiency is the mean of these gaps weighted by the weight actually assigned to the partner. The missed-opportunity rate equals 1 minus this efficiency.</p>
<ol start="11" type="1">
<li>epistemic credit misallocation = mean[missed corrective opportunities; credit-rank reversals; underweighting of a more knowledgeable partner]</li>
</ol>
<p>In plain language. The composite index combines the three errors defined in Table 5: missed corrective opportunities, credit-rank reversals, and underweighting of a more knowledgeable partner. It is computed only when the comparison is defined. The index is intentionally directional: it measures underuse of available corrective expertise rather than all possible calibration errors. Over-crediting a less knowledgeable partner is tracked separately; it can constitute miscalibration and increase some losses, but it is not in itself a credibility deficit suffered by the over-credited partner. The main index therefore does not, by itself, measure epistemic injustice.</p>
</section>
</section>
</section>
<section id="simulation-experiments" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiments">5. Simulation Experiments</h2>
<p>The model description and the simulation experiment are distinct. The model defines the rules; the experiments below define the situations in which those rules are run. This distinction is important for interpreting the results correctly.</p>
<section id="the-six-main-scenarios" class="level3">
<h3 class="anchored" data-anchor-id="the-six-main-scenarios">5.1. The Six Main Scenarios</h3>
<p>We cross three learning modes with two types of information environment, yielding six scenarios. Each scenario is repeated 30 times with different random draws. The same 96 agents are re-created from the MOVICI data at the beginning of every replication. Table 6 presents the six main scenarios.</p>
<p>Table 6. The Six Main Scenarios</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 24%">
<col style="width: 35%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Learning mode</strong></th>
<th style="text-align: left;"><strong>Fixed world</strong></th>
<th style="text-align: left;"><strong>Renewed world</strong></th>
<th style="text-align: left;"><strong>Question</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Search only</td>
<td style="text-align: left;">20 facts available throughout the simulation</td>
<td style="text-align: left;">3 new facts per cycle from episode 2 onward</td>
<td style="text-align: left;">Does learning saturate when the world is finite? Does it continue when new information appears?</td>
</tr>
<tr class="even">
<td style="text-align: left;">Debate only</td>
<td style="text-align: left;">Partners exchange information in a world of 20 factual-knowledge items</td>
<td style="text-align: left;">New facts are added and distributed in the population to maintain new opportunities for social learning</td>
<td style="text-align: left;">Can effects that are weak in the short run become cumulative?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Search then debate</td>
<td style="text-align: left;">Search followed by debate on the same updated state</td>
<td style="text-align: left;">Search adds new facts; debate then uses that world without a second expansion</td>
<td style="text-align: left;">Does search-based learning change dependence on others’ contributions and the self-model?</td>
</tr>
</tbody>
</table>
<p>In the renewed debate-only scenario, new facts must be distributed somewhere in the population; otherwise no agent could transmit them. These exogenous additions are not counted as social learning. To measure learning produced by debate, we count only acquisitions minus losses generated through exchanges among agents.</p>
</section>
<section id="what-an-episode-means" class="level3">
<h3 class="anchored" data-anchor-id="what-an-episode-means">5.2. What an Episode Means</h3>
<p>An episode is not a day, week, or year. It represents an abstract occurrence of the process under study: one search, one debate, or one search followed by one debate. We observe episodes 1, 5, 10, 15, 20, 25, and 50. Long-run results therefore describe the shape of repeated dynamics, not a chronological forecast.</p>
</section>
<section id="group-composition-and-partner-rotation" class="level3">
<h3 class="anchored" data-anchor-id="group-composition-and-partner-rotation">5.3. Group Composition and Partner Rotation</h3>
<p>In the main debate simulations, agents remain in their empirical condition: 49 under cooperation and 47 under competition. Groups are formed separately within each condition. In the empirical distribution, 17 participants belong to groups of 2, 35 to groups of 3, and 44 to groups of 4. Because groups must also be separated by condition, the closest feasible partition is 16, 36, and 44 participants, respectively. Partners are then recomposed at each episode.</p>
</section>
<section id="same-agent-counterfactual-comparison" class="level3">
<h3 class="anchored" data-anchor-id="same-agent-counterfactual-comparison">5.4. Same-Agent Counterfactual Comparison</h3>
<p>A population comparison can conflate contextual effects with initial differences between people. We therefore add a stricter computational intervention. Each agent is simulated twice from exactly the same initial state: once under the cooperative regime and once under the competitive regime. Random draws are paired as closely as possible between the two versions. The resulting difference therefore isolates the causal effect of the mechanisms that the model makes regime-dependent, conditional on the formalized architecture.</p>
<p>This comparison is limited to the renewed debate-only and search-then-debate scenarios. It does not claim to reconstruct all behavioural mediations that might occur in the human experiment, nor does it retrospectively turn MOVICI into a randomised trial. In this article, causal language is reserved for interventions performed within the model; human differences between conditions remain observational constraints.</p>
</section>
<section id="mechanism-robustness-and-sensitivity-tests" class="level3">
<h3 class="anchored" data-anchor-id="mechanism-robustness-and-sensitivity-tests">5.5. Mechanism, Robustness, and Sensitivity Tests</h3>
<p>We conduct four mechanism-removal or mechanism-neutralization tests. Each modifies one specific rule and reruns the simulation. These interventions identify which components are necessary for the model result and distinguish general receptivity from differential allocation across sources. Table 7 summarises the four tests.</p>
<p>Table 7. Mechanism-Removal Tests</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 42%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Test</strong></th>
<th style="text-align: left;"><strong>What is removed or neutralized</strong></th>
<th style="text-align: left;"><strong>Question</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Remove the socioeconomic search effect</td>
<td style="text-align: left;">The small coefficient associated with socioeconomic resources is set to zero</td>
<td style="text-align: left;">Does the cumulative knowledge gap disappear?</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remove relational memory</td>
<td style="text-align: left;">Evaluations of a partner are no longer averaged with previous encounters</td>
<td style="text-align: left;">Does the dynamic depend on a persistent dyadic relationship?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Remove the credit → influence link</td>
<td style="text-align: left;">All partners receive a fixed weight of 0.5, regardless of the credit assigned to them</td>
<td style="text-align: left;">Does social credit still produce a learning advantage when it can no longer change influence?</td>
</tr>
<tr class="even">
<td style="text-align: left;">Neutralize differential credit allocation</td>
<td style="text-align: left;">Each evaluator’s mean partner weight is preserved, but that same weight is assigned to all of their partners</td>
<td style="text-align: left;">Does the effect arise from general receptivity to others or from fine-grained allocation across sources?</td>
</tr>
</tbody>
</table>
<p>We also conduct two social-robustness checks: fixed partners instead of rotating partners, and groups of four for all agents. Three targeted sensitivity analyses separately vary the rate at which new information arrives, the strength with which the credit gap is transformed into weight, and the contribution of benevolence to credit. To limit computational cost, these extensions are repeated five times per variant, whereas the main scenarios and same-agent counterfactual are repeated 30 times. This strategy prioritizes targeted mechanistic tests over an exhaustive sweep of all parameters (Thiele et al., 2014).</p>
</section>
<section id="why-30-replications" class="level3">
<h3 class="anchored" data-anchor-id="why-30-replications">5.6. Why 30 Replications?</h3>
<p>A simulation contains stochasticity, so two otherwise identical executions may produce slightly different values. We repeat the main scenarios 30 times and summarise variation across these replications. Simulation replications are never treated as 30 additional human participants. Monte Carlo quantiles describe variability across simulated worlds; they are not confidence intervals for a human population. We also examine the stability of estimates across 10, 20, and 30 replications.</p>
</section>
</section>
<section id="empirical-anchoring-and-first-episode-checks" class="level2">
<h2 class="anchored" data-anchor-id="empirical-anchoring-and-first-episode-checks">6. Empirical Anchoring and First-Episode Checks</h2>
<p>We distinguish two uses of the MOVICI data. A calibration value is used directly to set a model mechanism. A structural check is used differently: it verifies that the model does not produce a result that is clearly incompatible with the experiment. This distinction avoids presenting a value used in model construction as independent validation. Table 8 compares the human data with the first simulated episode.</p>
<p>Table 8. Comparison of Human Data and the First Simulated Episode</p>
<table class="caption-top table">
<colgroup>
<col style="width: 55%">
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Signature</strong></th>
<th style="text-align: left;"><strong>MOVICI</strong></th>
<th style="text-align: left;"><strong>Simulation, episode 1</strong></th>
<th style="text-align: left;"><strong>Use</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Factual gain after search (/20)</td>
<td style="text-align: left;">+1.396</td>
<td style="text-align: left;">+1.423</td>
<td style="text-align: left;">Calibration</td>
</tr>
<tr class="even">
<td style="text-align: left;">Factual gain after debate (/20)</td>
<td style="text-align: left;">-0.229</td>
<td style="text-align: left;">+0.039</td>
<td style="text-align: left;">Structural check</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Raw effect of socioeconomic level after search</td>
<td style="text-align: left;">+0.562</td>
<td style="text-align: left;">+0.525</td>
<td style="text-align: left;">Calibration</td>
</tr>
<tr class="even">
<td style="text-align: left;">Effect of cooperation/competition condition on learning during information search</td>
<td style="text-align: left;">+0.284</td>
<td style="text-align: left;">-0.110</td>
<td style="text-align: left;">Structural check</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Effect of cooperation on perceived competence</td>
<td style="text-align: left;">+0.410</td>
<td style="text-align: left;">+0.406</td>
<td style="text-align: left;">Calibration</td>
</tr>
<tr class="even">
<td style="text-align: left;">Effect of cooperation on perceived benevolence</td>
<td style="text-align: left;">+0.712</td>
<td style="text-align: left;">+0.774</td>
<td style="text-align: left;">Calibration</td>
</tr>
</tbody>
</table>
<p>Differences are small for the main calibration targets. The post-search gain is +1.396 in MOVICI and +1.423 in the simulation. The aggregate socioeconomic effect is +0.562 in the data and +0.525 in the simulation, whereas the elementary SES coefficient was calibrated at the item-transition level. Condition-associated effects on perceived competence and benevolence are also close. The gain after a single debate remains close to zero in both cases, although its direction differs. The human effect of future debate condition on search, used only as a structural check, is not reproduced and was not robust in MOVICI.</p>
<p>The supplementary analysis of functional expertise allocation is also reproduced in the replication scripts: a one-standard-deviation improvement in allocation predicts +0.295 points of final knowledge, controlling for prior knowledge (CR2 p = .021; N = 73; 22 debates).</p>
</section>
<section id="simulation-results" class="level2">
<h2 class="anchored" data-anchor-id="simulation-results">7. Simulation Results</h2>
<section id="search-saturates-in-a-fixed-world-and-continues-in-a-renewed-world" class="level3">
<h3 class="anchored" data-anchor-id="search-saturates-in-a-fixed-world-and-continues-in-a-renewed-world">7.1. Search Saturates in a Fixed World and Continues in a Renewed World</h3>
<p>In the fixed world, agents learn progressively and then approach a plateau. Mean gain is +1.423 facts at the first episode, +4.392 at the fifth, +5.989 at the tenth, +7.215 at the twenty-fifth, and +7.420 at the fiftieth. Agents then master, on average, about 82% of the 20 available facts. Table 9 presents the full trajectories for the six scenarios.</p>
<p>In the renewed world, the same exposure engine does not saturate in the same way. Mean gain reaches +7.184 at the fifth episode, +14.827 at the tenth, +37.805 at the twenty-fifth, and +76.448 at the fiftieth. At that point, agents know an average of 85.448 facts, or about 51% of the available information environment. The FIXED/RENEWED comparison therefore holds the exposure budget constant after episode 1; what changes is whether new information can continue to enter the environment.</p>
<p>Table 9. Net Knowledge Gain or Cumulative Social Learning by Scenario</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Scenario</strong></th>
<th style="text-align: left;"><strong>1</strong></th>
<th style="text-align: left;"><strong>5</strong></th>
<th style="text-align: left;"><strong>10</strong></th>
<th style="text-align: left;"><strong>25</strong></th>
<th style="text-align: left;"><strong>50</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Search, fixed world</td>
<td style="text-align: left;">1.423</td>
<td style="text-align: left;">4.392</td>
<td style="text-align: left;">5.989</td>
<td style="text-align: left;">7.215</td>
<td style="text-align: left;">7.420</td>
</tr>
<tr class="even">
<td style="text-align: left;">Search, renewed world</td>
<td style="text-align: left;">1.423</td>
<td style="text-align: left;">7.184</td>
<td style="text-align: left;">14.827</td>
<td style="text-align: left;">37.805</td>
<td style="text-align: left;">76.448</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Debate, fixed world</td>
<td style="text-align: left;">0.039</td>
<td style="text-align: left;">0.142</td>
<td style="text-align: left;">0.256</td>
<td style="text-align: left;">0.531</td>
<td style="text-align: left;">0.782</td>
</tr>
<tr class="even">
<td style="text-align: left;">Debate, renewed world</td>
<td style="text-align: left;">0.039</td>
<td style="text-align: left;">0.144</td>
<td style="text-align: left;">0.242</td>
<td style="text-align: left;">0.543</td>
<td style="text-align: left;">1.105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Search then debate, fixed world</td>
<td style="text-align: left;">1.445</td>
<td style="text-align: left;">4.391</td>
<td style="text-align: left;">5.949</td>
<td style="text-align: left;">7.154</td>
<td style="text-align: left;">7.373</td>
</tr>
<tr class="even">
<td style="text-align: left;">Search then debate, renewed world</td>
<td style="text-align: left;">1.445</td>
<td style="text-align: left;">7.232</td>
<td style="text-align: left;">14.899</td>
<td style="text-align: left;">37.897</td>
<td style="text-align: left;">76.601</td>
</tr>
</tbody>
</table>
</section>
<section id="a-small-socioeconomic-differential-produces-cumulative-advantage-in-an-expanding-information-environment" class="level3">
<h3 class="anchored" data-anchor-id="a-small-socioeconomic-differential-produces-cumulative-advantage-in-an-expanding-information-environment">7.2. A Small Socioeconomic Differential Produces Cumulative Advantage in an Expanding Information Environment</h3>
<p>In the renewed environment, the knowledge-stock gap associated with socioeconomic level is already positive in the first episode: +0.525 facts. It then increases steadily: +0.852 at episode 5, +1.241 at episode 10, +2.607 at episode 25, and +4.946 at episode 50. The search-then-debate scenario produces an almost identical trajectory. Relative to the size of the world, the density gap is much smaller but remains positive, increasing from about +0.026 in the first episode to +0.030 in the fiftieth. Table 10 reports effects on stock and density jointly.</p>
<p>Together, these results clarify the form of cumulative advantage. The model does not show unlimited proportional divergence within a closed stock. Instead, it shows that a small differential in opportunity or efficiency, repeated in an information environment that continues to expand, generates a growing absolute knowledge gap while maintaining a much smaller relative differential. This assumption is substantively plausible for scientific and digital environments in which new knowledge continually becomes available. When the socioeconomic coefficient is set to zero, the SES effect on knowledge stock at episode 50 becomes -0.124 in search alone and +0.218 in the coupled scenario, with Monte Carlo quantiles broadly including zero; density effects likewise become close to zero.</p>
<p>Table 10. Evolution of the Knowledge Gap Associated with Socioeconomic Level</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Scenario</strong></th>
<th style="text-align: left;"><strong>Episode 1</strong></th>
<th style="text-align: left;"><strong>5</strong></th>
<th style="text-align: left;"><strong>10</strong></th>
<th style="text-align: left;"><strong>25</strong></th>
<th style="text-align: left;"><strong>50</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Renewed search – SES effect on stock</td>
<td style="text-align: left;">0.525</td>
<td style="text-align: left;">0.852</td>
<td style="text-align: left;">1.241</td>
<td style="text-align: left;">2.607</td>
<td style="text-align: left;">4.946</td>
</tr>
<tr class="even">
<td style="text-align: left;">Renewed search – SES effect on density</td>
<td style="text-align: left;">0.0262</td>
<td style="text-align: left;">0.0266</td>
<td style="text-align: left;">0.0264</td>
<td style="text-align: left;">0.0283</td>
<td style="text-align: left;">0.0296</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Renewed coupled – SES effect on stock</td>
<td style="text-align: left;">0.528</td>
<td style="text-align: left;">0.882</td>
<td style="text-align: left;">1.299</td>
<td style="text-align: left;">2.612</td>
<td style="text-align: left;">4.991</td>
</tr>
<tr class="even">
<td style="text-align: left;">Renewed coupled – SES effect on density</td>
<td style="text-align: left;">0.0264</td>
<td style="text-align: left;">0.0276</td>
<td style="text-align: left;">0.0276</td>
<td style="text-align: left;">0.0284</td>
<td style="text-align: left;">0.0299</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No SES effect – search, episode 50</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">-0.124 stock; -0.0007 density</td>
</tr>
<tr class="even">
<td style="text-align: left;">No SES effect – coupled, episode 50</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">+0.218 stock; +0.0013 density</td>
</tr>
</tbody>
</table>
<p>Reading. The absolute gap widens in a renewed world, whereas the relative density gap remains much smaller. Ablating the socioeconomic coefficient almost completely removes this gradient. The model also contains weak cognitive recursion: previously acquired knowledge slightly facilitates subsequent acquisition and reduces the probability of loss.</p>
</section>
<section id="a-single-debate-produces-little-learning-but-repeated-debates-can-accumulate" class="level3">
<h3 class="anchored" data-anchor-id="a-single-debate-produces-little-learning-but-repeated-debates-can-accumulate">7.3. A Single Debate Produces Little Learning, but Repeated Debates Can Accumulate</h3>
<p>Debate remains far less powerful than search for factual-knowledge learning. After one episode, the mean social-learning gain is +0.039. In the fixed world, cumulative net learning reaches +0.782 by episode 50. In the renewed world, it reaches +1.105. The important result is not that debate becomes a massive source of knowledge. Rather, a very small effect in each episode can nevertheless accumulate when partners and corrective opportunities are renewed.</p>
</section>
<section id="in-the-model-the-cooperative-regime-mainly-increases-social-receptivity" class="level3">
<h3 class="anchored" data-anchor-id="in-the-model-the-cooperative-regime-mainly-increases-social-receptivity">7.4. In the Model, the Cooperative Regime Mainly Increases Social Receptivity</h3>
<p>The same-agent counterfactual provides the clearest test. At episode 50, imposing the cooperative rather than the competitive regime hardly improves agents’ ability to rank partners by their actual competence: the cooperation-minus-competition difference is -0.012 and fluctuates around zero across replications. Table 11 gives the complete trajectory; Figure 2 summarises several differences at episode 50.</p>
<p>By contrast, the cooperative regime strongly increases the mean credit assigned to partners (+0.531). It increases the weight assigned to more knowledgeable partners (+0.163), but also the weight assigned to less knowledgeable partners (+0.133). The effect is therefore primarily an increase in social receptivity rather than an improvement in raw expertise detection. This openness increases the share of corrective opportunities that are actually used (+0.161), reduces the missed corrective opportunity rate (-0.161), and lowers the directional epistemic credit misallocation index by 0.238.</p>
<p>Factual consequences emerge slowly and must be separated into acquisitions and losses. The cooperative advantage in cumulative acquisitions grows from +0.014 in the first episode to +1.257 at episode 50, but cumulative losses also increase by +0.841. The mean net balance at episode 50 is therefore only +0.416 and varies more across replications (Monte Carlo quantiles: -0.427 to +1.131). The most robust conclusion thus concerns receptivity, use of corrective opportunities, and acquisitions rather than a guaranteed advantage in final knowledge stock.</p>
<p>Table 11. The Same Agent Simulated under Cooperation and Competition</p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Cooperation - competition difference</strong></th>
<th style="text-align: left;"><strong>1</strong></th>
<th style="text-align: left;"><strong>10</strong></th>
<th style="text-align: left;"><strong>25</strong></th>
<th style="text-align: left;"><strong>50</strong></th>
<th style="text-align: left;"><strong>Monte Carlo 2.5–97.5% quantiles at episode 50</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Correct expertise recognition</td>
<td style="text-align: left;">+0.046</td>
<td style="text-align: left;">-0.007</td>
<td style="text-align: left;">+0.020</td>
<td style="text-align: left;">-0.012</td>
<td style="text-align: left;">[-0.140; +0.107]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean credit assigned to partners</td>
<td style="text-align: left;">+0.545</td>
<td style="text-align: left;">+0.525</td>
<td style="text-align: left;">+0.529</td>
<td style="text-align: left;">+0.531</td>
<td style="text-align: left;">[+0.478; +0.591]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Weight assigned to more knowledgeable partners</td>
<td style="text-align: left;">+0.112</td>
<td style="text-align: left;">+0.149</td>
<td style="text-align: left;">+0.164</td>
<td style="text-align: left;">+0.163</td>
<td style="text-align: left;">[+0.122; +0.209]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Share of corrective opportunities used</td>
<td style="text-align: left;">+0.114</td>
<td style="text-align: left;">+0.149</td>
<td style="text-align: left;">+0.166</td>
<td style="text-align: left;">+0.161</td>
<td style="text-align: left;">[+0.121; +0.211]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Missed corrective opportunity rate</td>
<td style="text-align: left;">-0.114</td>
<td style="text-align: left;">-0.149</td>
<td style="text-align: left;">-0.166</td>
<td style="text-align: left;">-0.161</td>
<td style="text-align: left;">[-0.211; -0.121]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Epistemic credit misallocation</td>
<td style="text-align: left;">-0.162</td>
<td style="text-align: left;">-0.214</td>
<td style="text-align: left;">-0.237</td>
<td style="text-align: left;">-0.238</td>
<td style="text-align: left;">[-0.327; -0.147]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumulative acquisitions</td>
<td style="text-align: left;">+0.014</td>
<td style="text-align: left;">+0.213</td>
<td style="text-align: left;">+0.577</td>
<td style="text-align: left;">+1.257</td>
<td style="text-align: left;">[+0.612; +1.815]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weight assigned to less knowledgeable partners</td>
<td style="text-align: left;">+0.098</td>
<td style="text-align: left;">+0.089</td>
<td style="text-align: left;">+0.116</td>
<td style="text-align: left;">+0.133</td>
<td style="text-align: left;">[+0.090; +0.177]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumulative losses</td>
<td style="text-align: left;">+0.009</td>
<td style="text-align: left;">+0.116</td>
<td style="text-align: left;">+0.389</td>
<td style="text-align: left;">+0.841</td>
<td style="text-align: left;">[+0.551; +1.377]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative net balance</td>
<td style="text-align: left;">+0.005</td>
<td style="text-align: left;">+0.097</td>
<td style="text-align: left;">+0.188</td>
<td style="text-align: left;">+0.416</td>
<td style="text-align: left;">[-0.427; +1.131]</td>
</tr>
</tbody>
</table>
<p><img src="figures/image2.png" style="width:6.3in;height:3.68981in"></p>
<p>Figure 2. Effects of the simulated social regime at episode 50. Positive values indicate higher values under cooperation; negative values indicate lower values. Error bars represent the 2.5% and 97.5% quantiles across Monte Carlo replications, not confidence intervals for a human population.</p>
</section>
<section id="ablations-distinguish-influence-general-receptivity-and-differential-allocation" class="level3">
<h3 class="anchored" data-anchor-id="ablations-distinguish-influence-general-receptivity-and-differential-allocation">7.5. Ablations Distinguish Influence, General Receptivity, and Differential Allocation</h3>
<p>The first test preserves differences in credit while preventing that credit from changing partners’ actual influence: every partner receives a fixed weight of 0.5. At episode 50 of the debate scenario, cooperative credit remains higher (+0.544 in these ablation runs), but the advantage in corrective-opportunity use becomes exactly zero. The +1.257 acquisition advantage in the full model becomes -0.073 on average. In the coupled scenario, a small acquisition difference remains (+0.219), but the specific credit-to-weight channel is likewise neutralized. The intervention therefore establishes the internal necessity of the credit-to-influence link for the main social-learning advantage in debate.</p>
<p>A second ablation preserves each evaluator’s mean receptivity to others but assigns that same mean weight to all of their partners. It therefore removes differential allocation across sources without removing general social openness. At episode 50 of the debate scenario, the cooperative acquisition advantage remains +1.244, expertise-use efficiency remains +0.172, and the reduction in misallocation remains -0.263. Fine-grained differentiation among partners is therefore not necessary for the main mechanism: a large share of the cooperative effect comes from general receptivity to others’ contributions.</p>
<p>Finally, removing relational memory also leaves the main result largely intact: at episode 50 of the debate scenario, the cooperative advantage remains about +0.165 for corrective-opportunity use and +1.238 acquisitions in the five extension runs. With rotating partners, persistence of a specific dyadic relationship is therefore not necessary for the main mechanism. These ablations establish causal dependencies within the model; they are not independent causal evidence for the human participants.</p>
</section>
<section id="results-are-robust-to-several-scenario-changes" class="level3">
<h3 class="anchored" data-anchor-id="results-are-robust-to-several-scenario-changes">7.6. Results Are Robust to Several Scenario Changes</h3>
<p>The qualitative conclusions remain similar when all groups contain four agents or when partners remain fixed. They also retain the same direction when the strength of the credit-to-influence link is varied. Sensitivity to the benevolence contribution is particularly informative: even when this contribution is set to zero, the cooperative advantage in corrective-opportunity use and acquisitions remains; increasing it mainly strengthens the magnitude of receptivity. The rate at which new information enters the environment logically changes final knowledge stock and the size of the absolute SES-associated gap, without altering the general mechanism.</p>
<p>The main estimates change little between 20 and 30 replications. For example, the socioeconomic gap in knowledge stock at episode 50 changes from +5.009 to +4.946; the cooperative reduction in misallocation changes from -0.231 to -0.238; expertise-use efficiency from +0.156 to +0.161; and the credit advantage from +0.532 to +0.531. The central results are therefore stable between 20 and 30 replications in this version of the model.</p>
</section>
<section id="search-re-anchors-the-self-model" class="level3">
<h3 class="anchored" data-anchor-id="search-re-anchors-the-self-model">7.7. Search Re-Anchors the Self-Model</h3>
<p>In the renewed world, final knowledge stock in the search-then-debate scenario is almost identical to search alone: 85.601 versus 85.448 facts on average. Debate therefore does not add a second massive gain when document-based search is already strongly renewing knowledge. This proximity does not mean that debate has no effect; rather, it indicates that social acquisitions and losses largely offset each other at the level of final stock.</p>
<p>The coupling does, however, change metacognition. After fifty debates without search, the self-model difference between the cooperative and competitive regimes is -0.234. When each debate is preceded by search, this gap falls to -0.012. In the ABM, information acquired through document-based search therefore regularly re-anchors self-estimation and limits the divergence generated by the social context.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">8. Discussion</h2>
<section id="the-central-problem-is-converting-expertise-into-learning" class="level3">
<h3 class="anchored" data-anchor-id="the-central-problem-is-converting-expertise-into-learning">8.1. The Central Problem Is Converting Expertise into Learning</h3>
<p>MOVICI and the model converge on one point: the presence of a more knowledgeable person is not yet a learning resource. Their contribution must be encountered, receive enough credit, and that credit must be able to change how their information is used. This distinction is consistent with several findings from the learning and group literatures. Groups can fail to pool information that is already available (Stasser &amp; Titus, 1985). Conversely, shared experience can improve performance by facilitating recognition and use of members’ expertise (Littlepage et al., 1997), and perceptions of relative expertise shape what is learned and remembered in work relationships (Hollingshead, 2000).</p>
<p>The most instructive human result is the coexistence of two facts. On average, objective competence is poorly reflected in perceived competence; yet participants who direct their judgments more strongly toward partners who are actually more knowledgeable show greater progress. The simulation adds an important nuance: when the same agent is exposed to both formalized social regimes, the cooperative regime improves raw expertise recognition very little but strongly increases credit and receptivity toward others. It gives more weight to more knowledgeable partners, but also to less knowledgeable partners. The cooperative mechanism is therefore less an improvement in discrimination than a reduction in the risk of overlooking a potentially corrective contribution.</p>
<p>This result does not imply that all cooperative learning is weak. Meta-analyses find positive average effects of cooperative learning on achievement (Kyndt et al., 2013). But the factual benefits of argumentation are not automatic: Wecker and Fischer (2014) show that interventions can improve argumentation without producing an equally clear gain in domain knowledge. Here, greater receptivity produces more acquisitions but also more losses. The ablation of the credit-to-influence link clarifies the functional condition: a difference in credit does not produce the main cognitive advantage if it no longer changes the effective use of information.</p>
</section>
<section id="cumulative-inequalities-connections-with-economics-and-sociology" class="level3">
<h3 class="anchored" data-anchor-id="cumulative-inequalities-connections-with-economics-and-sociology">8.2. Cumulative Inequalities: Connections with Economics and Sociology</h3>
<p>The socioeconomic result has a familiar form in the literature on accumulation. A small initial or repeated advantage can itself become a resource for later gains. In the economics of skill formation, Cunha and Heckman (2007) describe self-productivity and dynamic complementarity: skills acquired at one stage can increase the returns to subsequent learning. Heckman and Mosso (2014) situate these mechanisms within inequalities in development and mobility. In our model, previously acquired knowledge slightly increases the probability of learning new facts and slightly decreases the probability of losing them, adding weak cognitive recursion to the repeated opportunity differential.</p>
<p>Sociology describes a related logic through cumulative advantage. Merton (1968) shows how advantages can reinforce themselves in scientific careers. DiPrete and Eirich (2006) generalize the mechanism to inequality production. In the learning sciences, Stanovich (1986) described a ‘Matthew effect’ in reading. The model directly reproduces none of these institutions and does not assume a closed information stock. It shows a minimal form of cumulative advantage in an expanding environment: a small SES-associated differential, repeated as new information becomes available, generates a growing absolute gap in knowledge stock. The density gap remains much smaller but does not disappear. When the SES coefficient is removed, both gradients become close to zero.</p>
<p>This dynamic is also consistent with research on digital inequalities. Differences in the benefits derived from technologies persist beyond material access and are associated with differences in skills, uses, and social resources (Hargittai, 2010; van Deursen &amp; van Dijk, 2011; Helsper, 2012; van Deursen &amp; Helsper, 2015; Scheerder et al., 2017; Robinson et al., 2015). The model provides one possible micro-dynamic: in an environment where the amount of accessible information itself continues to grow, small repeated differences in the chances of exploiting that information can sustain a modest relative differential while producing an increasingly large absolute knowledge gap.</p>
</section>
<section id="credibility-deficits-status-and-epistemic-injustice" class="level3">
<h3 class="anchored" data-anchor-id="credibility-deficits-status-and-epistemic-injustice">8.3. Credibility Deficits, Status, and Epistemic Injustice</h3>
<p>The model’s epistemic credit misallocation is not yet epistemic injustice. To speak of testimonial injustice in Fricker’s (2007) sense, one would need to show that a credibility deficit is linked to prejudice or to a relevant social relation. The current model does not directly introduce gender, race, disability, or a stigmatized status as a cause of credit. Moreover, its main index is directional: it measures the risk of underusing available corrective expertise. Over-crediting a less knowledgeable source is tracked separately as a calibration error or potential receptivity cost, not as an injustice suffered by the over-credited person.</p>
<p>The model nevertheless provides a mechanistic chain that can be connected to this literature. Goffman (1963) shows how stigma changes expectations and interactional treatment. He does not provide a theory of epistemic credibility, but his analysis helps explain how a socially discredited identity can shape the reception of a person even before their content is evaluated. Link and Phelan (2001) further emphasize the combination of labeling, stereotyping, separation, status loss, and discrimination under conditions of power.</p>
<p>Expectation states theories provide a more direct link to competence. Status characteristics can create performance expectations that subsequently organize participation and influence (Berger et al., 1972; Kalkhoff &amp; Thye, 2006; Ridgeway, 2014). Foschi (2000) likewise shows that different standards can be applied when attributing the same competence. Experiments holding qualifications constant document evaluation disparities related to motherhood (Correll et al., 2007) and gender in science (Moss-Racusin et al., 2012). Research on epistemic exclusion further shows that women faculty and faculty of color report greater devaluation of their scholarly contributions (Settles et al., 2022).</p>
<p>A future extension could therefore represent a structural credibility deficit simply: at equal objective competence, a given social status would repeatedly lower perceived competence or assigned credit. The existing chain predicts what may follow: less weight assigned to the source, more missed corrective opportunities, and eventually divergent learning trajectories. The present results also add another possibility: a more receptive regime can reduce the risk of under-crediting without necessarily improving calibration accuracy. Such a dynamic could limit some mechanisms of epistemic exclusion, but this extension remains to be tested and is not inferred from the current MOVICI data.</p>
</section>
<section id="cooperation-competition-and-the-strategic-value-of-others" class="level3">
<h3 class="anchored" data-anchor-id="cooperation-competition-and-the-strategic-value-of-others">8.4. Cooperation, Competition, and the Strategic Value of Others</h3>
<p>The difference between cooperation and competition is first consistent with research on interdependence, motivated information processing, and sociocognitive conflict. Social motivation shapes what group members seek and use as information (De Dreu et al., 2008). Performance goals favour regulation centred more on relative competence and self-assertion (Darnon et al., 2006; Sommet et al., 2014). A competitive or cooperative mindset also changes the effect of social comparison on self-evaluation (Colpaert et al., 2015). In the ABM, these differences are represented as changes in social evaluation and the self-model, never as a direct knowledge bonus.</p>
<p>Economics provides a more distant analogy. In tournament models, rewards depend on relative rank rather than absolute performance alone (Lazear &amp; Rosen, 1981). MOVICI is neither a labour market nor a monetary tournament. The analogy concerns only the following property: when success depends more strongly on relative position, information provided by others can change in strategic value. The results nevertheless suggest that the cooperative contrast is not reducible to better source ranking; it mainly affects willingness to let others’ contributions influence the agent.</p>
</section>
<section id="receptivity-calibration-and-epistemic-inclusion" class="level3">
<h3 class="anchored" data-anchor-id="receptivity-calibration-and-epistemic-inclusion">8.5. Receptivity, Calibration, and Epistemic Inclusion</h3>
<p>The central debate result leads us to distinguish three properties that are often conflated. Expertise recognition concerns the ability to identify who knows more. Credit calibration concerns the fit between objective competence and assigned credit in both directions: under-crediting and over-crediting. Epistemic inclusion, in the functional sense used here, refers more modestly to whether others’ contributions have a sufficient chance of being heard and of changing information processing. In the model, cooperation can improve this inclusion without improving raw recognition and while generating more over-crediting.</p>
<p>This trade-off is not necessarily irrational. A socially generous heuristic can be locally miscalibrated yet functionally effective in an environment where some partners possess corrective information. The ablation that preserves mean receptivity while removing differentiation across partners reinforces this interpretation: the main advantage in factual-knowledge acquisitions remains. Cooperation therefore mainly reduces the risk of failing to listen to available expertise; it guarantees neither perfect expert selection nor a net knowledge gain at every horizon.</p>
</section>
<section id="humanmachine-learning-and-trust-calibration" class="level3">
<h3 class="anchored" data-anchor-id="humanmachine-learning-and-trust-calibration">8.6. Human–Machine Learning and Trust Calibration</h3>
<p>MOVICI Web search is mediated primarily by a search engine that algorithmically ranks access to sources and only secondarily by generative artificial intelligence. The protocol therefore cannot be equated with systematic use of generative AI. Moreover, the connection with the present results mainly concerns metacognition. In MOVICI, factual gain and change in subjective knowledge are weakly associated. In addition, a larger share of time spent on search-engine results pages predicts higher subjective knowledge when factual knowledge is controlled. This exploratory association suggests that a cue of access or familiarity can feed the feeling of knowing without exactly tracking factual knowledge stock (Vayre et al., 2026a).</p>
<p>This result is consistent with Fisher et al.&nbsp;(2015), who show that online search can inflate estimates of internal knowledge, and with Sparrow et al.&nbsp;(2011), who show that information availability changes what is remembered. In the simulation, this mechanism is represented modestly: self-estimation depends on actual knowledge but also on a navigation cue. The coupling result is complementary: when search regularly precedes debate, divergence in self-estimation between the two social regimes becomes almost null. This is a result of the simulated scenario, not a demonstrated general property of all online search.</p>
<p>The literature on trust in automation (Lee &amp; See, 2004) and on algorithm aversion or appreciation (Dietvorst et al., 2015; Logg et al., 2019) therefore becomes relevant to a future extension in which an algorithmic source would itself be evaluated, credited, and weighted as a partner. It does not provide direct validation of the current Web-search scenario.</p>
<p>Table 12 summarises these connections. It does not present external studies as numerical validations of the model. The comparison concerns the form of mechanisms and regularities.</p>
<p>Table 12. Connections between Simulation Results and Research in Economics, Sociology, and the Learning Sciences</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 24%">
<col style="width: 28%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Simulation result</strong></th>
<th style="text-align: left;"><strong>Comparable research</strong></th>
<th style="text-align: left;"><strong>What is comparable</strong></th>
<th style="text-align: left;"><strong>Limit</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A small socioeconomic differential becomes cumulative in an expanding world</td>
<td style="text-align: left;">Cunha &amp; Heckman (2007); DiPrete &amp; Eirich (2006); digital-inequality literature</td>
<td style="text-align: left;">A repeated advantage can produce a growing absolute gap even when the relative gap remains more modest</td>
<td style="text-align: left;">The model is neither an economic human-capital production function nor a real longitudinal survey; world expansion is a theoretical assumption</td>
</tr>
<tr class="even">
<td style="text-align: left;">Objective competence and credit can diverge</td>
<td style="text-align: left;">Berger et al.&nbsp;(1972); Foschi (2000); Ridgeway (2014); Podolny (1993)</td>
<td style="text-align: left;">Status, reputation, or expectations can shape influence beyond objective quality</td>
<td style="text-align: left;">MOVICI does not directly manipulate these statuses</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A credit deficit can produce missed learning opportunities</td>
<td style="text-align: left;">Goffman (1963); Link &amp; Phelan (2001); Settles et al.&nbsp;(2022)</td>
<td style="text-align: left;">Social devaluation can durably alter the reception of a person and their contributions</td>
<td style="text-align: left;">The current model contains no stigmatized identity</td>
</tr>
<tr class="even">
<td style="text-align: left;">The cooperative regime mainly increases social receptivity</td>
<td style="text-align: left;">Johnson &amp; Johnson (2009); De Dreu et al.&nbsp;(2008); Darnon et al.&nbsp;(2006); Colpaert et al.&nbsp;(2015); Lazear &amp; Rosen (1981)</td>
<td style="text-align: left;">Goal structure can alter willingness to listen to and integrate others’ contributions without necessarily improving expert detection</td>
<td style="text-align: left;">MOVICI does not strictly randomize condition; the causal result concerns the simulated regime</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Credit has cognitive effects only if it changes effective influence</td>
<td style="text-align: left;">Stasser &amp; Titus (1985); Littlepage et al.&nbsp;(1997); Hollingshead (2000)</td>
<td style="text-align: left;">Available expertise improves performance only when it is recognized and actually mobilized</td>
<td style="text-align: left;">The necessity test is internal to the model; external studies support only the mechanism’s plausibility</td>
</tr>
<tr class="even">
<td style="text-align: left;">Search re-anchors self-estimation</td>
<td style="text-align: left;">Fisher et al.&nbsp;(2015); Sparrow et al.&nbsp;(2011); Lee &amp; See (2004)</td>
<td style="text-align: left;">Technical environments can change memory, the feeling of knowing, and dependence on external sources</td>
<td style="text-align: left;">The current scenario models Web search; it does not yet simulate generative AI as a partner</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Epistemic inclusion can improve without better calibration</td>
<td style="text-align: left;">Johnson &amp; Johnson (2009); De Dreu et al.&nbsp;(2008); literature on expertise use</td>
<td style="text-align: left;">Greater general receptivity can reduce missed corrective expertise while also increasing over-crediting</td>
<td style="text-align: left;">The model does not yet test a stigmatized status or testimonial injustice in the strong sense</td>
</tr>
</tbody>
</table>
</section>
<section id="what-the-model-can-explain" class="level3">
<h3 class="anchored" data-anchor-id="what-the-model-can-explain">8.7. What the Model Can Explain</h3>
<p>The value of the model lies not only in reproducing plausible curves, but especially in the ability to intervene on a mechanism and observe what disappears. Removing the credit-to-influence link shows that social credit cannot generate the main learning advantage in debate if it no longer changes uptake. Conversely, neutralizing differential allocation across partners while preserving mean receptivity leaves the effect largely intact: general receptivity is therefore sufficient for a large part of the mechanism. Removing the small socioeconomic effect, in turn, eliminates the cumulative gradient. These tests establish falsifiable dependencies within the model without being presented as independent causal validations in humans.</p>
<p>This logic follows the idea of generative explanation: specify explicit local rules, check their compatibility with relevant observations, and then study what they produce when repeated (Epstein, 1999; Windrum et al., 2007).</p>
</section>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">9. Limitations</h2>
<p>The model is built from a predominantly student sample and a single debate topic. Its parameters should not be interpreted as universal constants of human learning.</p>
<p>The cooperative versus competitive condition was not strictly randomised. Human differences between conditions should therefore remain described as observational associations. The same-agent counterfactual isolates the effect of changing social regime within the ABM, conditional on the formalized mechanisms; it does not retrospectively turn the experiment into a randomised trial.</p>
<p>The model strongly simplifies knowledge. A fact is either known or unknown. The semantic structure of arguments, emotions, rhetorical strategies, and the full distinction between private belief and public expression are not represented.</p>
<p>The renewed world is a theoretical experiment. Three new facts per episode correspond to no natural unit of time. Large values at episode 50 should be read as conditional consequences of repeated rules, not as forecasts of how many facts a student would actually learn. The stock/density comparison is precisely intended to distinguish absolute accumulation from the relative share of the world mastered.</p>
<p>Finally, the 30 Monte Carlo replications quantify the model’s internal stochasticity but do not propagate the full sampling uncertainty of coefficients estimated from the 96 participants. Sensitivity analyses in the RStudio package are deliberately targeted at a small number of modelling conventions or scenario parameters (world growth, the credit-to-weight scale, and the contribution of benevolence) in order to keep the package computationally tractable. Extensions are run for five replications per variant and should be read as qualitative mechanism checks rather than as a global analysis of parameter uncertainty.</p>
<p>Epistemic credit misallocation is not a direct measure of epistemic injustice. Testing such an extension would require explicitly manipulating or measuring social statuses, stereotypes, and their effects independently of objective competence. Likewise, over-crediting less knowledgeable partners is interpreted here as a calibration error or possible cost of receptivity, not as an injustice toward the over-credited person.</p>
</section>
<section id="data-code-and-reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="data-code-and-reproducibility">10. Data, Code, and Reproducibility</h2>
<p>The RStudio package, scripts, frozen parameters, minimally necessary pseudonymized data, ODD/ODD+D description, variable and output dictionaries, automated tests, and scripts reproducing the results are prepared for OSF deposit. The package distinguishes a FAST mode for technical verification from a STANDARD mode for publication results. The permanent link and DOI will be added in the submitted version. The archived version number provides traceability across code, results, and manuscript.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">11. Conclusion</h2>
<p>The model starts from a simple idea: having knowledge around oneself is not yet learning. Several steps lie between available expertise and changes in one’s own knowledge: encountering information, recognizing the source, assigning it credit, giving it weight, and integrating what it contributes.</p>
<p>Information search produces knowledge directly. In a renewed world, a small differential associated with socioeconomic resources repeats and generates cumulative advantage: the absolute stock gap grows strongly while the density gap remains much smaller. Debate produces far less net learning in the short term but changes how information from others is used. In the counterfactual simulations, the cooperative regime barely improves raw detection of who knows more. It mainly increases receptivity to partners in general: more weight is assigned to more knowledgeable partners, but also to less knowledgeable partners. This openness reduces missed corrective opportunities and increases acquisitions, while also increasing some losses; its advantage for net knowledge stock therefore remains more variable.</p>
<p>These results connect two forms of embeddedness. Structural conditions distribute opportunities to learn in an information environment that may continue to expand. Interactional situations locally determine how strongly others’ contributions can weigh on knowledge revision. States produced in one episode become the starting point for the next. The model thus shows that greater epistemic inclusion can emerge without an equivalent improvement in calibration accuracy, and that small structural or interactional differences can become trajectories when repeated.</p>
</section>
<section id="appendix-a.-correspondence-with-code-and-replication-parameters" class="level2">
<h2 class="anchored" data-anchor-id="appendix-a.-correspondence-with-code-and-replication-parameters">Appendix A. Correspondence with Code and Replication Parameters</h2>
<p>This appendix lists the technical names required for replication. They are omitted from the main text to preserve readability.</p>
<p>Table A1. Readable Article Labels and Names Used in the Files</p>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Concept in the article</strong></th>
<th style="text-align: left;"><strong>Name in the code</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Knowledge stock</td>
<td style="text-align: left;">KnowledgeStock</td>
</tr>
<tr class="even">
<td style="text-align: left;">Share of the information environment mastered</td>
<td style="text-align: left;">KnowledgeDensity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Self-estimated competence</td>
<td style="text-align: left;">SelfCredit_z</td>
</tr>
<tr class="even">
<td style="text-align: left;">Recognized partner expertise</td>
<td style="text-align: left;">RecognizedExpertise</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Perceived benevolence</td>
<td style="text-align: left;">BenevolenceSignal</td>
</tr>
<tr class="even">
<td style="text-align: left;">Credit assigned to partner</td>
<td style="text-align: left;">OtherCredit</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Effective partner weight</td>
<td style="text-align: left;">PartnerWeight</td>
</tr>
<tr class="even">
<td style="text-align: left;">Share of corrective opportunities used</td>
<td style="text-align: left;">ExpertUseEfficiency</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Missed corrective opportunity rate</td>
<td style="text-align: left;">MissedCorrectiveOpportunityRate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Epistemic credit misallocation</td>
<td style="text-align: left;">EpistemicCreditMisallocationIndex</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Human functional expertise-allocation index</td>
<td style="text-align: left;">ExpertiseAllocationGain</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weight assigned to less knowledgeable partners</td>
<td style="text-align: left;">WeightLessExpert</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rate of overweighting less knowledgeable partners</td>
<td style="text-align: left;">OverweightLessExpertRate</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative acquisitions</td>
<td style="text-align: left;">CumulativeLearningAcquisitions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumulative losses</td>
<td style="text-align: left;">CumulativeLearningLosses</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cumulative net balance</td>
<td style="text-align: left;">CumulativeLearningBalance</td>
</tr>
</tbody>
</table>
<p>Table A2. Selected Central Parameters. The OSF Configuration File Contains the Full List.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 16%">
<col style="width: 49%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Parameter</strong></th>
<th style="text-align: left;"><strong>Value</strong></th>
<th style="text-align: left;"><strong>Role</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Socioeconomic effect per search transition</td>
<td style="text-align: left;">0.1357</td>
<td style="text-align: left;">Small repeated learning differential</td>
</tr>
<tr class="even">
<td style="text-align: left;">Effect of fact ease</td>
<td style="text-align: left;">0.9881</td>
<td style="text-align: left;">Easier facts are easier to acquire</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Effect of information vigilance</td>
<td style="text-align: left;">0.1400</td>
<td style="text-align: left;">Contribution of the information-weighting state</td>
</tr>
<tr class="even">
<td style="text-align: left;">Persistence of self-estimation</td>
<td style="text-align: left;">0.7446</td>
<td style="text-align: left;">Inertia of the self-model across debates</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Knowledge re-anchoring under cooperation</td>
<td style="text-align: left;">0.1295</td>
<td style="text-align: left;">Additional link between knowledge and self-evaluation under cooperation</td>
</tr>
<tr class="even">
<td style="text-align: left;">Contribution of benevolence to credit</td>
<td style="text-align: left;">0.1690</td>
<td style="text-align: left;">Relational component of credit assigned to others</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Credit → weight scale</td>
<td style="text-align: left;">1.0000</td>
<td style="text-align: left;">Strength of the transformation from relative credit to influence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Longitudinal search exposure budget</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">Same exposure capacity in FIXED and RENEWED from episode 2 onward</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Probability that a search encounter is reliable</td>
<td style="text-align: left;">0.80</td>
<td style="text-align: left;">Scenario assumption for episodes 2–50</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sensitivity of benevolence contribution</td>
<td style="text-align: left;">0; 0.169; 0.338</td>
<td style="text-align: left;">Targeted robustness test of the social mechanism</td>
</tr>
</tbody>
</table>
</section>
<div id="movici-references">
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Ames, C. (1992). Classrooms: Goals, structures, and student motivation. Journal of Educational Psychology, 84(3), 261–271. <a href="https://doi.org/10.1037/0022-0663.84.3.261">https://doi.org/10.1037/0022-0663.84.3.261</a></p>
<p>Anderson, C., &amp; Kilduff, G. J. (2009). Why do dominant personalities attain influence in face-to-face groups? The competence-signaling effects of trait dominance. Journal of Personality and Social Psychology, 96(2), 491–503. <a href="https://doi.org/10.1037/a0014201">https://doi.org/10.1037/a0014201</a></p>
<p>Arcila-Valenzuela, M., &amp; Páez, A. (2024). Testimonial injustice: The facts of the matter. Review of Philosophy and Psychology, 15, 585–602. <a href="https://doi.org/10.1007/s13164-022-00662-w">https://doi.org/10.1007/s13164-022-00662-w</a></p>
<p>Banisch, S., &amp; Shamon, H. (2024). Validating argument-based opinion dynamics with survey experiments. Journal of Artificial Societies and Social Simulation, 27(1), 17. <a href="https://doi.org/10.18564/jasss.5305">https://doi.org/10.18564/jasss.5305</a></p>
<p>Berger, J., Cohen, B. P., &amp; Zelditch, M., Jr.&nbsp;(1972). Status characteristics and social interaction. American Sociological Review, 37(3), 241–255. <a href="https://doi.org/10.2307/2093465">https://doi.org/10.2307/2093465</a></p>
<p>Butler, G., Pigozzi, G., &amp; Rouchier, J. (2019). Mixing dyadic and deliberative opinion dynamics in an agent-based model of group decision-making. Complexity, 2019, 3758159. <a href="https://doi.org/10.1155/2019/3758159">https://doi.org/10.1155/2019/3758159</a></p>
<p>Butler, G., Pigozzi, G., &amp; Rouchier, J. (2020). An opinion diffusion model with vigilant agents and deliberation. In Multi-Agent-Based Simulation XX (pp.&nbsp;81–99). Springer. <a href="https://doi.org/10.1007/978-3-030-60843-9_7">https://doi.org/10.1007/978-3-030-60843-9_7</a></p>
<p>Cheng, J. T., Tracy, J. L., Foulsham, T., Kingstone, A., &amp; Henrich, J. (2013). Two ways to the top: Evidence that dominance and prestige are distinct yet viable avenues to social rank and influence. Journal of Personality and Social Psychology, 104(1), 103–125. <a href="https://doi.org/10.1037/a0030398">https://doi.org/10.1037/a0030398</a></p>
<p>Colpaert, L., Muller, D., Fayant, M.-P., &amp; Butera, F. (2015). A mindset of competition versus cooperation moderates the impact of social comparison on self-evaluation. Frontiers in Psychology, 6, 1337. <a href="https://doi.org/10.3389/fpsyg.2015.01337">https://doi.org/10.3389/fpsyg.2015.01337</a></p>
<p>Correll, S. J., Benard, S., &amp; Paik, I. (2007). Getting a job: Is there a motherhood penalty? American Journal of Sociology, 112(5), 1297–1338. <a href="https://doi.org/10.1086/511799">https://doi.org/10.1086/511799</a></p>
<p>Cunha, F., &amp; Heckman, J. (2007). The technology of skill formation. American Economic Review, 97(2), 31–47. <a href="https://doi.org/10.1257/aer.97.2.31">https://doi.org/10.1257/aer.97.2.31</a></p>
<p>De Dreu, C. K. W., Nijstad, B. A., &amp; van Knippenberg, D. (2008). Motivated information processing in group judgment and decision making. Personality and Social Psychology Review, 12(1), 22–49. <a href="https://doi.org/10.1177/1088868307304092">https://doi.org/10.1177/1088868307304092</a></p>
<p>Darnon, C., Muller, D., Schrager, S. M., Pannuzzo, N., &amp; Butera, F. (2006). Mastery and performance goals predict epistemic and relational conflict regulation. Journal of Educational Psychology, 98(4), 766–776. <a href="https://doi.org/10.1037/0022-0663.98.4.766">https://doi.org/10.1037/0022-0663.98.4.766</a></p>
<p>Dietvorst, B. J., Simmons, J. P., &amp; Massey, C. (2015). Algorithm aversion: People erroneously avoid algorithms after seeing them err. Journal of Experimental Psychology: General, 144(1), 114–126. <a href="https://doi.org/10.1037/xge0000033">https://doi.org/10.1037/xge0000033</a></p>
<p>DiPrete, T. A., &amp; Eirich, G. M. (2006). Cumulative advantage as a mechanism for inequality: A review of theoretical and empirical developments. Annual Review of Sociology, 32, 271–297. <a href="https://doi.org/10.1146/annurev.soc.32.061604.123127">https://doi.org/10.1146/annurev.soc.32.061604.123127</a></p>
<p>Dweck, C. S., &amp; Leggett, E. L. (1988). A social-cognitive approach to motivation and personality. Psychological Review, 95(2), 256–273. <a href="https://doi.org/10.1037/0033-295X.95.2.256">https://doi.org/10.1037/0033-295X.95.2.256</a></p>
<p>Elliot, A. J., &amp; McGregor, H. A. (2001). A 2 × 2 achievement goal framework. Journal of Personality and Social Psychology, 80(3), 501–519. <a href="https://doi.org/10.1037/0022-3514.80.3.501">https://doi.org/10.1037/0022-3514.80.3.501</a></p>
<p>Epstein, J. M. (1999). Agent-based computational models and generative social science. Complexity, 4(5), 41–60. <a href="https://doi.org/10.1002/(SICI)">https://doi.org/10.1002/(SICI</a>1099-0526(199905/06)4:5&lt;41::AID-CPLX9&gt;3.0.CO;2-F</p>
<p>Fisher, M., Goddu, M. K., &amp; Keil, F. C. (2015). Searching for explanations: How the Internet inflates estimates of internal knowledge. Journal of Experimental Psychology: General, 144(3), 674–687. <a href="https://doi.org/10.1037/xge0000070">https://doi.org/10.1037/xge0000070</a></p>
<p>Foschi, M. (2000). Double standards for competence: Theory and research. Annual Review of Sociology, 26, 21–42. <a href="https://doi.org/10.1146/annurev.soc.26.1.21">https://doi.org/10.1146/annurev.soc.26.1.21</a></p>
<p>Fricker, M. (2007). Epistemic injustice: Power and the ethics of knowing. Oxford University Press.</p>
<p>Goffman, E. (1963). Stigma: Notes on the management of spoiled identity. Prentice-Hall.</p>
<p>Granovetter, M. (1985). Economic action and social structure: The problem of embeddedness. American Journal of Sociology, 91(3), 481–510. <a href="https://doi.org/10.1086/228311">https://doi.org/10.1086/228311</a></p>
<p>Grimm, V., Railsback, S. F., Vincenot, C. E., et al.&nbsp;(2020). The ODD protocol for describing agent-based and other simulation models: A second update to improve clarity, replication, and structural realism. Journal of Artificial Societies and Social Simulation, 23(2), 7. <a href="https://doi.org/10.18564/jasss.4259">https://doi.org/10.18564/jasss.4259</a></p>
<p>Hargittai, E. (2010). Digital na(t)ives? Variation in Internet skills and uses among members of the ‘Net Generation’. Sociological Inquiry, 80(1), 92–113. <a href="https://doi.org/10.1111/j.1475-682X.2009.00317.x">https://doi.org/10.1111/j.1475-682X.2009.00317.x</a></p>
<p>Helsper, E. J. (2012). A corresponding fields model for the links between social and digital exclusion. Communication Theory, 22(4), 403–426. <a href="https://doi.org/10.1111/j.1468-2885.2012.01416.x">https://doi.org/10.1111/j.1468-2885.2012.01416.x</a></p>
<p>Heckman, J. J., &amp; Mosso, S. (2014). The economics of human development and social mobility. Annual Review of Economics, 6, 689–733. <a href="https://doi.org/10.1146/annurev-economics-080213-040753">https://doi.org/10.1146/annurev-economics-080213-040753</a></p>
<p>Hinsz, V. B., Tindale, R. S., &amp; Vollrath, D. A. (1997). The emerging conceptualization of groups as information processors. Psychological Bulletin, 121(1), 43–64. <a href="https://doi.org/10.1037/0033-2909.121.1.43">https://doi.org/10.1037/0033-2909.121.1.43</a></p>
<p>Hollingshead, A. B. (2000). Perceptions of expertise and transactive memory in work relationships. Group Processes &amp; Intergroup Relations, 3(3), 257–267. <a href="https://doi.org/10.1177/1368430200033002">https://doi.org/10.1177/1368430200033002</a></p>
<p>Hutchins, E. (1995). Cognition in the wild. MIT Press.</p>
<p>Johnson, D. W., &amp; Johnson, R. T. (2009). An educational psychology success story: Social interdependence theory and cooperative learning. Educational Researcher, 38(5), 365–379. <a href="https://doi.org/10.3102/0013189X09339057">https://doi.org/10.3102/0013189X09339057</a></p>
<p>Kalkhoff, W., &amp; Thye, S. R. (2006). Expectation states theory and research: New observations from meta-analysis. Sociological Methods &amp; Research, 35(2), 219–249. <a href="https://doi.org/10.1177/0049124106290311">https://doi.org/10.1177/0049124106290311</a></p>
<p>Koriat, A. (1997). Monitoring one’s own knowledge during study: A cue-utilization approach to judgments of learning. Journal of Experimental Psychology: General, 126(4), 349–370. <a href="https://doi.org/10.1037/0096-3445.126.4.349">https://doi.org/10.1037/0096-3445.126.4.349</a></p>
<p>Kyndt, E., Raes, E., Lismont, B., Timmers, F., Cascallar, E., &amp; Dochy, F. (2013). A meta-analysis of the effects of face-to-face cooperative learning. Educational Research Review, 10, 133–149. <a href="https://doi.org/10.1016/j.edurev.2013.02.002">https://doi.org/10.1016/j.edurev.2013.02.002</a></p>
<p>Laskowski, P. P., Puga-Gonzalez, I., Shults, F. L., &amp; Talmont-Kaminski, K. (2023). A cognitive model of epistemic vigilance in situations of varying competence, consistency, and utility. In F. Squazzoni (Ed.), Advances in Social Simulation (pp.&nbsp;13–21). Springer. <a href="https://doi.org/10.1007/978-3-031-34920-1_2">https://doi.org/10.1007/978-3-031-34920-1_2</a></p>
<p>Lazear, E. P., &amp; Rosen, S. (1981). Rank-order tournaments as optimum labor contracts. Journal of Political Economy, 89(5), 841–864. <a href="https://doi.org/10.1086/261010">https://doi.org/10.1086/261010</a></p>
<p>Lee, J. D., &amp; See, K. A. (2004). Trust in automation: Designing for appropriate reliance. Human Factors, 46(1), 50–80. <a href="https://doi.org/10.1518/hfes.46.1.50_30392">https://doi.org/10.1518/hfes.46.1.50_30392</a></p>
<p>Link, B. G., &amp; Phelan, J. C. (2001). Conceptualizing stigma. Annual Review of Sociology, 27, 363–385. <a href="https://doi.org/10.1146/annurev.soc.27.1.363">https://doi.org/10.1146/annurev.soc.27.1.363</a></p>
<p>Littlepage, G. E., Robison, W. B., &amp; Reddington, K. (1997). Effects of task experience and group experience on group performance, member ability, and recognition of expertise. Organizational Behavior and Human Decision Processes, 69(2), 133–147. <a href="https://doi.org/10.1006/obhd.1997.2677">https://doi.org/10.1006/obhd.1997.2677</a></p>
<p>Logg, J. M., Minson, J. A., &amp; Moore, D. A. (2019). Algorithm appreciation: People prefer algorithmic to human judgment. Organizational Behavior and Human Decision Processes, 151, 90–103. <a href="https://doi.org/10.1016/j.obhdp.2018.12.005">https://doi.org/10.1016/j.obhdp.2018.12.005</a></p>
<p>Mercier, H. (2016). The argumentative theory: Predictions and empirical evidence. Trends in Cognitive Sciences, 20(9), 689–700. <a href="https://doi.org/10.1016/j.tics.2016.07.001">https://doi.org/10.1016/j.tics.2016.07.001</a></p>
<p>Mercier, H., &amp; Sperber, D. (2011). Why do humans reason? Arguments for an argumentative theory. Behavioral and Brain Sciences, 34(2), 57–74. <a href="https://doi.org/10.1017/S0140525X10000968">https://doi.org/10.1017/S0140525X10000968</a></p>
<p>Merton, R. K. (1968). The Matthew effect in science. Science, 159(3810), 56–63. <a href="https://doi.org/10.1126/science.159.3810.56">https://doi.org/10.1126/science.159.3810.56</a></p>
<p>Nelson, T. O., &amp; Narens, L. (1990). Metamemory: A theoretical framework and new findings. In G. H. Bower (Ed.), The psychology of learning and motivation (Vol. 26, pp.&nbsp;125–173). Academic Press. <a href="https://doi.org/10.1016/S0079-7421(08)">https://doi.org/10.1016/S0079-7421(08</a>60053-5</p>
<p>Moss-Racusin, C. A., Dovidio, J. F., Brescoll, V. L., Graham, M. J., &amp; Handelsman, J. (2012). Science faculty’s subtle gender biases favor male students. Proceedings of the National Academy of Sciences, 109(41), 16474–16479. <a href="https://doi.org/10.1073/pnas.1211286109">https://doi.org/10.1073/pnas.1211286109</a></p>
<p>Podolny, J. M. (1993). A status-based model of market competition. American Journal of Sociology, 98(4), 829–872. <a href="https://doi.org/10.1086/230091">https://doi.org/10.1086/230091</a></p>
<p>Price, P. C., &amp; Stone, E. R. (2004). Intuitive evaluation of likelihood judgment producers: Evidence for a confidence heuristic. Journal of Behavioral Decision Making, 17(1), 39–57. <a href="https://doi.org/10.1002/bdm.460">https://doi.org/10.1002/bdm.460</a></p>
<p>Reisinger, D., Kogler, M. L., &amp; Jäger, G. (2023). On the interplay of gullibility, plausibility, and criticism: A computational model of epistemic vigilance. Journal of Artificial Societies and Social Simulation, 26(3), 8. <a href="https://doi.org/10.18564/jasss.5136">https://doi.org/10.18564/jasss.5136</a></p>
<p>Ridgeway, C. L. (2014). Why status matters for inequality. American Sociological Review, 79(1), 1–16. <a href="https://doi.org/10.1177/0003122413515997">https://doi.org/10.1177/0003122413515997</a></p>
<p>Robinson, L., Cotten, S. R., Ono, H., et al.&nbsp;(2015). Digital inequalities and why they matter. Information, Communication &amp; Society, 18(5), 569–582. <a href="https://doi.org/10.1080/1369118X.2015.1012532">https://doi.org/10.1080/1369118X.2015.1012532</a></p>
<p>Rybnik, M., Puga-Gonzalez, I., Shults, F. L., Dąbrowska-Prokopowska, E., &amp; Talmont-Kaminski, K. (2023). An agent-based model of the role of epistemic vigilance in human cooperation. In F. Squazzoni (Ed.), Advances in Social Simulation (pp.&nbsp;75–86). Springer. <a href="https://doi.org/10.1007/978-3-031-34920-1_7">https://doi.org/10.1007/978-3-031-34920-1_7</a></p>
<p>Scheerder, A., van Deursen, A. J. A. M., &amp; van Dijk, J. A. G. M. (2017). Determinants of Internet skills, uses and outcomes: A systematic review of the second- and third-level digital divide. Telematics and Informatics, 34(8), 1607–1624. <a href="https://doi.org/10.1016/j.tele.2017.07.007">https://doi.org/10.1016/j.tele.2017.07.007</a></p>
<p>Settles, I. H., Jones, M. K., Buchanan, N. T., &amp; Brassel, S. T. (2022). Epistemic exclusion of women faculty and faculty of color: Understanding scholar(ly) devaluation as a predictor of turnover intentions. Journal of Higher Education, 93(1), 31–55. <a href="https://doi.org/10.1080/00221546.2021.1914494">https://doi.org/10.1080/00221546.2021.1914494</a></p>
<p>Sommet, N., Darnon, C., Mugny, G., Quiamzade, A., Pulfrey, C., Dompnier, B., &amp; Butera, F. (2014). Performance goals in conflictual social interactions: Towards the distinction between two modes of relational conflict regulation. British Journal of Social Psychology, 53(1), 134–153. <a href="https://doi.org/10.1111/bjso.12015">https://doi.org/10.1111/bjso.12015</a></p>
<p>Sparrow, B., Liu, J., &amp; Wegner, D. M. (2011). Google effects on memory: Cognitive consequences of having information at our fingertips. Science, 333(6043), 776–778. <a href="https://doi.org/10.1126/science.1207745">https://doi.org/10.1126/science.1207745</a></p>
<p>Sperber, D., Clément, F., Heintz, C., Mascaro, O., Mercier, H., Origgi, G., &amp; Wilson, D. (2010). Epistemic vigilance. Mind &amp; Language, 25(4), 359–393. <a href="https://doi.org/10.1111/j.1468-0017.2010.01394.x">https://doi.org/10.1111/j.1468-0017.2010.01394.x</a></p>
<p>Stanovich, K. E. (1986). Matthew effects in reading: Some consequences of individual differences in the acquisition of literacy. Reading Research Quarterly, 21(4), 360–407. <a href="https://doi.org/10.1598/RRQ.21.4.1">https://doi.org/10.1598/RRQ.21.4.1</a></p>
<p>Stasser, G., &amp; Titus, W. (1985). Pooling of unshared information in group decision making: Biased information sampling during discussion. Journal of Personality and Social Psychology, 48(6), 1467–1478. <a href="https://doi.org/10.1037/0022-3514.48.6.1467">https://doi.org/10.1037/0022-3514.48.6.1467</a></p>
<p>Stefanelli, A., &amp; Seidl, R. (2017). Opinion communication on contested topics: How empirics and arguments can improve social simulation. Journal of Artificial Societies and Social Simulation, 20(4), 3. <a href="https://doi.org/10.18564/jasss.3492">https://doi.org/10.18564/jasss.3492</a></p>
<p>Thiele, J. C., Kurth, W., &amp; Grimm, V. (2014). Facilitating parameter estimation and sensitivity analysis of agent-based models: A cookbook using NetLogo and R. Journal of Artificial Societies and Social Simulation, 17(3), 11. <a href="https://doi.org/10.18564/jasss.2503">https://doi.org/10.18564/jasss.2503</a></p>
<p>van Deursen, A. J. A. M., &amp; Helsper, E. J. (2015). The third-level digital divide: Who benefits most from being online? In L. Robinson et al.&nbsp;(Eds.), Communication and Information Technologies Annual: Digital Distinctions and Inequalities (Vol. 10, pp.&nbsp;29–52). Emerald. <a href="https://doi.org/10.1108/S2050-206020150000010002">https://doi.org/10.1108/S2050-206020150000010002</a></p>
<p>van Deursen, A. J. A. M., &amp; van Dijk, J. A. G. M. (2011). Internet skills and the digital divide. New Media &amp; Society, 13(6), 893–911. <a href="https://doi.org/10.1177/1461444810386774">https://doi.org/10.1177/1461444810386774</a></p>
<p>Wecker, C., &amp; Fischer, F. (2014). Where is the evidence? A meta-analysis on the role of argumentation for the acquisition of domain-specific knowledge in computer-supported collaborative learning. Computers &amp; Education, 75, 218–228. <a href="https://doi.org/10.1016/j.compedu.2014.02.016">https://doi.org/10.1016/j.compedu.2014.02.016</a></p>
<p>Windrum, P., Fagiolo, G., &amp; Moneta, A. (2007). Empirical validation of agent-based models: Alternatives and prospects. Journal of Artificial Societies and Social Simulation, 10(2), 8. https://www.jasss.org/10/2/8.html</p>
<p>Vayre, J.-S., et al.&nbsp;(2026a). Prior Knowledge and Learning from Open Web Search. MOVICI preprint, final deposit version. Authors and repository identifier to be confirmed.</p>
<p>Vayre, J.-S., et al.&nbsp;(2026b). Epistemic Credit in Cooperative and Competitive Debate. MOVICI preprint, final deposit version. Authors and repository identifier to be confirmed.</p>
<p>Vayre, J.-S., et al.&nbsp;(2026c). Learning from Documents and from Others: Knowledge Change and Epistemic Coordination. MOVICI Article 3 preprint, final deposit version. Authors and repository identifier to be confirmed.</p>
<p>Vayre, J.-S., et al.&nbsp;(2026d). CAVL: A Cognitive Architecture for Vigilant Learning. Preprint, final deposit version. Authors and repository identifier to be confirmed.</p>
</section>
</div>
<script>
window.MOVICI_REFERENCES = [{"id": "ref-1", "full": "Ames, C. (1992). Classrooms: Goals, structures, and student motivation. Journal of Educational Psychology, 84(3), 261--271. https://doi.org/10.1037/0022-0663.84.3.261", "doi": "https://doi.org/10.1037/0022-0663.84.3.261", "aliases": ["Ames et al. (1992)", "Ames et al., 1992", "Ames (1992)", "Ames, 1992"]}, {"id": "ref-2", "full": "Anderson, C., & Kilduff, G. J. (2009). Why do dominant personalities attain influence in face-to-face groups? The competence-signaling effects of trait dominance. Journal of Personality and Social Psychology, 96(2), 491--503. https://doi.org/10.1037/a0014201", "doi": "https://doi.org/10.1037/a0014201", "aliases": ["Anderson and Kilduff (2009)", "Anderson and Kilduff, 2009", "Anderson & Kilduff (2009)", "Anderson & Kilduff, 2009", "Anderson et al. (2009)", "Anderson et al., 2009", "Anderson (2009)", "Anderson, 2009"]}, {"id": "ref-3", "full": "Arcila-Valenzuela, M., & Páez, A. (2024). Testimonial injustice: The facts of the matter. Review of Philosophy and Psychology, 15, 585--602. https://doi.org/10.1007/s13164-022-00662-w", "doi": "https://doi.org/10.1007/s13164-022-00662-w", "aliases": ["Arcila-Valenzuela and Páez (2024)", "Arcila-Valenzuela and Páez, 2024", "Arcila-Valenzuela et al. (2024)", "Arcila-Valenzuela & Páez (2024)", "Arcila-Valenzuela & Páez, 2024", "Arcila-Valenzuela et al., 2024", "Arcila-Valenzuela (2024)", "Arcila-Valenzuela, 2024"]}, {"id": "ref-4", "full": "Banisch, S., & Shamon, H. (2024). Validating argument-based opinion dynamics with survey experiments. Journal of Artificial Societies and Social Simulation, 27(1), 17. https://doi.org/10.18564/jasss.5305", "doi": "https://doi.org/10.18564/jasss.5305", "aliases": ["Banisch and Shamon (2024)", "Banisch and Shamon, 2024", "Banisch & Shamon (2024)", "Banisch & Shamon, 2024", "Banisch et al. (2024)", "Banisch et al., 2024", "Banisch (2024)", "Banisch, 2024"]}, {"id": "ref-5", "full": "Berger, J., Cohen, B. P., & Zelditch, M., Jr. (1972). Status characteristics and social interaction. American Sociological Review, 37(3), 241--255. https://doi.org/10.2307/2093465", "doi": "https://doi.org/10.2307/2093465", "aliases": ["Berger and Zelditch (1972)", "Berger and Zelditch, 1972", "Berger & Zelditch (1972)", "Berger & Zelditch, 1972", "Berger et al. (1972)", "Berger et al., 1972", "Berger (1972)", "Berger, 1972"]}, {"id": "ref-6", "full": "Butler, G., Pigozzi, G., & Rouchier, J. (2019). Mixing dyadic and deliberative opinion dynamics in an agent-based model of group decision-making. Complexity, 2019, 3758159. https://doi.org/10.1155/2019/3758159", "doi": "https://doi.org/10.1155/2019/3758159", "aliases": ["Butler and Rouchier (2019)", "Butler and Rouchier, 2019", "Butler & Rouchier (2019)", "Butler & Rouchier, 2019", "Butler et al. (2019)", "Butler et al., 2019", "Butler (2019)", "Butler, 2019"]}, {"id": "ref-7", "full": "Butler, G., Pigozzi, G., & Rouchier, J. (2020). An opinion diffusion model with vigilant agents and deliberation. In Multi-Agent-Based Simulation XX (pp. 81--99). Springer. https://doi.org/10.1007/978-3-030-60843-97", "doi": "https://doi.org/10.1007/978-3-030-60843-97", "aliases": ["Butler and Rouchier (2020)", "Butler and Rouchier, 2020", "Butler & Rouchier (2020)", "Butler & Rouchier, 2020", "Butler et al. (2020)", "Butler et al., 2020", "Butler (2020)", "Butler, 2020"]}, {"id": "ref-8", "full": "Cheng, J. T., Tracy, J. L., Foulsham, T., Kingstone, A., & Henrich, J. (2013). Two ways to the top: Evidence that dominance and prestige are distinct yet viable avenues to social rank and influence. Journal of Personality and Social Psychology, 104(1), 103--125. https://doi.org/10.1037/a0030398", "doi": "https://doi.org/10.1037/a0030398", "aliases": ["Cheng and Henrich (2013)", "Cheng and Henrich, 2013", "Cheng & Henrich (2013)", "Cheng & Henrich, 2013", "Cheng et al. (2013)", "Cheng et al., 2013", "Cheng (2013)", "Cheng, 2013"]}, {"id": "ref-9", "full": "Colpaert, L., Muller, D., Fayant, M.-P., & Butera, F. (2015). A mindset of competition versus cooperation moderates the impact of social comparison on self-evaluation. Frontiers in Psychology, 6, 1337. https://doi.org/10.3389/fpsyg.2015.01337", "doi": "https://doi.org/10.3389/fpsyg.2015.01337", "aliases": ["Colpaert and Butera (2015)", "Colpaert and Butera, 2015", "Colpaert & Butera (2015)", "Colpaert & Butera, 2015", "Colpaert et al. (2015)", "Colpaert et al., 2015", "Colpaert (2015)", "Colpaert, 2015"]}, {"id": "ref-10", "full": "Correll, S. J., Benard, S., & Paik, I. (2007). Getting a job: Is there a motherhood penalty? American Journal of Sociology, 112(5), 1297--1338. https://doi.org/10.1086/511799", "doi": "https://doi.org/10.1086/511799", "aliases": ["Correll and Paik (2007)", "Correll and Paik, 2007", "Correll & Paik (2007)", "Correll et al. (2007)", "Correll et al., 2007", "Correll & Paik, 2007", "Correll (2007)", "Correll, 2007"]}, {"id": "ref-11", "full": "Cunha, F., & Heckman, J. (2007). The technology of skill formation. American Economic Review, 97(2), 31--47. https://doi.org/10.1257/aer.97.2.31", "doi": "https://doi.org/10.1257/aer.97.2.31", "aliases": ["Cunha and Heckman (2007)", "Cunha and Heckman, 2007", "Cunha & Heckman (2007)", "Cunha & Heckman, 2007", "Cunha et al. (2007)", "Cunha et al., 2007", "Cunha (2007)", "Cunha, 2007"]}, {"id": "ref-12", "full": "De Dreu, C. K. W., Nijstad, B. A., & van Knippenberg, D. (2008). Motivated information processing in group judgment and decision making. Personality and Social Psychology Review, 12(1), 22--49. https://doi.org/10.1177/1088868307304092", "doi": "https://doi.org/10.1177/1088868307304092", "aliases": ["De Dreu and van Knippenberg (2008)", "De Dreu and van Knippenberg, 2008", "De Dreu & van Knippenberg (2008)", "De Dreu & van Knippenberg, 2008", "De Dreu et al. (2008)", "De Dreu et al., 2008", "De Dreu (2008)", "De Dreu, 2008"]}, {"id": "ref-13", "full": "Darnon, C., Muller, D., Schrager, S. M., Pannuzzo, N., & Butera, F. (2006). Mastery and performance goals predict epistemic and relational conflict regulation. Journal of Educational Psychology, 98(4), 766--776. https://doi.org/10.1037/0022-0663.98.4.766", "doi": "https://doi.org/10.1037/0022-0663.98.4.766", "aliases": ["Darnon and Butera (2006)", "Darnon and Butera, 2006", "Darnon & Butera (2006)", "Darnon & Butera, 2006", "Darnon et al. (2006)", "Darnon et al., 2006", "Darnon (2006)", "Darnon, 2006"]}, {"id": "ref-14", "full": "Dietvorst, B. J., Simmons, J. P., & Massey, C. (2015). Algorithm aversion: People erroneously avoid algorithms after seeing them err. Journal of Experimental Psychology: General, 144(1), 114--126. https://doi.org/10.1037/xge0000033", "doi": "https://doi.org/10.1037/xge0000033", "aliases": ["Dietvorst and Massey (2015)", "Dietvorst and Massey, 2015", "Dietvorst & Massey (2015)", "Dietvorst & Massey, 2015", "Dietvorst et al. (2015)", "Dietvorst et al., 2015", "Dietvorst (2015)", "Dietvorst, 2015"]}, {"id": "ref-15", "full": "DiPrete, T. A., & Eirich, G. M. (2006). Cumulative advantage as a mechanism for inequality: A review of theoretical and empirical developments. Annual Review of Sociology, 32, 271--297. https://doi.org/10.1146/annurev.soc.32.061604.123127", "doi": "https://doi.org/10.1146/annurev.soc.32.061604.123127", "aliases": ["DiPrete and Eirich (2006)", "DiPrete and Eirich, 2006", "DiPrete & Eirich (2006)", "DiPrete & Eirich, 2006", "DiPrete et al. (2006)", "DiPrete et al., 2006", "DiPrete (2006)", "DiPrete, 2006"]}, {"id": "ref-16", "full": "Dweck, C. S., & Leggett, E. L. (1988). A social-cognitive approach to motivation and personality. Psychological Review, 95(2), 256--273. https://doi.org/10.1037/0033-295X.95.2.256", "doi": "https://doi.org/10.1037/0033-295X.95.2.256", "aliases": ["Dweck and Leggett (1988)", "Dweck and Leggett, 1988", "Dweck & Leggett (1988)", "Dweck & Leggett, 1988", "Dweck et al. (1988)", "Dweck et al., 1988", "Dweck (1988)", "Dweck, 1988"]}, {"id": "ref-17", "full": "Elliot, A. J., & McGregor, H. A. (2001). A 2 × 2 achievement goal framework. Journal of Personality and Social Psychology, 80(3), 501--519. https://doi.org/10.1037/0022-3514.80.3.501", "doi": "https://doi.org/10.1037/0022-3514.80.3.501", "aliases": ["Elliot and McGregor (2001)", "Elliot and McGregor, 2001", "Elliot & McGregor (2001)", "Elliot & McGregor, 2001", "Elliot et al. (2001)", "Elliot et al., 2001", "Elliot (2001)", "Elliot, 2001"]}, {"id": "ref-18", "full": "Epstein, J. M. (1999). Agent-based computational models and generative social science. Complexity, 4(5), 41--60. https://doi.org/10.1002/(SICI)1099-0526(199905/06)4:5\\<41::AID-CPLX9\\>3.0.CO;2-F", "doi": "https://doi.org/10.1002/(SICI)1099-0526(199905/06)4:5\\", "aliases": ["Epstein et al. (1999)", "Epstein et al., 1999", "Epstein (1999)", "Epstein, 1999"]}, {"id": "ref-19", "full": "Fisher, M., Goddu, M. K., & Keil, F. C. (2015). Searching for explanations: How the Internet inflates estimates of internal knowledge. Journal of Experimental Psychology: General, 144(3), 674--687. https://doi.org/10.1037/xge0000070", "doi": "https://doi.org/10.1037/xge0000070", "aliases": ["Fisher and Keil (2015)", "Fisher and Keil, 2015", "Fisher & Keil (2015)", "Fisher et al. (2015)", "Fisher & Keil, 2015", "Fisher et al., 2015", "Fisher (2015)", "Fisher, 2015"]}, {"id": "ref-20", "full": "Foschi, M. (2000). Double standards for competence: Theory and research. Annual Review of Sociology, 26, 21--42. https://doi.org/10.1146/annurev.soc.26.1.21", "doi": "https://doi.org/10.1146/annurev.soc.26.1.21", "aliases": ["Foschi et al. (2000)", "Foschi et al., 2000", "Foschi (2000)", "Foschi, 2000"]}, {"id": "ref-21", "full": "Fricker, M. (2007). Epistemic injustice: Power and the ethics of knowing. Oxford University Press.", "doi": "", "aliases": ["Fricker et al. (2007)", "Fricker et al., 2007", "Fricker (2007)", "Fricker, 2007"]}, {"id": "ref-22", "full": "Goffman, E. (1963). Stigma: Notes on the management of spoiled identity. Prentice-Hall.", "doi": "", "aliases": ["Goffman et al. (1963)", "Goffman et al., 1963", "Goffman (1963)", "Goffman, 1963"]}, {"id": "ref-23", "full": "Granovetter, M. (1985). Economic action and social structure: The problem of embeddedness. American Journal of Sociology, 91(3), 481--510. https://doi.org/10.1086/228311", "doi": "https://doi.org/10.1086/228311", "aliases": ["Granovetter et al. (1985)", "Granovetter et al., 1985", "Granovetter (1985)", "Granovetter, 1985"]}, {"id": "ref-24", "full": "Grimm, V., Railsback, S. F., Vincenot, C. E., et al. (2020). The ODD protocol for describing agent-based and other simulation models: A second update to improve clarity, replication, and structural realism. Journal of Artificial Societies and Social Simulation, 23(2), 7. https://doi.org/10.18564/jasss.4259", "doi": "https://doi.org/10.18564/jasss.4259", "aliases": ["Grimm et al. (2020)", "Grimm et al., 2020", "Grimm (2020)", "Grimm, 2020"]}, {"id": "ref-25", "full": "Hargittai, E. (2010). Digital na(t)ives? Variation in Internet skills and uses among members of the 'Net Generation'. Sociological Inquiry, 80(1), 92--113. https://doi.org/10.1111/j.1475-682X.2009.00317.x", "doi": "https://doi.org/10.1111/j.1475-682X.2009.00317.x", "aliases": ["Hargittai et al. (2010)", "Hargittai et al., 2010", "Hargittai (2010)", "Hargittai, 2010"]}, {"id": "ref-26", "full": "Helsper, E. J. (2012). A corresponding fields model for the links between social and digital exclusion. Communication Theory, 22(4), 403--426. https://doi.org/10.1111/j.1468-2885.2012.01416.x", "doi": "https://doi.org/10.1111/j.1468-2885.2012.01416.x", "aliases": ["Helsper et al. (2012)", "Helsper et al., 2012", "Helsper (2012)", "Helsper, 2012"]}, {"id": "ref-27", "full": "Heckman, J. J., & Mosso, S. (2014). The economics of human development and social mobility. Annual Review of Economics, 6, 689--733. https://doi.org/10.1146/annurev-economics-080213-040753", "doi": "https://doi.org/10.1146/annurev-economics-080213-040753", "aliases": ["Heckman and Mosso (2014)", "Heckman and Mosso, 2014", "Heckman & Mosso (2014)", "Heckman et al. (2014)", "Heckman & Mosso, 2014", "Heckman et al., 2014", "Heckman (2014)", "Heckman, 2014"]}, {"id": "ref-28", "full": "Hinsz, V. B., Tindale, R. S., & Vollrath, D. A. (1997). The emerging conceptualization of groups as information processors. Psychological Bulletin, 121(1), 43--64. https://doi.org/10.1037/0033-2909.121.1.43", "doi": "https://doi.org/10.1037/0033-2909.121.1.43", "aliases": ["Hinsz and Vollrath (1997)", "Hinsz and Vollrath, 1997", "Hinsz & Vollrath (1997)", "Hinsz & Vollrath, 1997", "Hinsz et al. (1997)", "Hinsz et al., 1997", "Hinsz (1997)", "Hinsz, 1997"]}, {"id": "ref-29", "full": "Hollingshead, A. B. (2000). Perceptions of expertise and transactive memory in work relationships. Group Processes & Intergroup Relations, 3(3), 257--267. https://doi.org/10.1177/1368430200033002", "doi": "https://doi.org/10.1177/1368430200033002", "aliases": ["Hollingshead et al. (2000)", "Hollingshead et al., 2000", "Hollingshead (2000)", "Hollingshead, 2000"]}, {"id": "ref-30", "full": "Hutchins, E. (1995). Cognition in the wild. MIT Press.", "doi": "", "aliases": ["Hutchins et al. (1995)", "Hutchins et al., 1995", "Hutchins (1995)", "Hutchins, 1995"]}, {"id": "ref-31", "full": "Johnson, D. W., & Johnson, R. T. (2009). An educational psychology success story: Social interdependence theory and cooperative learning. Educational Researcher, 38(5), 365--379. https://doi.org/10.3102/0013189X09339057", "doi": "https://doi.org/10.3102/0013189X09339057", "aliases": ["Johnson and Johnson (2009)", "Johnson and Johnson, 2009", "Johnson & Johnson (2009)", "Johnson & Johnson, 2009", "Johnson et al. (2009)", "Johnson et al., 2009", "Johnson (2009)", "Johnson, 2009"]}, {"id": "ref-32", "full": "Kalkhoff, W., & Thye, S. R. (2006). Expectation states theory and research: New observations from meta-analysis. Sociological Methods & Research, 35(2), 219--249. https://doi.org/10.1177/0049124106290311", "doi": "https://doi.org/10.1177/0049124106290311", "aliases": ["Kalkhoff and Thye (2006)", "Kalkhoff and Thye, 2006", "Kalkhoff & Thye (2006)", "Kalkhoff et al. (2006)", "Kalkhoff & Thye, 2006", "Kalkhoff et al., 2006", "Kalkhoff (2006)", "Kalkhoff, 2006"]}, {"id": "ref-33", "full": "Koriat, A. (1997). Monitoring one's own knowledge during study: A cue-utilization approach to judgments of learning. Journal of Experimental Psychology: General, 126(4), 349--370. https://doi.org/10.1037/0096-3445.126.4.349", "doi": "https://doi.org/10.1037/0096-3445.126.4.349", "aliases": ["Koriat et al. (1997)", "Koriat et al., 1997", "Koriat (1997)", "Koriat, 1997"]}, {"id": "ref-34", "full": "Kyndt, E., Raes, E., Lismont, B., Timmers, F., Cascallar, E., & Dochy, F. (2013). A meta-analysis of the effects of face-to-face cooperative learning. Educational Research Review, 10, 133--149. https://doi.org/10.1016/j.edurev.2013.02.002", "doi": "https://doi.org/10.1016/j.edurev.2013.02.002", "aliases": ["Kyndt and Dochy (2013)", "Kyndt and Dochy, 2013", "Kyndt & Dochy (2013)", "Kyndt & Dochy, 2013", "Kyndt et al. (2013)", "Kyndt et al., 2013", "Kyndt (2013)", "Kyndt, 2013"]}, {"id": "ref-35", "full": "Laskowski, P. P., Puga-Gonzalez, I., Shults, F. L., & Talmont-Kaminski, K. (2023). A cognitive model of epistemic vigilance in situations of varying competence, consistency, and utility. In F. Squazzoni (Ed.), Advances in Social Simulation (pp. 13--21). Springer. https://doi.org/10.1007/978-3-031-34920-12", "doi": "https://doi.org/10.1007/978-3-031-34920-12", "aliases": ["Laskowski and Talmont-Kaminski (2023)", "Laskowski and Talmont-Kaminski, 2023", "Laskowski & Talmont-Kaminski (2023)", "Laskowski & Talmont-Kaminski, 2023", "Laskowski et al. (2023)", "Laskowski et al., 2023", "Laskowski (2023)", "Laskowski, 2023"]}, {"id": "ref-36", "full": "Lazear, E. P., & Rosen, S. (1981). Rank-order tournaments as optimum labor contracts. Journal of Political Economy, 89(5), 841--864. https://doi.org/10.1086/261010", "doi": "https://doi.org/10.1086/261010", "aliases": ["Lazear and Rosen (1981)", "Lazear and Rosen, 1981", "Lazear & Rosen (1981)", "Lazear et al. (1981)", "Lazear & Rosen, 1981", "Lazear et al., 1981", "Lazear (1981)", "Lazear, 1981"]}, {"id": "ref-37", "full": "Lee, J. D., & See, K. A. (2004). Trust in automation: Designing for appropriate reliance. Human Factors, 46(1), 50--80. https://doi.org/10.1518/hfes.46.1.5030392", "doi": "https://doi.org/10.1518/hfes.46.1.5030392", "aliases": ["Lee and See (2004)", "Lee et al. (2004)", "Lee and See, 2004", "Lee et al., 2004", "Lee & See (2004)", "Lee & See, 2004", "Lee (2004)", "Lee, 2004"]}, {"id": "ref-38", "full": "Link, B. G., & Phelan, J. C. (2001). Conceptualizing stigma. Annual Review of Sociology, 27, 363--385. https://doi.org/10.1146/annurev.soc.27.1.363", "doi": "https://doi.org/10.1146/annurev.soc.27.1.363", "aliases": ["Link and Phelan (2001)", "Link and Phelan, 2001", "Link & Phelan (2001)", "Link & Phelan, 2001", "Link et al. (2001)", "Link et al., 2001", "Link (2001)", "Link, 2001"]}, {"id": "ref-39", "full": "Littlepage, G. E., Robison, W. B., & Reddington, K. (1997). Effects of task experience and group experience on group performance, member ability, and recognition of expertise. Organizational Behavior and Human Decision Processes, 69(2), 133--147. https://doi.org/10.1006/obhd.1997.2677", "doi": "https://doi.org/10.1006/obhd.1997.2677", "aliases": ["Littlepage and Reddington (1997)", "Littlepage and Reddington, 1997", "Littlepage & Reddington (1997)", "Littlepage & Reddington, 1997", "Littlepage et al. (1997)", "Littlepage et al., 1997", "Littlepage (1997)", "Littlepage, 1997"]}, {"id": "ref-40", "full": "Logg, J. M., Minson, J. A., & Moore, D. A. (2019). Algorithm appreciation: People prefer algorithmic to human judgment. Organizational Behavior and Human Decision Processes, 151, 90--103. https://doi.org/10.1016/j.obhdp.2018.12.005", "doi": "https://doi.org/10.1016/j.obhdp.2018.12.005", "aliases": ["Logg and Moore (2019)", "Logg and Moore, 2019", "Logg & Moore (2019)", "Logg & Moore, 2019", "Logg et al. (2019)", "Logg et al., 2019", "Logg (2019)", "Logg, 2019"]}, {"id": "ref-41", "full": "Mercier, H. (2016). The argumentative theory: Predictions and empirical evidence. Trends in Cognitive Sciences, 20(9), 689--700. https://doi.org/10.1016/j.tics.2016.07.001", "doi": "https://doi.org/10.1016/j.tics.2016.07.001", "aliases": ["Mercier et al. (2016)", "Mercier et al., 2016", "Mercier (2016)", "Mercier, 2016"]}, {"id": "ref-42", "full": "Mercier, H., & Sperber, D. (2011). Why do humans reason? Arguments for an argumentative theory. Behavioral and Brain Sciences, 34(2), 57--74. https://doi.org/10.1017/S0140525X10000968", "doi": "https://doi.org/10.1017/S0140525X10000968", "aliases": ["Mercier and Sperber (2011)", "Mercier and Sperber, 2011", "Mercier & Sperber (2011)", "Mercier & Sperber, 2011", "Mercier et al. (2011)", "Mercier et al., 2011", "Mercier (2011)", "Mercier, 2011"]}, {"id": "ref-43", "full": "Merton, R. K. (1968). The Matthew effect in science. Science, 159(3810), 56--63. https://doi.org/10.1126/science.159.3810.56", "doi": "https://doi.org/10.1126/science.159.3810.56", "aliases": ["Merton et al. (1968)", "Merton et al., 1968", "Merton (1968)", "Merton, 1968"]}, {"id": "ref-44", "full": "Nelson, T. O., & Narens, L. (1990). Metamemory: A theoretical framework and new findings. In G. H. Bower (Ed.), The psychology of learning and motivation (Vol. 26, pp. 125--173). Academic Press. https://doi.org/10.1016/S0079-7421(08)60053-5", "doi": "https://doi.org/10.1016/S0079-7421(08)60053-5", "aliases": ["Nelson and Narens (1990)", "Nelson and Narens, 1990", "Nelson & Narens (1990)", "Nelson & Narens, 1990", "Nelson et al. (1990)", "Nelson et al., 1990", "Nelson (1990)", "Nelson, 1990"]}, {"id": "ref-45", "full": "Moss-Racusin, C. A., Dovidio, J. F., Brescoll, V. L., Graham, M. J., & Handelsman, J. (2012). Science faculty's subtle gender biases favor male students. Proceedings of the National Academy of Sciences, 109(41), 16474--16479. https://doi.org/10.1073/pnas.1211286109", "doi": "https://doi.org/10.1073/pnas.1211286109", "aliases": ["Moss-Racusin and Handelsman (2012)", "Moss-Racusin and Handelsman, 2012", "Moss-Racusin & Handelsman (2012)", "Moss-Racusin & Handelsman, 2012", "Moss-Racusin et al. (2012)", "Moss-Racusin et al., 2012", "Moss-Racusin (2012)", "Moss-Racusin, 2012"]}, {"id": "ref-46", "full": "Podolny, J. M. (1993). A status-based model of market competition. American Journal of Sociology, 98(4), 829--872. https://doi.org/10.1086/230091", "doi": "https://doi.org/10.1086/230091", "aliases": ["Podolny et al. (1993)", "Podolny et al., 1993", "Podolny (1993)", "Podolny, 1993"]}, {"id": "ref-47", "full": "Price, P. C., & Stone, E. R. (2004). Intuitive evaluation of likelihood judgment producers: Evidence for a confidence heuristic. Journal of Behavioral Decision Making, 17(1), 39--57. https://doi.org/10.1002/bdm.460", "doi": "https://doi.org/10.1002/bdm.460", "aliases": ["Price and Stone (2004)", "Price and Stone, 2004", "Price & Stone (2004)", "Price & Stone, 2004", "Price et al. (2004)", "Price et al., 2004", "Price (2004)", "Price, 2004"]}, {"id": "ref-48", "full": "Reisinger, D., Kogler, M. L., & Jäger, G. (2023). On the interplay of gullibility, plausibility, and criticism: A computational model of epistemic vigilance. Journal of Artificial Societies and Social Simulation, 26(3), 8. https://doi.org/10.18564/jasss.5136", "doi": "https://doi.org/10.18564/jasss.5136", "aliases": ["Reisinger and Jäger (2023)", "Reisinger and Jäger, 2023", "Reisinger & Jäger (2023)", "Reisinger et al. (2023)", "Reisinger & Jäger, 2023", "Reisinger et al., 2023", "Reisinger (2023)", "Reisinger, 2023"]}, {"id": "ref-49", "full": "Ridgeway, C. L. (2014). Why status matters for inequality. American Sociological Review, 79(1), 1--16. https://doi.org/10.1177/0003122413515997", "doi": "https://doi.org/10.1177/0003122413515997", "aliases": ["Ridgeway et al. (2014)", "Ridgeway et al., 2014", "Ridgeway (2014)", "Ridgeway, 2014"]}, {"id": "ref-50", "full": "Robinson, L., Cotten, S. R., Ono, H., et al. (2015). Digital inequalities and why they matter. Information, Communication & Society, 18(5), 569--582. https://doi.org/10.1080/1369118X.2015.1012532", "doi": "https://doi.org/10.1080/1369118X.2015.1012532", "aliases": ["Robinson et al. (2015)", "Robinson et al., 2015", "Robinson (2015)", "Robinson, 2015"]}, {"id": "ref-51", "full": "Rybnik, M., Puga-Gonzalez, I., Shults, F. L., Dąbrowska-Prokopowska, E., & Talmont-Kaminski, K. (2023). An agent-based model of the role of epistemic vigilance in human cooperation. In F. Squazzoni (Ed.), Advances in Social Simulation (pp. 75--86). Springer. https://doi.org/10.1007/978-3-031-34920-17", "doi": "https://doi.org/10.1007/978-3-031-34920-17", "aliases": ["Rybnik and Talmont-Kaminski (2023)", "Rybnik and Talmont-Kaminski, 2023", "Rybnik & Talmont-Kaminski (2023)", "Rybnik & Talmont-Kaminski, 2023", "Rybnik et al. (2023)", "Rybnik et al., 2023", "Rybnik (2023)", "Rybnik, 2023"]}, {"id": "ref-52", "full": "Scheerder, A., van Deursen, A. J. A. M., & van Dijk, J. A. G. M. (2017). Determinants of Internet skills, uses and outcomes: A systematic review of the second- and third-level digital divide. Telematics and Informatics, 34(8), 1607--1624. https://doi.org/10.1016/j.tele.2017.07.007", "doi": "https://doi.org/10.1016/j.tele.2017.07.007", "aliases": ["Scheerder and van Dijk (2017)", "Scheerder and van Dijk, 2017", "Scheerder & van Dijk (2017)", "Scheerder & van Dijk, 2017", "Scheerder et al. (2017)", "Scheerder et al., 2017", "Scheerder (2017)", "Scheerder, 2017"]}, {"id": "ref-53", "full": "Settles, I. H., Jones, M. K., Buchanan, N. T., & Brassel, S. T. (2022). Epistemic exclusion of women faculty and faculty of color: Understanding scholar(ly) devaluation as a predictor of turnover intentions. Journal of Higher Education, 93(1), 31--55. https://doi.org/10.1080/00221546.2021.1914494", "doi": "https://doi.org/10.1080/00221546.2021.1914494", "aliases": ["Settles and Brassel (2022)", "Settles and Brassel, 2022", "Settles & Brassel (2022)", "Settles & Brassel, 2022", "Settles et al. (2022)", "Settles et al., 2022", "Settles (2022)", "Settles, 2022"]}, {"id": "ref-54", "full": "Sommet, N., Darnon, C., Mugny, G., Quiamzade, A., Pulfrey, C., Dompnier, B., & Butera, F. (2014). Performance goals in conflictual social interactions: Towards the distinction between two modes of relational conflict regulation. British Journal of Social Psychology, 53(1), 134--153. https://doi.org/10.1111/bjso.12015", "doi": "https://doi.org/10.1111/bjso.12015", "aliases": ["Sommet and Butera (2014)", "Sommet and Butera, 2014", "Sommet & Butera (2014)", "Sommet & Butera, 2014", "Sommet et al. (2014)", "Sommet et al., 2014", "Sommet (2014)", "Sommet, 2014"]}, {"id": "ref-55", "full": "Sparrow, B., Liu, J., & Wegner, D. M. (2011). Google effects on memory: Cognitive consequences of having information at our fingertips. Science, 333(6043), 776--778. https://doi.org/10.1126/science.1207745", "doi": "https://doi.org/10.1126/science.1207745", "aliases": ["Sparrow and Wegner (2011)", "Sparrow and Wegner, 2011", "Sparrow & Wegner (2011)", "Sparrow & Wegner, 2011", "Sparrow et al. (2011)", "Sparrow et al., 2011", "Sparrow (2011)", "Sparrow, 2011"]}, {"id": "ref-56", "full": "Sperber, D., Clément, F., Heintz, C., Mascaro, O., Mercier, H., Origgi, G., & Wilson, D. (2010). Epistemic vigilance. Mind & Language, 25(4), 359--393. https://doi.org/10.1111/j.1468-0017.2010.01394.x", "doi": "https://doi.org/10.1111/j.1468-0017.2010.01394.x", "aliases": ["Sperber and Wilson (2010)", "Sperber and Wilson, 2010", "Sperber & Wilson (2010)", "Sperber & Wilson, 2010", "Sperber et al. (2010)", "Sperber et al., 2010", "Sperber (2010)", "Sperber, 2010"]}, {"id": "ref-57", "full": "Stanovich, K. E. (1986). Matthew effects in reading: Some consequences of individual differences in the acquisition of literacy. Reading Research Quarterly, 21(4), 360--407. https://doi.org/10.1598/RRQ.21.4.1", "doi": "https://doi.org/10.1598/RRQ.21.4.1", "aliases": ["Stanovich et al. (1986)", "Stanovich et al., 1986", "Stanovich (1986)", "Stanovich, 1986"]}, {"id": "ref-58", "full": "Stasser, G., & Titus, W. (1985). Pooling of unshared information in group decision making: Biased information sampling during discussion. Journal of Personality and Social Psychology, 48(6), 1467--1478. https://doi.org/10.1037/0022-3514.48.6.1467", "doi": "https://doi.org/10.1037/0022-3514.48.6.1467", "aliases": ["Stasser and Titus (1985)", "Stasser and Titus, 1985", "Stasser & Titus (1985)", "Stasser & Titus, 1985", "Stasser et al. (1985)", "Stasser et al., 1985", "Stasser (1985)", "Stasser, 1985"]}, {"id": "ref-59", "full": "Stefanelli, A., & Seidl, R. (2017). Opinion communication on contested topics: How empirics and arguments can improve social simulation. Journal of Artificial Societies and Social Simulation, 20(4), 3. https://doi.org/10.18564/jasss.3492", "doi": "https://doi.org/10.18564/jasss.3492", "aliases": ["Stefanelli and Seidl (2017)", "Stefanelli and Seidl, 2017", "Stefanelli & Seidl (2017)", "Stefanelli et al. (2017)", "Stefanelli & Seidl, 2017", "Stefanelli et al., 2017", "Stefanelli (2017)", "Stefanelli, 2017"]}, {"id": "ref-60", "full": "Thiele, J. C., Kurth, W., & Grimm, V. (2014). Facilitating parameter estimation and sensitivity analysis of agent-based models: A cookbook using NetLogo and R. Journal of Artificial Societies and Social Simulation, 17(3), 11. https://doi.org/10.18564/jasss.2503", "doi": "https://doi.org/10.18564/jasss.2503", "aliases": ["Thiele and Grimm (2014)", "Thiele and Grimm, 2014", "Thiele & Grimm (2014)", "Thiele et al. (2014)", "Thiele & Grimm, 2014", "Thiele et al., 2014", "Thiele (2014)", "Thiele, 2014"]}, {"id": "ref-61", "full": "van Deursen, A. J. A. M., & Helsper, E. J. (2015). The third-level digital divide: Who benefits most from being online? In L. Robinson et al. (Eds.), Communication and Information Technologies Annual: Digital Distinctions and Inequalities (Vol. 10, pp. 29--52). Emerald. https://doi.org/10.1108/S2050-206020150000010002", "doi": "https://doi.org/10.1108/S2050-206020150000010002", "aliases": ["van Deursen and Helsper (2015)", "van Deursen and Helsper, 2015", "van Deursen & Helsper (2015)", "van Deursen & Helsper, 2015", "van Deursen et al. (2015)", "van Deursen et al., 2015", "van Deursen (2015)", "van Deursen, 2015"]}, {"id": "ref-62", "full": "van Deursen, A. J. A. M., & van Dijk, J. A. G. M. (2011). Internet skills and the digital divide. New Media & Society, 13(6), 893--911. https://doi.org/10.1177/1461444810386774", "doi": "https://doi.org/10.1177/1461444810386774", "aliases": ["van Deursen and van Dijk (2011)", "van Deursen and van Dijk, 2011", "van Deursen & van Dijk (2011)", "van Deursen & van Dijk, 2011", "van Deursen et al. (2011)", "van Deursen et al., 2011", "van Deursen (2011)", "van Deursen, 2011"]}, {"id": "ref-63", "full": "Wecker, C., & Fischer, F. (2014). Where is the evidence? A meta-analysis on the role of argumentation for the acquisition of domain-specific knowledge in computer-supported collaborative learning. Computers & Education, 75, 218--228. https://doi.org/10.1016/j.compedu.2014.02.016", "doi": "https://doi.org/10.1016/j.compedu.2014.02.016", "aliases": ["Wecker and Fischer (2014)", "Wecker and Fischer, 2014", "Wecker & Fischer (2014)", "Wecker & Fischer, 2014", "Wecker et al. (2014)", "Wecker et al., 2014", "Wecker (2014)", "Wecker, 2014"]}, {"id": "ref-64", "full": "Windrum, P., Fagiolo, G., & Moneta, A. (2007). Empirical validation of agent-based models: Alternatives and prospects. Journal of Artificial Societies and Social Simulation, 10(2), 8. https://www.jasss.org/10/2/8.html", "doi": "", "aliases": ["Windrum and Moneta (2007)", "Windrum and Moneta, 2007", "Windrum & Moneta (2007)", "Windrum & Moneta, 2007", "Windrum et al. (2007)", "Windrum et al., 2007", "Windrum (2007)", "Windrum, 2007"]}, {"id": "ref-65", "full": "Vayre, J.-S., et al. (2026a). Prior Knowledge and Learning from Open Web Search. MOVICI preprint, final deposit version. Authors and repository identifier to be confirmed.", "doi": "", "aliases": ["Vayre et al. (2026a)", "Vayre et al., 2026a", "Vayre (2026a)", "Vayre, 2026a"]}, {"id": "ref-66", "full": "Vayre, J.-S., et al. (2026b). Epistemic Credit in Cooperative and Competitive Debate. MOVICI preprint, final deposit version. Authors and repository identifier to be confirmed.", "doi": "", "aliases": ["Vayre et al. (2026b)", "Vayre et al., 2026b", "Vayre (2026b)", "Vayre, 2026b"]}, {"id": "ref-67", "full": "Vayre, J.-S., et al. (2026c). Learning from Documents and from Others: Knowledge Change and Epistemic Coordination. MOVICI Article 3 preprint, final deposit version. Authors and repository identifier to be confirmed.", "doi": "", "aliases": ["Vayre et al. (2026c)", "Vayre et al., 2026c", "Vayre (2026c)", "Vayre, 2026c"]}, {"id": "ref-68", "full": "Vayre, J.-S., et al. (2026d). CAVL: A Cognitive Architecture for Vigilant Learning. Preprint, final deposit version. Authors and repository identifier to be confirmed.", "doi": "", "aliases": ["Vayre et al. (2026d)", "Vayre et al., 2026d", "Vayre (2026d)", "Vayre, 2026d"]}];
</script>



</main> <!-- /main -->


<div id="movici-citation-tooltip" role="tooltip"></div>

<script>

(function () {

  function escRE(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }



  function run() {

    const refs = window.MOVICI_REFERENCES || [];

    if (!refs.length) return;



    const aliasMap = new Map();

    refs.forEach(ref => (ref.aliases || []).forEach(a => {

      if (a && !aliasMap.has(a)) aliasMap.set(a, ref);

    }));

    const aliases = Array.from(aliasMap.keys()).sort((a,b) => b.length - a.length);

    if (!aliases.length) return;



    const rx = new RegExp(aliases.map(escRE).join('|'), 'g');

    const root = document.querySelector('main.content') || document.querySelector('main') || document.body;

    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);

    const nodes = [];

    let node;

    while ((node = walker.nextNode())) {

      const p = node.parentElement;

      if (!p) continue;

      if (p.closest('#movici-references, script, style, pre, code, a, .movici-citation-hover')) continue;

      if (rx.test(node.nodeValue)) nodes.push(node);

      rx.lastIndex = 0;

    }



    nodes.forEach(textNode => {

      const text = textNode.nodeValue;

      let last = 0, match;

      rx.lastIndex = 0;

      const frag = document.createDocumentFragment();

      while ((match = rx.exec(text))) {

        if (match.index > last) frag.appendChild(document.createTextNode(text.slice(last, match.index)));

        const ref = aliasMap.get(match[0]);

        const el = ref && ref.doi ? document.createElement('a') : document.createElement('span');

        el.className = 'movici-citation-hover';

        el.textContent = match[0];

        el.dataset.full = (ref && ref.full) || '';

        el.dataset.doi = (ref && ref.doi) || '';

        if (ref && ref.doi) {

          el.href = ref.doi;

          el.target = '_blank';

          el.rel = 'noopener';

          el.setAttribute('aria-label', match[0] + ' — open DOI');

        }

        frag.appendChild(el);

        last = rx.lastIndex;

      }

      if (last < text.length) frag.appendChild(document.createTextNode(text.slice(last)));

      textNode.replaceWith(frag);

    });



    const tip = document.getElementById('movici-citation-tooltip');

    let hideTimer = null;



    function show(el) {

      clearTimeout(hideTimer);

      const full = el.dataset.full || '';

      const doi = el.dataset.doi || '';

      tip.innerHTML = '';

      const txt = document.createElement('div');

      txt.textContent = full;

      tip.appendChild(txt);

      if (doi) {

        const a = document.createElement('a');

        a.href = doi;

        a.target = '_blank';

        a.rel = 'noopener';

        a.textContent = 'Open DOI';

        tip.appendChild(a);

      }

      tip.style.display = 'block';

      const r = el.getBoundingClientRect();

      const w = Math.min(460, window.innerWidth - 24);

      tip.style.maxWidth = w + 'px';

      let left = Math.min(r.left, window.innerWidth - w - 12);

      left = Math.max(12, left);

      let top = r.bottom + 8;

      requestAnimationFrame(() => {

        const th = tip.getBoundingClientRect().height;

        if (top + th > window.innerHeight - 12) top = Math.max(12, r.top - th - 8);

        tip.style.left = left + 'px';

        tip.style.top = top + 'px';

      });

    }



    function scheduleHide() {

      hideTimer = setTimeout(() => { tip.style.display = 'none'; }, 180);

    }



    document.querySelectorAll('.movici-citation-hover').forEach(el => {

      el.addEventListener('mouseenter', () => show(el));

      el.addEventListener('mouseleave', scheduleHide);

      el.addEventListener('focus', () => show(el));

      el.addEventListener('blur', scheduleHide);

      el.tabIndex = 0;

    });

    tip.addEventListener('mouseenter', () => clearTimeout(hideTimer));

    tip.addEventListener('mouseleave', scheduleHide);

  }



  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', run);

  else run();

})();

</script>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>MOVICI Research Programme · Working papers and research materials</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>