<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Learning from Documents and from Others: Knowledge Change and Epistemic Coordination – MOVICI</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-172ba59bd5e0b52282274ba0c0cc16fc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">MOVICI</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-working-papers" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Working Papers</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-working-papers">    
        <li>
    <a class="dropdown-item" href="../../working-papers/wp01-cavl/index.html">
 <span class="dropdown-text">WP01 — CAVL</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../working-papers/wp02-information-search/index.html">
 <span class="dropdown-text">WP02 — Information Search</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../working-papers/wp03-debate/index.html">
 <span class="dropdown-text">WP03 — Debate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../working-papers/wp04-search-debate/index.html">
 <span class="dropdown-text">WP04 — Information Search &amp; Debate</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../working-papers/wp05-agent-based-model/index.html">
 <span class="dropdown-text">WP05 — Agent-Based Model</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../team.html"> 
<span class="menu-text">Project Team</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../funding.html"> 
<span class="menu-text">Funding &amp; Support</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#video-presentation" id="toc-video-presentation" class="nav-link active" data-scroll-target="#video-presentation">Video Presentation</a></li>
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a></li>
  <li><a href="#theoretical-framework-and-predictions" id="toc-theoretical-framework-and-predictions" class="nav-link" data-scroll-target="#theoretical-framework-and-predictions">2. Theoretical framework and predictions</a>
  <ul class="collapse">
  <li><a href="#cognitive-technologies-and-external-epistemic-environments" id="toc-cognitive-technologies-and-external-epistemic-environments" class="nav-link" data-scroll-target="#cognitive-technologies-and-external-epistemic-environments">2.1. Cognitive technologies and external epistemic environments</a></li>
  <li><a href="#cavl-vigilant-learning-and-dual-social-embedding" id="toc-cavl-vigilant-learning-and-dual-social-embedding" class="nav-link" data-scroll-target="#cavl-vigilant-learning-and-dual-social-embedding">2.2. CAVL: vigilant learning and dual social embedding</a></li>
  <li><a href="#factual-transformation-document-availability-prior-knowledge-and-score-homogenization" id="toc-factual-transformation-document-availability-prior-knowledge-and-score-homogenization" class="nav-link" data-scroll-target="#factual-transformation-document-availability-prior-knowledge-and-score-homogenization">2.3. Factual transformation: document availability, prior knowledge, and score homogenization</a></li>
  <li><a href="#distinct-forms-of-integration-facts-subjective-knowledge-and-attitudes" id="toc-distinct-forms-of-integration-facts-subjective-knowledge-and-attitudes" class="nav-link" data-scroll-target="#distinct-forms-of-integration-facts-subjective-knowledge-and-attitudes">2.4. Distinct forms of integration: facts, subjective knowledge, and attitudes</a></li>
  <li><a href="#human-sources-transactive-memory-social-comparison-and-epistemic-credit" id="toc-human-sources-transactive-memory-social-comparison-and-epistemic-credit" class="nav-link" data-scroll-target="#human-sources-transactive-memory-social-comparison-and-epistemic-credit">2.5. Human sources: transactive memory, social comparison, and epistemic credit</a></li>
  <li><a href="#complementary-analysis-and-the-human-epistemic-bottleneck" id="toc-complementary-analysis-and-the-human-epistemic-bottleneck" class="nav-link" data-scroll-target="#complementary-analysis-and-the-human-epistemic-bottleneck">2.6. Complementary analysis and the human epistemic bottleneck</a></li>
  </ul></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">3. Method</a>
  <ul class="collapse">
  <li><a href="#participants-and-design" id="toc-participants-and-design" class="nav-link" data-scroll-target="#participants-and-design">3.1. Participants and design</a></li>
  <li><a href="#procedure-parallel-structure-and-ecological-validity" id="toc-procedure-parallel-structure-and-ecological-validity" class="nav-link" data-scroll-target="#procedure-parallel-structure-and-ecological-validity">3.2. Procedure, parallel structure, and ecological validity</a></li>
  <li><a href="#measures" id="toc-measures" class="nav-link" data-scroll-target="#measures">3.3. Measures</a></li>
  <li><a href="#analysis-strategy" id="toc-analysis-strategy" class="nav-link" data-scroll-target="#analysis-strategy">3.4. Analysis strategy</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">4. Results</a>
  <ul class="collapse">
  <li><a href="#baseline-balance" id="toc-baseline-balance" class="nav-link" data-scroll-target="#baseline-balance">4.1. Baseline balance</a></li>
  <li><a href="#h1---different-factual-trajectories-across-the-protocol" id="toc-h1---different-factual-trajectories-across-the-protocol" class="nav-link" data-scroll-target="#h1---different-factual-trajectories-across-the-protocol">4.2. H1 - Different factual trajectories across the protocol</a></li>
  <li><a href="#h2---factual-subjective-and-attitudinal-trajectories-differ-across-t1-t2-and-t3" id="toc-h2---factual-subjective-and-attitudinal-trajectories-differ-across-t1-t2-and-t3" class="nav-link" data-scroll-target="#h2---factual-subjective-and-attitudinal-trajectories-differ-across-t1-t2-and-t3">4.3. H2 - Factual, subjective, and attitudinal trajectories differ across T1, T2, and T3</a></li>
  <li><a href="#h3---human-credit-and-calibration-are-more-sensitive-to-social-structure" id="toc-h3---human-credit-and-calibration-are-more-sensitive-to-social-structure" class="nav-link" data-scroll-target="#h3---human-credit-and-calibration-are-more-sensitive-to-social-structure">4.4. H3 - Human credit and calibration are more sensitive to social structure</a></li>
  <li><a href="#c1---document-based-credit-and-initial-factual-knowledge" id="toc-c1---document-based-credit-and-initial-factual-knowledge" class="nav-link" data-scroll-target="#c1---document-based-credit-and-initial-factual-knowledge">4.5. C1 - Document-based credit and initial factual knowledge</a></li>
  <li><a href="#rq1---does-factual-knowledge-available-in-others-become-a-learning-resource" id="toc-rq1---does-factual-knowledge-available-in-others-become-a-learning-resource" class="nav-link" data-scroll-target="#rq1---does-factual-knowledge-available-in-others-become-a-learning-resource">4.6. RQ1 - Does factual knowledge available in others become a learning resource?</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">5. Discussion</a>
  <ul class="collapse">
  <li><a href="#external-representations-can-support-domain-knowledge-without-removing-the-social" id="toc-external-representations-can-support-domain-knowledge-without-removing-the-social" class="nav-link" data-scroll-target="#external-representations-can-support-domain-knowledge-without-removing-the-social">5.1. External representations can support domain knowledge without removing the social</a></li>
  <li><a href="#human-interaction-can-amplify-learning-when-social-and-epistemic-processes-align" id="toc-human-interaction-can-amplify-learning-when-social-and-epistemic-processes-align" class="nav-link" data-scroll-target="#human-interaction-can-amplify-learning-when-social-and-epistemic-processes-align">5.2. Human interaction can amplify learning when social and epistemic processes align</a></li>
  <li><a href="#moving-from-documents-to-interlocutors-adds-an-epistemic-coordination-bottleneck" id="toc-moving-from-documents-to-interlocutors-adds-an-epistemic-coordination-bottleneck" class="nav-link" data-scroll-target="#moving-from-documents-to-interlocutors-adds-an-epistemic-coordination-bottleneck">5.3. Moving from documents to interlocutors adds an epistemic-coordination bottleneck</a></li>
  <li><a href="#what-the-comparison-contributes-to-cavl" id="toc-what-the-comparison-contributes-to-cavl" class="nav-link" data-scroll-target="#what-the-comparison-contributes-to-cavl">5.4. What the comparison contributes to CAVL</a></li>
  <li><a href="#implications-for-instruction" id="toc-implications-for-instruction" class="nav-link" data-scroll-target="#implications-for-instruction">5.5. Implications for instruction</a></li>
  </ul></li>
  <li><a href="#limitations-and-future-directions" id="toc-limitations-and-future-directions" class="nav-link" data-scroll-target="#limitations-and-future-directions">6. Limitations and future directions</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">7. Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Learning from Documents and from Others: Knowledge Change and Epistemic Coordination</h1>
<p class="subtitle lead">MOVICI Working Paper 04</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="movici-author">
MOVICI Research Programme
</div>
<div class="movici-meta">
Working paper · 2026 · Preprint — not peer reviewed
</div>
<div class="resources">
<p><span class="resources-title">Resources</span> <a class="resource-link" href="files/MOVICI_WP04.pdf">Download PDF</a> <a class="resource-link" href="files/MOVICI_WP04_search_debate_Replication_Package.zip">Data &amp; replication package</a></p>
</div>
<section id="video-presentation" class="level2">
<h2 class="anchored" data-anchor-id="video-presentation">Video Presentation</h2>
<div class="video-embed">
<iframe src="https://www.youtube.com/embed/JzkDOJrYhds" title="MOVICI Working Paper 04 video presentation" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="">
</iframe>
</div>
</section>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<div class="abstract-block">
<p>Document-based environments and human interaction both give access to knowledge beyond individual memory, but they impose different learning constraints. External representations stabilize information and make it revisitable. Human sources add reciprocity, social comparison, and the need to identify who knows what. Using CAVL (Cognitive Architecture for Vigilant Learning), we compared these two configurations within the same 96 participants in MOVICI. Participants first completed an approximately 20-minute open Web search followed by source/argument recall and evaluation before T2. They then completed a 20-minute cooperative or competitive debate followed by parallel partner/argument recall and evaluation before T3. Factual scores increased from T1 to T2 by 1.396 points out of 20 and remained 1.167 points above T1 at T3; score variance fell by 55.3% at T2 and remained 40.4% below baseline at T3. Subjective knowledge increased more gradually and was 0.198 points above T1 at T3 (p = .0056). Attitudes shifted in both periods and were 4.281 points lower at T3 than at T1 (p &lt; .001), with the larger adjacent-period change occurring before T2. Cooperation/competition was much more strongly associated with epistemic credit for human than for recalled Web sources (interaction b = 1.019 SD, p = .0017), and cooperation was associated with lower self-calibration error after the interactional sequence. Measured factual knowledge in partners was only weakly related to perceived expertise and to others' final factual level; robustness analyses using the highest-scoring partner led to the same conclusion. The findings distinguish information availability from epistemic uptake and show that factual, metacognitive, and attitudinal change follow different temporal profiles across the same sequential learning protocol.</p>
</div>
<div class="keywords">
<p><strong>Keywords:</strong> learning; Web search; debate; epistemic vigilance; metacognition; transactive memory; CAVL</p>
</div>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>Much human learning depends on knowledge that is not already stored in individual memory. That knowledge may be carried by other people or by inscription systems such as writing, books, databases, search engines, and digital environments. These resources are not neutral containers. They change how information can be preserved, compared, revisited, and coordinated with what a learner already knows (Donald, 1991; Hutchins, 1995; Salomon et al., 1991). They also allow socially produced knowledge to remain available beyond the interaction in which it was produced.</p>
<p>Externalization does not make document-based learning asocial. A document condenses prior social work: production, selection, validation, classification, and diffusion. Its distinctive property is that information becomes partly decoupled from an immediate reciprocal relationship with its author. A reader can inspect content, provenance, and coherence without simultaneously managing a present interlocutor. Distributed cognition and cognitive-offloading approaches describe this redistribution of processing across internal and external resources (Clark &amp; Chalmers, 1998; Hollan et al., 2000; Risko &amp; Gilbert, 2016).</p>
<p>A medium does not produce learning by itself. Effects depend on the task, methods, prior knowledge, and learner activity (Clark, 1983). Educational technologies show positive but heterogeneous average effects (Tamim et al., 2011). Prior domain knowledge strongly predicts later knowledge levels, although its relation to learning gains is heterogeneous across tasks and learners (Simonsmeier et al., 2022).</p>
<p>Human interaction offers a different cognitive power. Humans learn extensively from others and coordinate knowledge through joint attention, language, reasoning, and cultural transmission (Tomasello, 1999; Heyes, 2020). Cooperative learning has positive average effects on achievement and attitudes (Kyndt et al., 2013). ICAP likewise predicts an advantage for interactive engagement when participants genuinely co-construct new inferences (Chi &amp; Wylie, 2014). Yet this power is conditional. Collaboration can distribute processing across people while also adding communication and coordination costs (Janssen et al., 2010; Kirschner et al., 2018). Partners must establish common ground, identify who knows what, and coordinate contributions. Janssen and Kirschner (2020) describe this requirement as mutual cognitive interdependence. Collaboration scripts show the same principle: effects on domain knowledge are more favorable when interaction becomes genuinely transactive and one participant's reasoning builds on another's contribution (Vogel et al., 2017). Social processes are therefore neither noise added to knowledge nor a guarantee of knowledge. When competence, trust, and epistemic goals align, they can make collective learning highly effective.</p>
<p>MOVICI provides an opportunity to observe these two configurations within the same participants. The first sequence combines open Web search, evaluation of recalled sources, and recall/evaluation of their arguments before T2. The second combines cooperative or competitive debate, evaluation of partners, and recall/evaluation of their arguments before T3. The post-activity structure is deliberately parallel, while each activity retains its functional properties.</p>
<p>Separate analyses of the two sequences are reported in companion manuscripts (Vayre et al., 2026a, 2026b). They answer phase-specific questions. The present study has a different goal: it uses a common comparative framework to examine how two external epistemic environments are associated with different forms of factual, metacognitive, attitudinal, and social change in the same learners.</p>
<p>We use CAVL, the Cognitive Architecture for Vigilant Learning, as an integrative framework (Vayre et al., 2026c). CAVL links mechanisms documented in established traditions: prior knowledge, distributed cognition, epistemic vigilance, metacognitive monitoring, source representations, transactive memory, and social goals. It distinguishes structural social embedding, which shapes resources and credibility criteria before an episode, from interactional embedding, which acts through a present reciprocal relationship. The central claim is not that knowledge and sociality oppose each other. Knowledge is socially produced. Rather, immediate interaction adds coordination, comparison, trust, reputation, and status. These mechanisms can strengthen learning when they track competence and accuracy. They can also redirect processing toward other social goals.</p>
</section>
<section id="theoretical-framework-and-predictions" class="level2">
<h2 class="anchored" data-anchor-id="theoretical-framework-and-predictions">2. Theoretical framework and predictions</h2>
<section id="cognitive-technologies-and-external-epistemic-environments" class="level3">
<h3 class="anchored" data-anchor-id="cognitive-technologies-and-external-epistemic-environments">2.1. Cognitive technologies and external epistemic environments</h3>
<p>Writing, books, and digital systems stabilize representations beyond an individual's biological memory. Donald (1991) described external symbolic storage, while Hutchins (1995) and Hollan et al.&nbsp;(2000) showed how public representations participate in distributed cognitive systems. Externalization does not replace internal memory. It changes the activity. Searching, selecting, comparing, annotating, revisiting, and linking representations become cognitive operations in their own right.</p>
<p>Digital environments amplify availability, but they also increase heterogeneity and provenance problems. Web search requires learners to formulate a need, choose intermediaries, select documents, assess sources, and decide when to continue or stop (Marchionini, 1995; Pirolli &amp; Card, 1999; Rieh et al., 2016). Multiple-document comprehension further requires learners to represent content and sources together and to coordinate relations across documents (Perfetti et al., 1999; Rouet, 2006; Bråten et al., 2011; Anmarkrud et al., 2022).</p>
<p>This perspective avoids a simple technology-versus-human contrast. Documents are social products, but they stabilize information and reduce its dependence on immediate reciprocity. A human source can adapt an explanation, answer, challenge, and correct. The same source also becomes a social partner. The functional question is therefore which operations each environment facilitates and which additional operations it requires.</p>
</section>
<section id="cavl-vigilant-learning-and-dual-social-embedding" class="level3">
<h3 class="anchored" data-anchor-id="cavl-vigilant-learning-and-dual-social-embedding">2.2. CAVL: vigilant learning and dual social embedding</h3>
<p>CAVL defines vigilant learning as the regulated integration of socially available information. It separates exposure, comprehension, evaluation, acceptance, and uptake. Information may be encountered without being understood, understood without being accepted, or used to update a source representation without changing factual knowledge (Vayre et al., 2026c; Sperber et al., 2010).</p>
<p>Two distinctions matter here. First, measured or effective competence, subjective competence, perceived competence in others, and epistemic credit are related but not equivalent. Second, structural and interactional embedding act through different routes. Structural embedding includes prior learning trajectories, institutions, credibility norms, and verification costs. Interactional embedding emerges when the source is a present partner who can respond, judge, cooperate, compete, and change the learner's relative social position.</p>
<p>Moving from a document to an interlocutor is therefore more than changing channels. It adds social coordination to an epistemic task. Human cognition is highly adapted for social learning and cultural transmission (Tomasello, 1999; Heyes, 2020), and reasoning itself can serve argumentative exchange (Mercier &amp; Sperber, 2011). These mechanisms do not serve accuracy alone. They also serve coordination, affiliation, reputation, and disagreement management. Social cues may therefore be epistemically diagnostic or non-diagnostic. When they track competence and goals favor accuracy, social learning can be exceptionally effective. When they diverge, relational regulation and factual integration can compete.</p>
<p>Figure 1. Two routes from external information to epistemic uptake.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 46%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Document-based environment</strong></th>
<th style="text-align: left;"><strong>Interactional human environment</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Socially produced information -&gt; search / selection / provenance</td>
<td style="text-align: left;">Knowledge embodied in others -&gt; recognition of who knows what</td>
</tr>
<tr class="even">
<td style="text-align: left;">Epistemic credit -&gt; factual / metacognitive / attitudinal integration</td>
<td style="text-align: left;">Epistemic credit -&gt; factual / metacognitive / attitudinal integration</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Distinctive affordances: stable, revisitable, self-selected representations</td>
<td style="text-align: left;">Distinctive affordances: adaptive explanation, reciprocity, correction, comparison</td>
</tr>
<tr class="even">
<td style="text-align: left;">Main coordination problem: selecting and evaluating external representations</td>
<td style="text-align: left;">Main coordination problem: identifying competence while managing social interdependence</td>
</tr>
</tbody>
</table>
<p><strong>Note.</strong> Conceptual synthesis from CAVL, distributed cognition, collaborative cognitive load theory, and transactive-memory perspectives.</p>
</section>
<section id="factual-transformation-document-availability-prior-knowledge-and-score-homogenization" class="level3">
<h3 class="anchored" data-anchor-id="factual-transformation-document-availability-prior-knowledge-and-score-homogenization">2.3. Factual transformation: document availability, prior knowledge, and score homogenization</h3>
<p>In the document-based sequence, participants can stabilize activity around self-selected information. Search organizes exposure. Recall and evaluation then require reconstruction of sources and arguments before T2. In the phase-specific analysis, the number of recalled sources did not explain T2 once prior knowledge, SES, and condition were considered, whereas average epistemic evaluation of retained sources remained associated with T2 (Vayre et al., 2026a). External information therefore does not become knowledge through exposure alone.</p>
<p>Prior knowledge remains an important learner characteristic, although its relation to learning gains is heterogeneous (Simonsmeier et al., 2022). In multiple-document settings, topic knowledge is also associated with how learners evaluate and use source information (Bråten et al., 2011; Anmarkrud et al., 2022). Open information access therefore does not place learners on equal footing. Yet a common external environment can still reduce observed score differences if initially less-informed participants gain relatively more from accessible, revisitable representations.</p>
<p>The interactional sequence has another potential. Collaborative Cognitive Load Theory proposes that a group can distribute task elements across multiple working memories, creating a collective working-memory resource (Kirschner et al., 2018). The gain is conditional. Collaboration also creates transaction costs: communication, coordination, common-ground construction, and monitoring of others' contributions (Janssen et al., 2010). Mutual cognitive interdependence adds a further requirement: members must learn where relevant expertise resides and when to rely on it (Janssen &amp; Kirschner, 2020). Experimental work has shown that collaboration can be more efficient than individual work for complex tasks yet less efficient for simpler tasks (Kirschner et al., 2011). The balance between collective resources and coordination costs therefore matters.</p>
<p>This condition is central to MOVICI. Debate can be highly productive when partners hold complementary knowledge, make it visible, and build on one another's contributions. ICAP and collaboration-script research predict precisely this advantage when interaction becomes constructive and transactive (Chi &amp; Wylie, 2014; Vogel et al., 2017). A meta-analysis of CSCL argumentation interventions likewise found more consistent effects on argumentation than on domain-specific knowledge, with equivocal evidence that improved argumentation mediates knowledge gains (Wecker &amp; Fischer, 2014). The MOVICI debate did not force this level of transactivity. It also required argument production, social comparison, and cooperative or competitive goal management. In addition, it followed a first sequence that could already change the knowledge state. Our prediction is therefore specific to this sequential design.</p>
<p>H1 - Factual transformation. In the MOVICI sequence, factual scores should increase and become less dispersed from T1 to T2. The T2-to-T3 period should not add a substantial positive factual gain and should show weaker maintenance of that homogenization. We also examine T1-to-T3 change to determine how much of the first-period difference remains visible at protocol end.</p>
</section>
<section id="distinct-forms-of-integration-facts-subjective-knowledge-and-attitudes" class="level3">
<h3 class="anchored" data-anchor-id="distinct-forms-of-integration-facts-subjective-knowledge-and-attitudes">2.4. Distinct forms of integration: facts, subjective knowledge, and attitudes</h3>
<p>A factual score does not exhaust learning. CAVL separates factual knowledge, monitoring of one's own competence, evaluation of the topic, and updating of source representations. These outcomes can change differently because they rely on different cues and functions.</p>
<p>Metacognition provides one example. Judgments of knowledge are inferred from cues such as familiarity, fluency, difficulty, and perceived performance rather than read directly from memory (Nelson &amp; Narens, 1990; Koriat, 1997). Online search can inflate a feeling of internal knowledge because information is easily accessible (Fisher et al., 2015). Discussion adds social-comparison cues that may change self-evaluation even without adding factual content.</p>
<p>Attitudes are another form of integration. They are neither factual scores nor purely private preferences. In a sociotechnical controversy, attitudes combine factual information, values, and norms. Persuasion models distinguish argument quality from source cues (Chaiken, 1980; Petty &amp; Cacioppo, 1986). A sequence may therefore change attitudes without reproducing the profile of a factual inventory. The direction of change can also be informative when some items concern domains in which scientific evidence and assessment frameworks have evolved, but an attitude score should never be treated as a global truth score.</p>
<p>H2 - Differentiated outcomes. Factual knowledge, subjective knowledge, and attitudes should follow different trajectories across the protocol. We therefore examine each outcome over the first period (T1-to-T2), the common-baseline interval (T1-to-T3), and the second period (T2-to-T3). The factual profile should not be reproduced identically by subjective knowledge or attitudes, and individual changes across these dimensions should remain weakly coupled without assuming strict independence.</p>
</section>
<section id="human-sources-transactive-memory-social-comparison-and-epistemic-credit" class="level3">
<h3 class="anchored" data-anchor-id="human-sources-transactive-memory-social-comparison-and-epistemic-credit">2.5. Human sources: transactive memory, social comparison, and epistemic credit</h3>
<p>When knowledge is carried by present people, learners must also locate expertise socially. Transactive-memory theory frames this requirement as a representation of who knows what (Wegner, 1987; Hollingshead, 2000). Collaborative Cognitive Load Theory poses a related problem through mutual cognitive interdependence (Janssen &amp; Kirschner, 2020). The presence of knowledge in a group therefore guarantees neither its recognition nor its use.</p>
<p>This coordination is sensitive to social goals. Cooperation can make another person's competence useful to one's own success, whereas competitive interdependence can make relative standing more salient (Johnson &amp; Johnson, 2009). More specifically, competence comparisons can become threatening depending on the structure of resource interdependence (Buchs &amp; Butera, 2009). Motivated information processing and sociocognitive-conflict research likewise show that social goals change how information and disagreement are regulated (De Dreu et al., 2008; Darnon et al., 2006, 2007). Sociality is not opposed to knowledge. It can become a powerful route to knowledge when relationships make competence visible and reward accuracy. It can also shift attention toward ranking, self-defense, or relationship management.</p>
<p>In MOVICI, the cooperative or competitive framing was announced before search. It could therefore shape expectations during the document-based phase. Only during debate, however, did the source become fully reciprocal: a partner spoke, responded, judged, and became an object of judgment. If structural and interactional embedding differ as proposed by CAVL, the condition should affect epistemic credit more strongly for human sources than for recalled Web sources. The same logic predicts better self-calibration when others' competence can function as a cooperative reference rather than a relative threat.</p>
<p>H3 - Interactional reconfiguration. The cooperation/competition condition should be more strongly associated with epistemic credit when the evaluated source is human than when it is document-based. Cooperation should also be associated with better calibration between objective and subjective knowledge after the interactional sequence.</p>
</section>
<section id="complementary-analysis-and-the-human-epistemic-bottleneck" class="level3">
<h3 class="anchored" data-anchor-id="complementary-analysis-and-the-human-epistemic-bottleneck">2.6. Complementary analysis and the human epistemic bottleneck</h3>
<p>CAVL also proposes a more specific relation between prior knowledge and attributed authority. When learners have little valid knowledge for direct content evaluation, source cues may carry more weight; as expertise increases, direct evaluation becomes more accessible (Vayre et al., 2026c). Complementary analysis C1 therefore tests whether the Web-credit association with T2 varies with T1 factual knowledge. This is not one of the three central comparative hypotheses.</p>
<p>Transactive memory and CCLT lead to a distinct research question. For knowledge in other people to become a resource, at least two transitions are required. First, measured factual knowledge must be recognized as expertise. Second, the knowledge available in partners must be associated with the learner's final state. We test this possible bottleneck using partners' T2 factual scores, measured before debate.</p>
<p>RQ1 - Human epistemic bottleneck. To what extent is factual knowledge available in partners before debate (a) recognized through perceived expertise and (b) associated with the evaluator's final factual knowledge? We also examine whether the evaluator's own factual knowledge improves recognition, whether human epistemic credit predicts T3 beyond the evaluator's own T2, and whether results change when the highest-scoring partner rather than the mean partner score is used.</p>
<p>Table 1. Summary of predictions and analyses.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 44%">
<col style="width: 37%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Block</strong></th>
<th style="text-align: left;"><strong>Central question</strong></th>
<th style="text-align: left;"><strong>Primary test</strong></th>
<th style="text-align: left;"><strong>Status</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">Do the two periods show the same factual transformation?</td>
<td style="text-align: left;">Within-person T1-T2, T1-T3, and T2-T3 change; variance ratios</td>
<td style="text-align: left;">Main hypothesis</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Do factual, subjective, and attitudinal outcomes follow the same trajectory?</td>
<td style="text-align: left;">T1-T2, T1-T3, and T2-T3 mean change; dispersion; associations among changes</td>
<td style="text-align: left;">Main hypothesis</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Are credit and calibration more sensitive to social structure with a human source?</td>
<td style="text-align: left;">Source type x condition; T3 calibration error adjusted for T2</td>
<td style="text-align: left;">Main hypothesis</td>
</tr>
<tr class="even">
<td style="text-align: left;">C1</td>
<td style="text-align: left;">Does initial factual knowledge moderate the Web-credit association with T2?</td>
<td style="text-align: left;">T1 x Web credit, controlling SES and condition</td>
<td style="text-align: left;">Complementary</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RQ1</td>
<td style="text-align: left;">Is factual knowledge available in others recognized and transformed into an individual resource?</td>
<td style="text-align: left;">Partner T2 -&gt; perceived expertise; partner knowledge -&gt; T3; human credit -&gt; T3</td>
<td style="text-align: left;">Research question</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">3. Method</h2>
<section id="participants-and-design" class="level3">
<h3 class="anchored" data-anchor-id="participants-and-design">3.1. Participants and design</h3>
<p>The analytic sample comprised 96 participants recruited in the Université Côte d'Azur environment: 94 students and two recent graduates. Age ranged from 18 to 42 years (M = 20.45, SD = 3.41). The sample included 62 women and 34 men. Forty-nine participants were in the cooperative condition and 47 in the competitive condition. The 96 participants were distributed across 34 debates, which were used as clusters for participant-level inference.</p>
<p>Condition allocation followed participant enrolment and session-entry order rather than strict random assignment. Debate groups were then composed with reference to T1 attitudes so as to favor, where feasible, diversity of initial positions within each discussion. This procedure was intended to preserve the possibility of genuine disagreement on the controversy. Because condition allocation was not strictly randomized, condition coefficients are interpreted as associations under an experimentally manipulated framing rather than as pure randomized causal effects.</p>
<p>Baseline checks showed no clear condition differences in T1 factual knowledge (standardized b = -0.065, p = .750), T1 subjective knowledge (b = 0.177, p = .336), or family SES (b = -0.035, p = .860). The global T1 attitude score was somewhat more negative in cooperation (standardized b = -0.372, p = .059); none of the four attitude subscales differed clearly between conditions.</p>
<p>The protocol received a favorable opinion from the Université Côte d'Azur Research Ethics Committee on March 9, 2024 (file no. 2024-037). All participants received written information and provided free and informed consent. Sessions took place at the CoCoLab of Université Côte d'Azur. Announced compensation included EUR 20 fixed plus up to EUR 10 variable by condition; all participants ultimately received EUR 30.</p>
</section>
<section id="procedure-parallel-structure-and-ecological-validity" class="level3">
<h3 class="anchored" data-anchor-id="procedure-parallel-structure-and-ecological-validity">3.2. Procedure, parallel structure, and ecological validity</h3>
<p>One to several weeks before the laboratory session, participants completed a pre-questionnaire containing the first factual-knowledge test (T1), subjective knowledge, and attitudes. At the laboratory, the cooperative or competitive framing of the upcoming debate was announced before search.</p>
<p>Participants then had approximately 20 minutes to search the Web freely for information about animal-protein consumption. They formulated their own queries and selected their own tools and sources. After search, they recalled and evaluated sources, then recalled and evaluated arguments. The second factual test (T2), subjective knowledge, and attitudes were administered after this sequence and before any discussion.</p>
<p>The debate lasted approximately 20 minutes and involved two to four participants. In the competitive condition, participants were instructed to convince others of the accuracy and merits of their own position, and individual persuasive performance was announced as the evaluation target. In the cooperative condition, the goal was to improve knowledge collectively and build areas of agreement, with group performance announced as the evaluation target. After debate, each participant evaluated partners, then recalled and evaluated their arguments using a structure parallel to the post-search sequence. Participants then reassessed their own knowledge and attitudes and completed T3.</p>
<p>MOVICI deliberately balances experimental comparability with ecological validity. The two sequences share a parallel post-activity structure: source or partner evaluation, followed by argument recall/evaluation and post-sequence measures. Their constitutive properties are not artificially made identical. In open Web search, learners choose queries, tools, and sources. In debate, partners are given by group composition and become reciprocal sources. Making the environments fully isomorphic would remove the selection processes that characterize search and the reciprocity that characterizes interaction. This design choice follows ecological-validity and representative-design arguments that experimental tasks should preserve functionally relevant features of the environments to which they are meant to speak (Brunswik, 1956; Schmuckler, 2001; Cicourel, 2007). It supports ecological plausibility, but does not by itself guarantee broad external validity.</p>
<p>Thus, T1-to-T2 covers search -&gt; recall/evaluation -&gt; measurement, and T2-to-T3 covers debate -&gt; recall/evaluation -&gt; measurement. The parallel processing structure strengthens comparability. It does not identify a pure causal effect of search or debate because each period is composite and the order is fixed. Because environment type and sequence position are perfectly confounded, no statistical adjustment can identify an order-independent document-versus-interaction effect in this design. T1-to-T3 analyses provide a common-baseline description of the final state; they do not neutralize the order effect.</p>
<p>Table 2. Experimental sequence and measures.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 22%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Stage</strong></th>
<th style="text-align: left;"><strong>Activity</strong></th>
<th style="text-align: left;"><strong>Post-activity processing</strong></th>
<th style="text-align: left;"><strong>Measures</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">T1</td>
<td style="text-align: left;">Pre-questionnaire</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Factual knowledge, subjective knowledge, attitudes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Document-based sequence</td>
<td style="text-align: left;">Open Web search (~20 min)</td>
<td style="text-align: left;">Source evaluation; argument recall and evaluation</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T2</td>
<td style="text-align: left;">Post-document sequence assessment</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Factual knowledge, subjective knowledge, attitudes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Interactional sequence</td>
<td style="text-align: left;">COOP or COMP debate (~20 min)</td>
<td style="text-align: left;">Partner evaluation; argument recall and evaluation</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T3</td>
<td style="text-align: left;">Post-interaction sequence assessment</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">Factual knowledge, subjective knowledge, attitudes</td>
</tr>
</tbody>
</table>
</section>
<section id="measures" class="level3">
<h3 class="anchored" data-anchor-id="measures">3.3. Measures</h3>
<section id="factual-knowledge" class="level4">
<h4 class="anchored" data-anchor-id="factual-knowledge">3.3.1. Factual knowledge</h4>
<p>Factual knowledge was measured with a 20-item inventory developed for MOVICI. Each correct response scored 1; incorrect, 'I do not know', and missing responses scored 0. The same inventory was administered at T1, T2, and T3, with question and response-option order randomized. The score is treated as an inventory of factual knowledge relevant to the controversy, not as a unidimensional scale of general expertise.</p>
</section>
<section id="subjective-knowledge-and-calibration" class="level4">
<h4 class="anchored" data-anchor-id="subjective-knowledge-and-calibration">3.3.2. Subjective knowledge and calibration</h4>
<p>Subjective knowledge was self-rated from 1 ('very low') to 4 ('very high') at T1, T2, and T3. For calibration analyses, objective and subjective scores were standardized within time. Absolute calibration error was defined as |z(subjective knowledge) - z(factual knowledge)|. It captures the magnitude of mismatch without conflating magnitude with the direction of bias.</p>
</section>
<section id="attitudes" class="level4">
<h4 class="anchored" data-anchor-id="attitudes">3.3.3. Attitudes</h4>
<p>Eight attitude items, rated from -4 ('strongly against') to +4 ('strongly in favor'), formed four canonical subscales: SSA (science, health, and consumption), VAHC (animal-use and consumption practices), VASA (animal suffering and slaughter), and EP (environment and political regulation). Analytic variables retain the canonical directional scoring. Under this scoring, the global total has a theoretical range from -42 to +22. More negative global values broadly indicate a more critical position toward animal-protein consumption/uses and/or stronger support for animal protection and environmental regulation. Subscales are interpreted according to their own direction.</p>
</section>
<section id="document-based-and-human-epistemic-credit" class="level4">
<h4 class="anchored" data-anchor-id="document-based-and-human-epistemic-credit">3.3.4. Document-based and human epistemic credit</h4>
<p>After search, recalled Web sources were evaluated on two dimensions: expertise/competence and benevolence/honesty. A participant-level mean was computed for each dimension. For cross-environment comparison, the dimensions were standardized within environment and averaged into document-based epistemic credit. This indicator describes evaluations of retained sources; it does not measure their objective quality or claim-by-claim uptake.</p>
<p>After debate, participants evaluated each partner on parallel dimensions of expertise and benevolence, then recalled and evaluated partner arguments. For comparison with Web sources, partner evaluations were aggregated at evaluator level, standardized, and averaged into human epistemic credit. Dyadic RQ1 analyses retain each evaluator-partner relation. The dyadic dataset contains 212 ordered relations; 196 have perceived-expertise data and involve 91 evaluators across 29 debates.</p>
<p>The two credit indicators use parallel evaluative dimensions, but their source sets are not generated in the same way. Web sources are self-selected and then recalled; human partners are determined by debate composition and become reciprocal. The comparison therefore concerns common dimensions of epistemic credit in two ecologically different environments, not strictly isomorphic source sets. Argument processing is more closely parallel: in both sequences, participants recalled arguments actually encountered during the activity and then evaluated them.</p>
</section>
</section>
<section id="analysis-strategy" class="level3">
<h3 class="anchored" data-anchor-id="analysis-strategy">3.4. Analysis strategy</h3>
<p>The study was not preregistered. H1-H3 are theory-guided predictions derived from CAVL and established literatures on document learning, distributed cognition, collaborative cognitive load, transactive memory, metacognition, and epistemic vigilance. They should be read as non-preregistered theory-guided tests, not as preregistered confirmatory tests. Inference uses CR2 cluster-robust standard errors with Satterthwaite degrees of freedom, clustering by debate (Pustejovsky &amp; Tipton, 2018). Continuous predictors are standardized within the relevant analytic sample when required.</p>
<p>For H1, we estimate factual change from T1 to T2, the common-baseline change from T1 to T3, and incremental change from T2 to T3. We also estimate the direct within-person contrast between the two adjacent changes. Dispersion is compared with the Pitman-Morgan test for paired measures, and cluster bootstrap is used for direct contrasts in log variance ratios. Distribution diagnostics check for floor or ceiling compression. For T2-to-T3 change, one-sided sensitivity tests compare the estimate with candidate positive gains from +0.10 to +1.00 points.</p>
<p>For H2, the same temporal logic is applied to subjective knowledge and attitudes: T1-to-T2, T1-to-T3, and T2-to-T3 mean changes are estimated, together with the direct contrast between the two adjacent periods. Dispersion is assessed for all three pairwise intervals with Pitman-Morgan tests. Cluster bootstrap compares factual dispersion change with subjective-knowledge and attitude dispersion over both T1-to-T2 and T1-to-T3. The four attitude subscales are tested for T1-to-T2, T1-to-T3, T2-to-T3, and the adjacent-period contrast, with Benjamini-Hochberg correction within each predefined family. Associations among factual, subjective, and attitudinal changes are examined separately for T1-to-T2, T1-to-T3, and T2-to-T3 using correlations and standardized CR2 slopes. Post hoc equivalence sensitivity uses symmetric standardized bounds of +/-0.10, +/-0.20, and +/-0.30; these are sensitivity benchmarks, not preregistered smallest effects of interest.</p>
<p>For H3, a long dataset compares standardized document-based and human credit. The primary test is the source-type x condition interaction. Secondary analyses separate expertise and benevolence. A sensitivity model adds the number of recalled Web sources, and a stronger model also allows its association to differ by source type. Post-interaction calibration is modeled as T3 error adjusted for T2 error and condition. Objective knowledge x condition at T3 is used as a diagnosticity analysis.</p>
<p>C1 tests T1 x Web credit in a T2 model controlling SES and condition. RQ1 uses partners' T2 factual knowledge measured before debate. We test whether partner knowledge predicts perceived expertise, whether evaluator knowledge moderates recognition, whether mean partner knowledge predicts T3 beyond own T2, and whether human credit predicts T3. Robustness analyses replace mean partner knowledge with the highest-scoring partner, the highest-scoring partner's advantage over the evaluator, mean partner advantage, and the proportion of partners scoring above the evaluator. Post hoc equivalence sensitivity is applied to the two central near-zero RQ1 links.</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">4. Results</h2>
<section id="baseline-balance" class="level3">
<h3 class="anchored" data-anchor-id="baseline-balance">4.1. Baseline balance</h3>
<p>The two conditions were similar at baseline on factual knowledge, subjective knowledge, and family SES. The global attitude score was descriptively more negative in cooperation (Competition M = -20.66, Cooperation M = -24.14; standardized b = -0.372, p = .059), while no attitude subscale showed a clear condition difference. These checks do not substitute for randomization, but they indicate no large baseline separation on the central knowledge variables.</p>
</section>
<section id="h1---different-factual-trajectories-across-the-protocol" class="level3">
<h3 class="anchored" data-anchor-id="h1---different-factual-trajectories-across-the-protocol">4.2. H1 - Different factual trajectories across the protocol</h3>
<p>Mean factual scores were 9.00/20 at T1 (SD = 3.21), 10.40 at T2 (SD = 2.14), and 10.17 at T3 (SD = 2.48). From T1 to T2, the mean increase was 1.396 points, 95% CI [0.755, 2.036], p &lt; .001. Relative to the same T1 baseline, the final T3 score remained 1.167 points higher, 95% CI [0.503, 1.831], p = .0012. Thus, the factual difference visible after the first period remained clearly present at protocol end.</p>
<p>Incremental change from T2 to T3 was -0.229 points, 95% CI [-0.567, 0.109], p = .176. The one-sided 95% upper bound was +0.052 points. Candidate positive gains of +0.10, +0.25, +0.50, and +1.00 points were rejected; for +0.10, p = .028. On this metric, the interactional period was therefore not compatible with a mean positive gain of at least +0.10 points. The direct within-person contrast, (T3-T2) - (T2-T1), was -1.625 points, 95% CI [-2.405, -0.845], p &lt; .001.</p>
<p>Score dispersion changed in the same asymmetric way. Variance fell from 10.29 at T1 to 4.60 at T2, a 55.3% reduction, Pitman-Morgan p &lt; .001. At T3, variance was 6.14: still 40.4% below T1, p = .0051, but 33.5% higher than at T2, p = .0146. Thus, the strong homogenization of observed factual scores after the first period was only partly reversed after the second. Distribution diagnostics showed no ceiling compression: maxima were 16, 15, and 16 at T1, T2, and T3, respectively, and only one participant was at the floor at T1.</p>
<p>Pre-post rank continuity was also stronger in the second period. In the stacked standardized model, the pre-post slope was .494 for T1-to-T2 and increased by .331 for T2-to-T3, interaction p = .0018. T3 therefore remained strongly anchored in the level reached at T2.</p>
</section>
<section id="h2---factual-subjective-and-attitudinal-trajectories-differ-across-t1-t2-and-t3" class="level3">
<h3 class="anchored" data-anchor-id="h2---factual-subjective-and-attitudinal-trajectories-differ-across-t1-t2-and-t3">4.3. H2 - Factual, subjective, and attitudinal trajectories differ across T1, T2, and T3</h3>
<p>Subjective knowledge showed a gradual cumulative increase rather than the factual profile. The T1-to-T2 increase was 0.115 points, 95% CI [-0.008, 0.237], p = .066. Relative to the same baseline, subjective knowledge was 0.198 points higher at T3, 95% CI [0.063, 0.333], p = .0056. The incremental T2-to-T3 increase was 0.083 points, 95% CI [0.002, 0.164], p = .044. The two adjacent-period changes did not differ directly, p = .688. Thus, unlike factual knowledge, subjective knowledge did not show a sharp first-period increase followed by no additional gain; instead, it increased modestly across the protocol.</p>
<p>Attitudes also showed a cumulative trajectory, but with a larger first-period shift. The global score decreased by 3.260 points from T1 to T2, 95% CI [-4.733, -1.788], p &lt; .001, and by 4.281 points from T1 to T3, 95% CI [-5.746, -2.816], p &lt; .001. The additional T2-to-T3 decrease was 1.021 points, 95% CI [-1.843, -0.199], p = .0167. Under the canonical scoring, lower values broadly indicate more critical positions toward animal-protein consumption/uses and/or greater support for animal protection and environmental regulation. The first adjacent-period change was larger: the second-minus-first contrast was +2.240 points, 95% CI [0.357, 4.122], p = .0214.</p>
<p>Subscales refined this cumulative pattern. From T1 to T2, SSA decreased by 1.406 points (q = .0010) and EP by 1.229 points (q = .0010). From T1 to T3, SSA remained lower by 1.750 points (q = .00118) and EP by 1.625 points (q &lt; .001), whereas VAHC and VASA did not show corrected changes. During T2-to-T3, only EP showed a robust corrected decrease (-0.396, q = .0087). Direct adjacent-period contrasts for SSA and EP were nominal but just above the adjusted threshold (q approximately .059). The durable global attitude shift was therefore concentrated mainly in SSA and EP.</p>
<p>Dispersion profiles also differed across outcomes. From T1 to T2, subjective-knowledge variance decreased by 24.4% (p = .121) and attitude variance by 19.6% (p = .152), compared with a 55.3% reduction in factual-score variance. Cluster bootstrap confirmed that the T1-to-T2 factual reduction was larger than the reductions for subjective knowledge (difference in log variance ratios = -0.526, 95% CI [-0.989, -0.062]) and attitudes (-0.587, 95% CI [-1.076, -0.176]). From T1 to T3, subjective-knowledge variance was 25.7% lower (p = .117) and attitude variance 17.0% lower (p = .175). Factual variance remained 40.4% below baseline, but its relative reduction was no longer clearly distinguishable from the T1-to-T3 reductions in subjective knowledge (bootstrap difference = -0.220, 95% CI [-0.654, 0.221]) or attitudes (-0.331, 95% CI [-0.775, 0.109]).</p>
<p>Individual changes remained weakly coupled. For T1-to-T2, CR2 standardized slopes were beta = .100 for factual-to-subjective change, beta = -.105 for factual-to-attitude change, and beta = -.060 for subjective-to-attitude change; none was significant. Across the full T1-to-T3 interval, factual and subjective change showed a small positive association, beta = .185, 95% CI [0.001, 0.370], p = .049, whereas factual-to-attitude (beta = .049, p = .667) and subjective-to-attitude change (beta = -.077, p = .342) remained weak. T2-to-T3 couplings were likewise weak and non-significant. Given the borderline T1-to-T3 factual-subjective result and the post hoc equivalence analyses, these findings are best interpreted as weak coupling rather than evidence of independence or a robust common change factor.</p>
</section>
<section id="h3---human-credit-and-calibration-are-more-sensitive-to-social-structure" class="level3">
<h3 class="anchored" data-anchor-id="h3---human-credit-and-calibration-are-more-sensitive-to-social-structure">4.4. H3 - Human credit and calibration are more sensitive to social structure</h3>
<p>The primary model compared standardized epistemic credit for recalled Web sources and human partners. The source-type x condition interaction was positive, b = 1.019 SD, SE = 0.290, 95% CI [0.422, 1.616], p = .00165. Cooperation/competition was therefore much more strongly associated with credit when the evaluated source was a human partner than when it was a recalled Web source.</p>
<p>The result held for both components. For expertise/competence, the human-source x cooperation interaction was b = 0.760, 95% CI [0.145, 1.376], p = .0174. For benevolence/honesty, it was b = 1.068, 95% CI [0.519, 1.618], p &lt; .001. Among the 85 participants with both evaluations, the human-minus-Web contrast was -0.645 SD under competition, p = .020, and was 1.124 SD larger under cooperation, p = .0010.</p>
<p>The interaction was virtually unchanged after accounting for the number of recalled Web sources: b = 1.004, 95% CI [0.398, 1.611], p = .0022. In the stronger sensitivity model that also allowed recalled-source count to differ by source type, the interaction was b = 1.040, 95% CI [0.387, 1.694], p = .0030. Recalled-source count itself did not show a clear association with credit in the first sensitivity model (p = .221). The H3 result therefore does not appear to be explained by how many Web sources a participant recalled.</p>
<p>Self-calibration showed a parallel pattern. T2 calibration error predicted T3 error, b = 0.466, p = .0013, but at equal T2 error, cooperation was associated with 0.351 lower T3 error, 95% CI [-0.601, -0.100], p = .0079. Raw error increased by 0.181 under competition, p = .030; the difference in raw change between conditions was marginal, p = .060. The longitudinal model is therefore the main test.</p>
<p>At T3, self-evaluation diagnosticity also differed by condition. Under competition, the slope linking factual and subjective knowledge was near zero, b = -0.016, p = .917. The objective-knowledge x cooperation interaction was b = 0.562, 95% CI [0.190, 0.933], p = .00535. A similar difference was already suggestive at T2 (interaction b = 0.408, p = .056), and the objective x condition x time interaction was not significant (b = 0.153, p = .347). We therefore do not claim that debate alone created the diagnosticity difference.</p>
</section>
<section id="c1---document-based-credit-and-initial-factual-knowledge" class="level3">
<h3 class="anchored" data-anchor-id="c1---document-based-credit-and-initial-factual-knowledge">4.5. C1 - Document-based credit and initial factual knowledge</h3>
<p>In the model controlling T1, SES, and condition, Web credit remained positively associated with T2, b = 0.452 points per SD, 95% CI [0.074, 0.829], p = .0219. The T1 x Web-credit interaction was not supported, b = -0.315, 95% CI [-0.723, 0.092], p = .116.</p>
<p>Simple slopes followed the CAVL-predicted gradient: b = 0.767 at -1 SD of T1 (p = .004), b = 0.452 at the mean (p = .022), and b = 0.136 at +1 SD (p = .657). Because the interaction was not significant, this gradient remains descriptive. The study supports a general Web-credit association with T2, but not formal moderation by initial factual knowledge.</p>
</section>
<section id="rq1---does-factual-knowledge-available-in-others-become-a-learning-resource" class="level3">
<h3 class="anchored" data-anchor-id="rq1---does-factual-knowledge-available-in-others-become-a-learning-resource">4.6. RQ1 - Does factual knowledge available in others become a learning resource?</h3>
<p>At the dyadic level, a partner's T2 factual score was only weakly related to the expertise attributed to that partner: b = -0.168, 95% CI [-0.849, 0.514], p = .607, N = 196 relations in 29 debates. On a standardized metric, beta = -0.036, SE = 0.069, 95% CI [-0.183, 0.111]. Post hoc equivalence was not established within +/-0.10 (p = .184), but was established within +/-0.20 (p = .0155) and +/-0.30 (p &lt; .001). The evaluator's own factual knowledge did not improve this recognition relation, interaction b = -0.090, p = .783.</p>
<p>At evaluator level, mean partner T2 factual knowledge was also only weakly related to T3 after control for the evaluator's own T2: b = -0.013, 95% CI [-0.345, 0.320], p = .935, N = 91. The standardized effect was beta = -0.005, 95% CI [-0.139, 0.129]. Equivalence was not established within +/-0.10 (p = .074), but was established within +/-0.20 (p = .0039) and +/-0.30 (p &lt; .001). By contrast, the evaluator's own T2 strongly predicted T3 (standardized beta = .830, p &lt; .001).</p>
<p>Robustness analyses showed that the near-zero result was not an artifact of averaging partners. The highest-scoring partner's T2 factual knowledge was not positively associated with T3 after own T2 was controlled, b = -0.176, 95% CI [-0.466, 0.113], p = .211. The factual-knowledge advantage of that highest-scoring partner over the evaluator was likewise not associated with T3, b = -0.305, 95% CI [-0.805, 0.196], p = .211, and did not predict T2-to-T3 change (same coefficient and p value). Mean partner advantage was near zero, p = .935, and the proportion of partners scoring above the evaluator was also unrelated to T3, p = .607. Thus, the result does not appear to arise because a group mean hides one particularly knowledgeable partner.</p>
<p>Finally, human epistemic credit had a positive but uncertain association with T3 after own T2 was controlled, b = 0.254, 95% CI [-0.067, 0.574], p = .113, N = 89. We did not test equivalence for this relation because the positive signal remained compatible with a non-negligible effect. RQ1 therefore does not demonstrate an absence of local transmission during debate. It shows more specifically that measured factual knowledge available in partners was neither well recognized nor reliably associated with the evaluator's final factual level on the global measures used here.</p>
<p>Table 3. Main results.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 33%">
<col style="width: 20%">
<col style="width: 14%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Block</strong></th>
<th style="text-align: left;"><strong>Analysis</strong></th>
<th style="text-align: left;"><strong>Estimate</strong></th>
<th style="text-align: left;"><strong>p / equivalence</strong></th>
<th style="text-align: left;"><strong>Interpretation</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">Factual change T1-T2</td>
<td style="text-align: left;">+1.396 [0.755, 2.036]</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">Increase</td>
</tr>
<tr class="even">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">Factual change T1-T3</td>
<td style="text-align: left;">+1.167 [0.503, 1.831]</td>
<td style="text-align: left;">.0012</td>
<td style="text-align: left;">Increase remains at protocol end</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">Incremental factual change T2-T3</td>
<td style="text-align: left;">-0.229 [-0.567, 0.109]</td>
<td style="text-align: left;">.176</td>
<td style="text-align: left;">No substantial positive gain</td>
</tr>
<tr class="even">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">Variance T1-T2</td>
<td style="text-align: left;">-55.3%</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">Strong score homogenization</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H1</td>
<td style="text-align: left;">Variance T1-T3</td>
<td style="text-align: left;">-40.4%</td>
<td style="text-align: left;">.0051</td>
<td style="text-align: left;">Homogenization partly maintained</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Subjective change T1-T3</td>
<td style="text-align: left;">+0.198 [0.063, 0.333]</td>
<td style="text-align: left;">.0056</td>
<td style="text-align: left;">Gradual cumulative increase</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Global attitude change T1-T2</td>
<td style="text-align: left;">-3.260 [-4.733, -1.788]</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">Robust change</td>
</tr>
<tr class="even">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Global attitude change T1-T3</td>
<td style="text-align: left;">-4.281 [-5.746, -2.816]</td>
<td style="text-align: left;">&lt; .001</td>
<td style="text-align: left;">Cumulative change maintained</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H2</td>
<td style="text-align: left;">Global attitude change T2-T3</td>
<td style="text-align: left;">-1.021 [-1.843, -0.199]</td>
<td style="text-align: left;">.0167</td>
<td style="text-align: left;">Smaller additional change</td>
</tr>
<tr class="even">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Human source x cooperation, credit</td>
<td style="text-align: left;">+1.019 SD [0.422, 1.616]</td>
<td style="text-align: left;">.00165</td>
<td style="text-align: left;">Supported</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Same interaction + recalled-source count</td>
<td style="text-align: left;">+1.004 SD [0.398, 1.611]</td>
<td style="text-align: left;">.0022</td>
<td style="text-align: left;">Robust</td>
</tr>
<tr class="even">
<td style="text-align: left;">H3</td>
<td style="text-align: left;">Cooperation -&gt; T3 calibration error, adjusted for T2</td>
<td style="text-align: left;">-0.351 [-0.601, -0.100]</td>
<td style="text-align: left;">.0079</td>
<td style="text-align: left;">Better calibration</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C1</td>
<td style="text-align: left;">T1 x Web credit -&gt; T2</td>
<td style="text-align: left;">-0.315 [-0.723, 0.092]</td>
<td style="text-align: left;">.116</td>
<td style="text-align: left;">Moderation not supported</td>
</tr>
<tr class="even">
<td style="text-align: left;">RQ1</td>
<td style="text-align: left;">Partner factual knowledge -&gt; perceived expertise</td>
<td style="text-align: left;">beta = -0.036 [-0.183, 0.111]</td>
<td style="text-align: left;">equiv. +/-0.20: .0155</td>
<td style="text-align: left;">At most small association</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RQ1</td>
<td style="text-align: left;">Mean partner factual knowledge -&gt; T3 | own T2</td>
<td style="text-align: left;">beta = -0.005 [-0.139, 0.129]</td>
<td style="text-align: left;">equiv. +/-0.20: .0039</td>
<td style="text-align: left;">At most small association</td>
</tr>
<tr class="even">
<td style="text-align: left;">RQ1</td>
<td style="text-align: left;">Highest-scoring partner -&gt; T3 | own T2</td>
<td style="text-align: left;">-0.176 [-0.466, 0.113]</td>
<td style="text-align: left;">.211</td>
<td style="text-align: left;">Robustness also null</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">5. Discussion</h2>
<section id="external-representations-can-support-domain-knowledge-without-removing-the-social" class="level3">
<h3 class="anchored" data-anchor-id="external-representations-can-support-domain-knowledge-without-removing-the-social">5.1. External representations can support domain knowledge without removing the social</h3>
<p>The first result is an asymmetric factual trajectory. Factual scores increased markedly from T1 to T2 and became much less dispersed. At T3, the score remained clearly above T1 and dispersion remained substantially below baseline. The second period therefore did not erase the earlier transformation. It added no positive mean factual gain, but it partially re-differentiated trajectories. This is not evidence that 'digital learning is better than human learning.' The order was fixed, the periods were composite, and T1 was temporally more distant from T2 than T2 from T3. The result is better read as a difference in the transformations observed across a sequential protocol.</p>
<p>The pattern nevertheless highlights the cognitive value of stable external representations. Writing, books, and digital systems preserve socially produced information beyond the interaction in which it emerged (Donald, 1991). Learners can revisit and compare such representations without depending on a partner's immediate memory or social position. In MOVICI, the first period may have supported factual change because relevant information was selectable and revisitable. This remains a theoretical interpretation because interactional load was not directly measured.</p>
<p>The strong T1-to-T2 reduction in observed score variance, together with the absence of floor or ceiling compression, is compatible with a meaningful homogenization of factual performance. We deliberately describe this as homogenization of observed scores rather than as direct proof that latent knowledge became equally distributed. At T3, much of that homogenization remained. The interactional period therefore appears less as a reversal of learning than as a period in which factual rank differences became more pronounced again.</p>
</section>
<section id="human-interaction-can-amplify-learning-when-social-and-epistemic-processes-align" class="level3">
<h3 class="anchored" data-anchor-id="human-interaction-can-amplify-learning-when-social-and-epistemic-processes-align">5.2. Human interaction can amplify learning when social and epistemic processes align</h3>
<p>The absence of an additional mean factual gain during the second period does not make debate cognitively sterile. Human interaction can be a powerful amplifier. It enables explanation, challenge, correction, and pooling of resources. Cooperative-learning meta-analyses and ICAP document this potential (Kyndt et al., 2013; Chi &amp; Wylie, 2014). CCLT clarifies its condition: the benefit of collective working memory must exceed transaction costs, and members must know where useful expertise resides (Janssen et al., 2010; Kirschner et al., 2018; Janssen &amp; Kirschner, 2020). When these conditions hold, social interaction and knowledge can reinforce one another. When they do not, interaction can remain rich in argumentation or relation regulation without producing the same immediate factual increase.</p>
<p>Metacognition illustrates this differentiated temporal profile. Subjective knowledge was only weakly higher at T2 but was clearly higher at T3 relative to T1, indicating a gradual cumulative increase across the protocol. At comparable T2 calibration error, cooperation was also associated with lower error at T3. Under cooperation, subjective knowledge tracked factual knowledge more strongly; under competition, the relation was close to zero. Other people can therefore provide information about one's own epistemic position, but the diagnostic value of that information depends on social structure. This is consistent with social-comparison theory (Festinger, 1954) and with evidence that competitive versus cooperative mindsets moderate the effects of social comparison on self-evaluation (Colpaert et al., 2015).</p>
<p>Attitudes add another layer. Their global shift accumulated across the protocol: the score was 3.260 points lower at T2 and 4.281 points lower at T3 relative to T1, with the larger adjacent-period change occurring before T2. The durable T1-to-T3 change was concentrated mainly in SSA and EP. Its direction is not epistemically arbitrary: several items moved toward lower endorsement of some animal-protein consumption practices, stronger animal-protection orientations, and greater environmental regulation. These directions are partly congruent with contemporary evidence concerning health risks associated with red and processed meat and food-system environmental impacts, and with established frameworks for animal-welfare assessment (Bouvard et al., 2015; Poore &amp; Nemecek, 2018; Clark et al., 2020; Mellor et al., 2020). The attitude score is not a truth score, however. Some items include normative judgments, and no global position is scientifically univocal. The temporal asymmetry therefore raises, rather than resolves, the possibility that stabilized document-based representations and immediate social exchange support different forms of attitude revision. Because environment and sequence position are confounded, the present design cannot attribute that asymmetry to source environment independently of order.</p>
</section>
<section id="moving-from-documents-to-interlocutors-adds-an-epistemic-coordination-bottleneck" class="level3">
<h3 class="anchored" data-anchor-id="moving-from-documents-to-interlocutors-adds-an-epistemic-coordination-bottleneck">5.3. Moving from documents to interlocutors adds an epistemic-coordination bottleneck</h3>
<p>The most distinctive result concerns epistemic credit. Cooperation/competition was much more strongly associated with evaluations of human partners than with recalled Web sources. This interaction remained almost unchanged after the number of recalled Web sources was controlled. The result therefore appears robust to a simple difference in document-search breadth. It should not be treated as an ontological property of 'humans versus documents.' The two environments differ in reciprocity and in how sources are selected. The finding is better stated as follows: within these ecologically distinct activities, human credit was far more sensitive to relational structure.</p>
<p>That non-isomorphism is partly a feature of the design, not only a limitation. Search normally includes source selection and abandonment. Discussion normally includes copresence, reciprocity, and less control over who speaks. MOVICI standardizes operations that can reasonably be standardized - especially the post-activity recall/evaluation structure - while preserving mechanisms that constitute the activities themselves. This compromise is important for ecological validity (Brunswik, 1956; Schmuckler, 2001; Cicourel, 2007).</p>
<p>Transactive memory and CCLT identify the functional problem. To benefit from distributed knowledge, a group must know sufficiently well who knows what (Wegner, 1987; Hollingshead, 2000; Janssen &amp; Kirschner, 2020). Yet partners' measured factual knowledge was only weakly related to the expertise attributed to them. Mean partner knowledge was also only weakly related to T3 once the evaluator's own T2 was controlled. Importantly, the same conclusion held when the highest-scoring partner and the highest-scoring partner's knowledge advantage were examined. The result is therefore not simply an artifact of averaging several partners.</p>
<p>This bottleneck does not make human interaction inferior. It identifies a condition of its power. A document can be reinspected once selected. In a group, useful knowledge may exist without being functionally accessible if learners do not identify who holds it, do not grant that person appropriate credit, or must manage competing relational demands. When measured competence, recognition, epistemic credit, and social goals align, distributed knowledge can become an exceptionally efficient collective resource. When they do not, part of that potential remains unused.</p>
</section>
<section id="what-the-comparison-contributes-to-cavl" class="level3">
<h3 class="anchored" data-anchor-id="what-the-comparison-contributes-to-cavl">5.4. What the comparison contributes to CAVL</h3>
<p>The comparison places four constraints on CAVL. First, factual knowledge, subjective monitoring, attitudes, and epistemic credit do not behave as a single learning outcome. The full T1-to-T3 analyses reinforce this point: factual knowledge showed an early increase with marked score homogenization, subjective knowledge increased more gradually, and attitudes accumulated change across both periods. The architecture must therefore retain distinct transitions between exposure, evaluation, factual integration, self-evaluation, and attitudinal change.</p>
<p>Second, interactional embedding is not a passive context. It changes the relation between source and credit and is associated with self-calibration. The distinction between documents and people is therefore not the presence versus absence of the social. Both are socially produced. The difference lies in the degree of reciprocity, social comparison, and coordination required during processing.</p>
<p>Third, the sequence measured factual knowledge -&gt; perceived expertise -&gt; epistemic credit is empirically useful. Human social-learning capacities can make learning from others highly effective, but they do not guarantee that factual knowledge is correctly recognized. Learning environments can intervene precisely at this interface by making evidence visible, clarifying domains of expertise, and reducing non-diagnostic status cues.</p>
<p>Fourth, the more specific prediction that lower-knowledge learners would depend more strongly on document-based credit was not formally supported. Web credit predicted T2, and simple slopes followed the predicted gradient, but the interaction with T1 was not significant. This proposition should therefore remain a hypothesis for designs that manipulate content quality, attributed authority, and prior knowledge independently.</p>
</section>
<section id="implications-for-instruction" class="level3">
<h3 class="anchored" data-anchor-id="implications-for-instruction">5.5. Implications for instruction</h3>
<p>The results argue against two symmetrical prescriptions: 'searching online is enough to learn' and 'having students debate is enough to learn.' Document-based environments can support domain-knowledge construction when information is relevant, verifiable, and connected to prior knowledge. Instruction should therefore organize search goals, provenance, comparison, and verification rather than provide access alone.</p>
<p>Debate should be designed not only to increase participation, but to align social coordination with epistemic goals. Useful procedures include independent initial judgments, explicit evidence requirements, visible mapping of expertise, source comparison, and protected opportunities to revise. The goal is to make competence legible and disagreement informative. When those conditions are met, interaction can combine collective memory, explanation, correction, and metacognitive calibration. These are design implications, not causal effects established by MOVICI.</p>
<p>More broadly, documents and human interaction are complementary. Documents stabilize socially produced knowledge and make it revisitable. Human interaction adds adaptation, explanation, challenge, calibration, and socialization. Instruction can distribute these functions across a sequence: document before discussion, make expertise explicit during discussion, and return to evidence afterward. The problem is not to choose between knowledge and the social. It is to organize social mechanisms so that they reinforce epistemic quality rather than compete with it.</p>
</section>
</section>
<section id="limitations-and-future-directions" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-future-directions">6. Limitations and future directions</h2>
<ul>
<li><p>The design is sequential and not counterbalanced. All participants completed the document-based period before the interactional period. T1 was also administered one to several weeks before the laboratory session, whereas T2 and T3 were collected within that session. We do not have a sufficiently usable participant-level measure of that interval or of possible topic exposure between T1 and the session. Environment type and sequence position are therefore perfectly confounded: no statistical adjustment in the present data can estimate what would have happened had the debate occurred first. T1-to-T3 analyses place final outcomes on the same baseline and improve trajectory description, but they do not neutralize this order effect. T1-to-T2 change cannot be attributed exclusively to the document-based sequence, and adjacent-period contrasts should be interpreted comparatively rather than as pure causal estimates of document versus human learning.</p></li>
<li><p>Both periods are composite. T1-to-T2 combines search, active recall, and source/argument evaluation; T2-to-T3 combines debate, partner evaluation, and argument recall/evaluation. The parallel post-activity structure is a strength for comparison, but it does not isolate the effect of search or debate. Retrieval itself can support retention (Roediger &amp; Karpicke, 2006).</p></li>
<li><p>Condition allocation followed enrolment/session entry rather than strict randomization. Groups were composed using T1 attitudes to favor position diversity. Baseline knowledge and SES were similar across conditions, but the global T1 attitude score showed a modest descriptive difference. Condition associations, including H3, should therefore not be interpreted as pure randomized causal effects.</p></li>
<li><p>Document-based and human-source measures are structurally parallel but not isomorphic. Web sources are selected and recalled by participants; human partners are given by group composition and are reciprocal. This limits a pure type-of-source interpretation. At the same time, preserving these properties supports ecological validity because source selection is constitutive of Web search and reciprocity is constitutive of live interaction.</p></li>
<li><p>The 20-item factual inventory samples only part of the controversy. It does not measure argumentative learning, fine-grained conceptual synthesis, tacit knowledge, or awareness of the limits of one's own understanding. The minimized Article 3 reproducibility dataset contains total factual scores rather than item-level responses, so the present package does not estimate internal-consistency reliability. Distribution diagnostics nevertheless showed no meaningful floor or ceiling compression at T1, T2, or T3.</p></li>
<li><p>Immediate attitudes should not be equated with durable private beliefs or stable public expression. Their direction is not a truth test. Some changes can be interpreted relative to contemporary evidence in health and environment and to established animal-welfare assessment frameworks, but that interpretation must remain dimension-specific.</p></li>
<li><p>Equivalence analyses are post hoc. The +/-0.10, +/-0.20, and +/-0.30 bounds are standardized sensitivity benchmarks, not preregistered smallest effects of interest. The strongest conclusion is compatibility with effects inside +/-0.20 for two RQ1 associations, not prospective proof of an exactly null effect.</p></li>
<li><p>The sample is mainly composed of university students and the task concerns one controversy. Replication is needed across domains, populations, and instructional settings. A decisive follow-up would randomize or counterbalance environment order, match target content across document and partner conditions, and link specific claims to specific sources. It could then trace exposure -&gt; recognition -&gt; credit -&gt; retention -&gt; integration directly.</p></li>
</ul>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">7. Conclusion</h2>
<p>Within the same participants, the MOVICI periods were associated with different learning configurations. Factual scores increased and strongly homogenized from T1 to T2; at T3, the mean remained above T1 and dispersion remained below baseline, showing that the earlier transformation was not erased. Subjective knowledge increased more gradually and was clearly above T1 only when the full T1-to-T3 interval was considered. Attitudes shifted in both periods and showed a larger cumulative T1-to-T3 change, especially on SSA and EP. The interactional period did not add a positive mean factual gain, but it re-differentiated factual scores while other dimensions continued to change.</p>
<p>The central distinction is not knowledge versus socialization. Human knowledge is deeply social. It is produced, transmitted, and stabilized by collectives. External representations have a particular property: they preserve part of that knowledge while partly decoupling it from immediate reciprocity. Human sources offer something else. They can explain, answer, challenge, and correct, but they also engage comparison, trust, status, and coordination. These mechanisms are powerful. Their epistemic effect depends on how well they align with measured competence and knowledge-oriented goals.</p>
<p>For CAVL, vigilant learning is therefore the regulation of dependence on external resources. Documents and people are not two versions of one mechanism. They distribute processing differently across content, source, self, and others. When social mechanisms make competence visible and reward accuracy, collective learning can be exceptionally powerful. When they answer to other goals, available knowledge may remain poorly recognized or poorly integrated. This distinction provides a framework for linking domain learning, metacognition, cognitive technologies, and epistemic coordination in contemporary instruction.</p>
</section>
<div id="movici-references">
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Anmarkrud, Ø., Bråten, I., Florit, E., &amp; Mason, L. (2022). The role of individual differences in sourcing: A systematic review. <em>Educational Psychology Review</em>, <em>34</em>, 749-792. <a href="https://doi.org/10.1007/s10648-021-09640-7">https://doi.org/10.1007/s10648-021-09640-7</a></p>
<p>Bouvard, V., Loomis, D., Guyton, K. Z., Grosse, Y., El Ghissassi, F., Benbrahim-Tallaa, L., Guha, N., Mattock, H., &amp; Straif, K. (2015). Carcinogenicity of consumption of red and processed meat. <em>The Lancet Oncology</em>, <em>16</em>(16), 1599-1600. <a href="https://doi.org/10.1016/S1470-2045(15)">https://doi.org/10.1016/S1470-2045(15</a>00444-1</p>
<p>Bråten, I., Strømsø, H. I., &amp; Salmerón, L. (2011). Trust and mistrust when students read multiple information sources about climate change. <em>Learning and Instruction</em>, <em>21</em>(2), 180-192. <a href="https://doi.org/10.1016/j.learninstruc.2010.02.002">https://doi.org/10.1016/j.learninstruc.2010.02.002</a></p>
<p>Brunswik, E. (1956). <em>Perception and the representative design of psychological experiments</em> (2nd ed.). University of California Press.</p>
<p>Buchs, C., &amp; Butera, F. (2009). Is a partner’s competence threatening during dyadic cooperative work? It depends on resource interdependence. <em>European Journal of Psychology of Education</em>, <em>24</em>, 145-154. <a href="https://doi.org/10.1007/BF03173007">https://doi.org/10.1007/BF03173007</a></p>
<p>Chaiken, S. (1980). Heuristic versus systematic information processing and the use of source versus message cues in persuasion. <em>Journal of Personality and Social Psychology</em>, <em>39</em>(5), 752-766. <a href="https://doi.org/10.1037/0022-3514.39.5.752">https://doi.org/10.1037/0022-3514.39.5.752</a></p>
<p>Chi, M. T. H., &amp; Wylie, R. (2014). The ICAP framework: Linking cognitive engagement to active learning outcomes. <em>Educational Psychologist</em>, <em>49</em>(4), 219-243. <a href="https://doi.org/10.1080/00461520.2014.965823">https://doi.org/10.1080/00461520.2014.965823</a></p>
<p>Cicourel, A. V. (2007). A personal, retrospective view of ecological validity. <em>Text &amp; Talk</em>, <em>27</em>(5-6), 735-752. <a href="https://doi.org/10.1515/TEXT.2007.033">https://doi.org/10.1515/TEXT.2007.033</a></p>
<p>Clark, A., &amp; Chalmers, D. (1998). The extended mind. <em>Analysis</em>, <em>58</em>(1), 7-19. <a href="https://doi.org/10.1093/analys/58.1.7">https://doi.org/10.1093/analys/58.1.7</a></p>
<p>Clark, M. A., Domingo, N. G. G., Colgan, K., Thakrar, S. K., Tilman, D., Lynch, J., Azevedo, I. L., &amp; Hill, J. D. (2020). Global food system emissions could preclude achieving the 1.5°C and 2°C climate change targets. <em>Science</em>, <em>370</em>(6517), 705-708. <a href="https://doi.org/10.1126/science.aba7357">https://doi.org/10.1126/science.aba7357</a></p>
<p>Clark, R. E. (1983). Reconsidering research on learning from media. <em>Review of Educational Research</em>, <em>53</em>(4), 445-459. <a href="https://doi.org/10.3102/00346543053004445">https://doi.org/10.3102/00346543053004445</a></p>
<p>Colpaert, L., Muller, D., Fayant, M.-P., &amp; Butera, F. (2015). A mindset of competition versus cooperation moderates the impact of social comparison on self-evaluation. <em>Frontiers in Psychology</em>, <em>6</em>, 1337. <a href="https://doi.org/10.3389/fpsyg.2015.01337">https://doi.org/10.3389/fpsyg.2015.01337</a></p>
<p>Darnon, C., Doll, S., &amp; Butera, F. (2007). Dealing with a disagreeing partner: Relational and epistemic conflict elaboration. <em>European Journal of Psychology of Education</em>, <em>22</em>(3), 227-242. <a href="https://doi.org/10.1007/BF03173423">https://doi.org/10.1007/BF03173423</a></p>
<p>Darnon, C., Muller, D., Schrager, S. M., Pannuzzo, N., &amp; Butera, F. (2006). Mastery and performance goals predict epistemic and relational conflict regulation. <em>Journal of Educational Psychology</em>, <em>98</em>(4), 766-776. <a href="https://doi.org/10.1037/0022-0663.98.4.766">https://doi.org/10.1037/0022-0663.98.4.766</a></p>
<p>De Dreu, C. K. W., Nijstad, B. A., &amp; van Knippenberg, D. (2008). Motivated information processing in group judgment and decision making. <em>Personality and Social Psychology Review</em>, <em>12</em>(1), 22-49. <a href="https://doi.org/10.1177/1088868307304092">https://doi.org/10.1177/1088868307304092</a></p>
<p>Donald, M. (1991). <em>Origins of the modern mind: Three stages in the evolution of culture and cognition</em>. Harvard University Press.</p>
<p>Festinger, L. (1954). A theory of social comparison processes. <em>Human Relations</em>, <em>7</em>(2), 117-140. <a href="https://doi.org/10.1177/001872675400700202">https://doi.org/10.1177/001872675400700202</a></p>
<p>Fisher, M., Goddu, M. K., &amp; Keil, F. C. (2015). Searching for explanations: How the Internet inflates estimates of internal knowledge. <em>Journal of Experimental Psychology: General</em>, <em>144</em>(3), 674-687. <a href="https://doi.org/10.1037/xge0000070">https://doi.org/10.1037/xge0000070</a></p>
<p>Heyes, C. (2020). Psychological mechanisms forged by cultural evolution. <em>Current Directions in Psychological Science</em>, <em>29</em>(4), 399-404. <a href="https://doi.org/10.1177/0963721420917736">https://doi.org/10.1177/0963721420917736</a></p>
<p>Hollan, J., Hutchins, E., &amp; Kirsh, D. (2000). Distributed cognition: Toward a new foundation for human-computer interaction research. <em>ACM Transactions on Computer-Human Interaction</em>, <em>7</em>(2), 174-196. <a href="https://doi.org/10.1145/353485.353487">https://doi.org/10.1145/353485.353487</a></p>
<p>Hollingshead, A. B. (2000). Perceptions of expertise and transactive memory in work relationships. <em>Group Processes &amp; Intergroup Relations</em>, <em>3</em>(3), 257-267. <a href="https://doi.org/10.1177/1368430200033002">https://doi.org/10.1177/1368430200033002</a></p>
<p>Hutchins, E. (1995). <em>Cognition in the wild</em>. MIT Press.</p>
<p>Janssen, J., Kirschner, F., Erkens, G., Kirschner, P. A., &amp; Paas, F. (2010). Making the black box of collaborative learning transparent: Combining process-oriented and cognitive load approaches. <em>Educational Psychology Review</em>, <em>22</em>(2), 139-154. <a href="https://doi.org/10.1007/s10648-010-9131-x">https://doi.org/10.1007/s10648-010-9131-x</a></p>
<p>Janssen, J., &amp; Kirschner, P. A. (2020). Applying collaborative cognitive load theory to computer-supported collaborative learning: Towards a research agenda. <em>Educational Technology Research and Development</em>, <em>68</em>, 783-805. <a href="https://doi.org/10.1007/s11423-019-09729-5">https://doi.org/10.1007/s11423-019-09729-5</a></p>
<p>Johnson, D. W., &amp; Johnson, R. T. (2009). An educational psychology success story: Social interdependence theory and cooperative learning. <em>Educational Researcher</em>, <em>38</em>(5), 365-379. <a href="https://doi.org/10.3102/0013189X09339057">https://doi.org/10.3102/0013189X09339057</a></p>
<p>Kirschner, F., Paas, F., &amp; Kirschner, P. A. (2011). Task complexity as a driver for collaborative learning efficiency: The collective working-memory effect. <em>Applied Cognitive Psychology</em>, <em>25</em>(4), 615-624. <a href="https://doi.org/10.1002/acp.1730">https://doi.org/10.1002/acp.1730</a></p>
<p>Kirschner, P. A., Sweller, J., Kirschner, F., &amp; Zambrano, J. R. (2018). From cognitive load theory to collaborative cognitive load theory. <em>International Journal of Computer-Supported Collaborative Learning</em>, <em>13</em>(2), 213-233. <a href="https://doi.org/10.1007/s11412-018-9277-y">https://doi.org/10.1007/s11412-018-9277-y</a></p>
<p>Koriat, A. (1997). Monitoring one’s own knowledge during study: A cue-utilization approach to judgments of learning. <em>Journal of Experimental Psychology: General</em>, <em>126</em>(4), 349-370. <a href="https://doi.org/10.1037/0096-3445.126.4.349">https://doi.org/10.1037/0096-3445.126.4.349</a></p>
<p>Kyndt, E., Raes, E., Lismont, B., Timmers, F., Cascallar, E., &amp; Dochy, F. (2013). A meta-analysis of the effects of face-to-face cooperative learning: Do recent studies falsify or verify earlier findings? Educational Research Review, 10, 133-149. <a href="https://doi.org/10.1016/j.edurev.2013.02.002">https://doi.org/10.1016/j.edurev.2013.02.002</a></p>
<p>Marchionini, G. (1995). <em>Information seeking in electronic environments</em>. Cambridge University Press.</p>
<p>Mellor, D. J., Beausoleil, N. J., Littlewood, K. E., McLean, A. N., McGreevy, P. D., Jones, B., &amp; Wilkins, C. (2020). The 2020 Five Domains Model: Including human-animal interactions in assessments of animal welfare. <em>Animals</em>, <em>10</em>(10), 1870. <a href="https://doi.org/10.3390/ani10101870">https://doi.org/10.3390/ani10101870</a></p>
<p>Mercier, H., &amp; Sperber, D. (2011). Why do humans reason? Arguments for an argumentative theory. <em>Behavioral and Brain Sciences</em>, <em>34</em>(2), 57-74. <a href="https://doi.org/10.1017/S0140525X10000968">https://doi.org/10.1017/S0140525X10000968</a></p>
<p>Nelson, T. O., &amp; Narens, L. (1990). Metamemory: A theoretical framework and new findings. In G. H. Bower (Ed.), <em>The psychology of learning and motivation</em> (Vol. 26, pp.&nbsp;125-173). Academic Press. <a href="https://doi.org/10.1016/S0079-7421(08)">https://doi.org/10.1016/S0079-7421(08</a>60053-5</p>
<p>Perfetti, C. A., Rouet, J.-F., &amp; Britt, M. A. (1999). Toward a theory of documents representation. In H. van Oostendorp &amp; S. R. Goldman (Eds.), <em>The construction of mental representations during reading</em> (pp.&nbsp;99-122). Lawrence Erlbaum Associates.</p>
<p>Petty, R. E., &amp; Cacioppo, J. T. (1986). <em>Communication and persuasion: Central and peripheral routes to attitude change</em>. Springer. <a href="https://doi.org/10.1007/978-1-4612-4964-1">https://doi.org/10.1007/978-1-4612-4964-1</a></p>
<p>Pirolli, P., &amp; Card, S. K. (1999). Information foraging. <em>Psychological Review</em>, <em>106</em>(4), 643-675. <a href="https://doi.org/10.1037/0033-295X.106.4.643">https://doi.org/10.1037/0033-295X.106.4.643</a></p>
<p>Poore, J., &amp; Nemecek, T. (2018). Reducing food’s environmental impacts through producers and consumers. <em>Science</em>, <em>360</em>(6392), 987-992. <a href="https://doi.org/10.1126/science.aaq0216">https://doi.org/10.1126/science.aaq0216</a></p>
<p>Pustejovsky, J. E., &amp; Tipton, E. (2018). Small-sample methods for cluster-robust variance estimation and hypothesis testing in fixed effects models. <em>Journal of Business &amp; Economic Statistics</em>, <em>36</em>(4), 672-683. <a href="https://doi.org/10.1080/07350015.2016.1247004">https://doi.org/10.1080/07350015.2016.1247004</a></p>
<p>Rieh, S. Y., Collins-Thompson, K., Hansen, P., &amp; Lee, H.-J. (2016). Towards searching as a learning process: A review of current perspectives and future directions. <em>Journal of Information Science</em>, <em>42</em>(1), 19-34. <a href="https://doi.org/10.1177/0165551515615841">https://doi.org/10.1177/0165551515615841</a></p>
<p>Risko, E. F., &amp; Gilbert, S. J. (2016). Cognitive offloading. <em>Trends in Cognitive Sciences</em>, <em>20</em>(9), 676-688. <a href="https://doi.org/10.1016/j.tics.2016.07.002">https://doi.org/10.1016/j.tics.2016.07.002</a></p>
<p>Roediger, H. L., III, &amp; Karpicke, J. D. (2006). Test-enhanced learning: Taking memory tests improves long-term retention. <em>Psychological Science</em>, <em>17</em>(3), 249-255. <a href="https://doi.org/10.1111/j.1467-9280.2006.01693.x">https://doi.org/10.1111/j.1467-9280.2006.01693.x</a></p>
<p>Rouet, J.-F. (2006). <em>The skills of document use: From text comprehension to web-based learning</em>. Lawrence Erlbaum Associates.</p>
<p>Salomon, G., Perkins, D. N., &amp; Globerson, T. (1991). Partners in cognition: Extending human intelligence with intelligent technologies. <em>Educational Researcher</em>, <em>20</em>(3), 2-9. <a href="https://doi.org/10.3102/0013189X020003002">https://doi.org/10.3102/0013189X020003002</a></p>
<p>Schmuckler, M. A. (2001). What is ecological validity? A dimensional analysis. <em>Infancy</em>, <em>2</em>(4), 419-436. <a href="https://doi.org/10.1207/S15327078IN0204_02">https://doi.org/10.1207/S15327078IN0204_02</a></p>
<p>Simonsmeier, B. A., Flaig, M., Deiglmayr, A., Schalk, L., &amp; Schneider, M. (2022). Domain-specific prior knowledge and learning: A meta-analysis. <em>Educational Psychologist</em>, <em>57</em>(1), 31-54. <a href="https://doi.org/10.1080/00461520.2021.1939700">https://doi.org/10.1080/00461520.2021.1939700</a></p>
<p>Sperber, D., Clément, F., Heintz, C., Mascaro, O., Mercier, H., Origgi, G., &amp; Wilson, D. (2010). Epistemic vigilance. <em>Mind &amp; Language</em>, <em>25</em>(4), 359-393. <a href="https://doi.org/10.1111/j.1468-0017.2010.01394.x">https://doi.org/10.1111/j.1468-0017.2010.01394.x</a></p>
<p>Tamim, R. M., Bernard, R. M., Borokhovski, E., Abrami, P. C., &amp; Schmid, R. F. (2011). What forty years of research says about the impact of technology on learning: A second-order meta-analysis and validation study. <em>Review of Educational Research</em>, <em>81</em>(1), 4-28. <a href="https://doi.org/10.3102/0034654310393361">https://doi.org/10.3102/0034654310393361</a></p>
<p>Tomasello, M. (1999). The human adaptation for culture. <em>Annual Review of Anthropology</em>, <em>28</em>, 509-529. <a href="https://doi.org/10.1146/annurev.anthro.28.1.509">https://doi.org/10.1146/annurev.anthro.28.1.509</a></p>
<p>Vayre et al.&nbsp;(2026a). Prior knowledge and learning from open Web search [Preprint].</p>
<p>Vayre et al.&nbsp;(2026b). Epistemic credit in cooperative and competitive debate [Preprint].</p>
<p>Vayre et al.&nbsp;(2026c). CAVL: A cognitive architecture for vigilant learning [Preprint].</p>
<p>Vogel, F., Wecker, C., Kollar, I., &amp; Fischer, F. (2017). Socio-cognitive scaffolding with computer-supported collaboration scripts: A meta-analysis. <em>Educational Psychology Review</em>, <em>29</em>, 477-511. <a href="https://doi.org/10.1007/s10648-016-9361-7">https://doi.org/10.1007/s10648-016-9361-7</a></p>
<p>Wecker, C., &amp; Fischer, F. (2014). Where is the evidence? A meta-analysis on the role of argumentation for the acquisition of domain-specific knowledge in computer-supported collaborative learning. <em>Computers &amp; Education</em>, <em>75</em>, 218-228. <a href="https://doi.org/10.1016/j.compedu.2014.02.016">https://doi.org/10.1016/j.compedu.2014.02.016</a></p>
<p>Wegner, D. M. (1987). Transactive memory: A contemporary analysis of the group mind. In B. Mullen &amp; G. R. Goethals (Eds.), <em>Theories of group behavior</em> (pp.&nbsp;185-208). Springer. <a href="https://doi.org/10.1007/978-1-4612-4634-3_9">https://doi.org/10.1007/978-1-4612-4634-3_9</a></p>
</section>
</div>
<script>
window.MOVICI_REFERENCES = [{"id": "ref-1", "full": "Anmarkrud, Ø., Bråten, I., Florit, E., & Mason, L. (2022). The role of individual differences in sourcing: A systematic review. Educational Psychology Review, 34, 749-792. https://doi.org/10.1007/s10648-021-09640-7", "doi": "https://doi.org/10.1007/s10648-021-09640-7", "aliases": ["Anmarkrud and Mason (2022)", "Anmarkrud and Mason, 2022", "Anmarkrud & Mason (2022)", "Anmarkrud & Mason, 2022", "Anmarkrud et al. (2022)", "Anmarkrud et al., 2022", "Anmarkrud (2022)", "Anmarkrud, 2022"]}, {"id": "ref-2", "full": "Bouvard, V., Loomis, D., Guyton, K. Z., Grosse, Y., El Ghissassi, F., Benbrahim-Tallaa, L., Guha, N., Mattock, H., & Straif, K. (2015). Carcinogenicity of consumption of red and processed meat. The Lancet Oncology, 16(16), 1599-1600. https://doi.org/10.1016/S1470-2045(15)00444-1", "doi": "https://doi.org/10.1016/S1470-2045(15)00444-1", "aliases": ["Bouvard and Straif (2015)", "Bouvard and Straif, 2015", "Bouvard & Straif (2015)", "Bouvard & Straif, 2015", "Bouvard et al. (2015)", "Bouvard et al., 2015", "Bouvard (2015)", "Bouvard, 2015"]}, {"id": "ref-3", "full": "Bråten, I., Strømsø, H. I., & Salmerón, L. (2011). Trust and mistrust when students read multiple information sources about climate change. Learning and Instruction, 21(2), 180-192. https://doi.org/10.1016/j.learninstruc.2010.02.002", "doi": "https://doi.org/10.1016/j.learninstruc.2010.02.002", "aliases": ["Bråten and Salmerón (2011)", "Bråten and Salmerón, 2011", "Bråten & Salmerón (2011)", "Bråten & Salmerón, 2011", "Bråten et al. (2011)", "Bråten et al., 2011", "Bråten (2011)", "Bråten, 2011"]}, {"id": "ref-4", "full": "Brunswik, E. (1956). Perception and the representative design of psychological experiments (2nd ed.). University of California Press.", "doi": "", "aliases": ["Brunswik et al. (1956)", "Brunswik et al., 1956", "Brunswik (1956)", "Brunswik, 1956"]}, {"id": "ref-5", "full": "Buchs, C., & Butera, F. (2009). Is a partner's competence threatening during dyadic cooperative work? It depends on resource interdependence. European Journal of Psychology of Education, 24, 145-154. https://doi.org/10.1007/BF03173007", "doi": "https://doi.org/10.1007/BF03173007", "aliases": ["Buchs and Butera (2009)", "Buchs and Butera, 2009", "Buchs & Butera (2009)", "Buchs & Butera, 2009", "Buchs et al. (2009)", "Buchs et al., 2009", "Buchs (2009)", "Buchs, 2009"]}, {"id": "ref-6", "full": "Chaiken, S. (1980). Heuristic versus systematic information processing and the use of source versus message cues in persuasion. Journal of Personality and Social Psychology, 39(5), 752-766. https://doi.org/10.1037/0022-3514.39.5.752", "doi": "https://doi.org/10.1037/0022-3514.39.5.752", "aliases": ["Chaiken et al. (1980)", "Chaiken et al., 1980", "Chaiken (1980)", "Chaiken, 1980"]}, {"id": "ref-7", "full": "Chi, M. T. H., & Wylie, R. (2014). The ICAP framework: Linking cognitive engagement to active learning outcomes. Educational Psychologist, 49(4), 219-243. https://doi.org/10.1080/00461520.2014.965823", "doi": "https://doi.org/10.1080/00461520.2014.965823", "aliases": ["Chi and Wylie (2014)", "Chi and Wylie, 2014", "Chi & Wylie (2014)", "Chi et al. (2014)", "Chi & Wylie, 2014", "Chi et al., 2014", "Chi (2014)", "Chi, 2014"]}, {"id": "ref-8", "full": "Cicourel, A. V. (2007). A personal, retrospective view of ecological validity. Text & Talk, 27(5-6), 735-752. https://doi.org/10.1515/TEXT.2007.033", "doi": "https://doi.org/10.1515/TEXT.2007.033", "aliases": ["Cicourel et al. (2007)", "Cicourel et al., 2007", "Cicourel (2007)", "Cicourel, 2007"]}, {"id": "ref-9", "full": "Clark, A., & Chalmers, D. (1998). The extended mind. Analysis, 58(1), 7-19. https://doi.org/10.1093/analys/58.1.7", "doi": "https://doi.org/10.1093/analys/58.1.7", "aliases": ["Clark and Chalmers (1998)", "Clark and Chalmers, 1998", "Clark & Chalmers (1998)", "Clark & Chalmers, 1998", "Clark et al. (1998)", "Clark et al., 1998", "Clark (1998)", "Clark, 1998"]}, {"id": "ref-10", "full": "Clark, M. A., Domingo, N. G. G., Colgan, K., Thakrar, S. K., Tilman, D., Lynch, J., Azevedo, I. L., & Hill, J. D. (2020). Global food system emissions could preclude achieving the 1.5°C and 2°C climate change targets. Science, 370(6517), 705-708. https://doi.org/10.1126/science.aba7357", "doi": "https://doi.org/10.1126/science.aba7357", "aliases": ["Clark and Hill (2020)", "Clark and Hill, 2020", "Clark & Hill (2020)", "Clark et al. (2020)", "Clark et al., 2020", "Clark & Hill, 2020", "Clark (2020)", "Clark, 2020"]}, {"id": "ref-11", "full": "Clark, R. E. (1983). Reconsidering research on learning from media. Review of Educational Research, 53(4), 445-459. https://doi.org/10.3102/00346543053004445", "doi": "https://doi.org/10.3102/00346543053004445", "aliases": ["Clark et al. (1983)", "Clark et al., 1983", "Clark (1983)", "Clark, 1983"]}, {"id": "ref-12", "full": "Colpaert, L., Muller, D., Fayant, M.-P., & Butera, F. (2015). A mindset of competition versus cooperation moderates the impact of social comparison on self-evaluation. Frontiers in Psychology, 6, 1337. https://doi.org/10.3389/fpsyg.2015.01337", "doi": "https://doi.org/10.3389/fpsyg.2015.01337", "aliases": ["Colpaert and Butera (2015)", "Colpaert and Butera, 2015", "Colpaert & Butera (2015)", "Colpaert & Butera, 2015", "Colpaert et al. (2015)", "Colpaert et al., 2015", "Colpaert (2015)", "Colpaert, 2015"]}, {"id": "ref-13", "full": "Darnon, C., Doll, S., & Butera, F. (2007). Dealing with a disagreeing partner: Relational and epistemic conflict elaboration. European Journal of Psychology of Education, 22(3), 227-242. https://doi.org/10.1007/BF03173423", "doi": "https://doi.org/10.1007/BF03173423", "aliases": ["Darnon and Butera (2007)", "Darnon and Butera, 2007", "Darnon & Butera (2007)", "Darnon & Butera, 2007", "Darnon et al. (2007)", "Darnon et al., 2007", "Darnon (2007)", "Darnon, 2007"]}, {"id": "ref-14", "full": "Darnon, C., Muller, D., Schrager, S. M., Pannuzzo, N., & Butera, F. (2006). Mastery and performance goals predict epistemic and relational conflict regulation. Journal of Educational Psychology, 98(4), 766-776. https://doi.org/10.1037/0022-0663.98.4.766", "doi": "https://doi.org/10.1037/0022-0663.98.4.766", "aliases": ["Darnon and Butera (2006)", "Darnon and Butera, 2006", "Darnon & Butera (2006)", "Darnon & Butera, 2006", "Darnon et al. (2006)", "Darnon et al., 2006", "Darnon (2006)", "Darnon, 2006"]}, {"id": "ref-15", "full": "De Dreu, C. K. W., Nijstad, B. A., & van Knippenberg, D. (2008). Motivated information processing in group judgment and decision making. Personality and Social Psychology Review, 12(1), 22-49. https://doi.org/10.1177/1088868307304092", "doi": "https://doi.org/10.1177/1088868307304092", "aliases": ["De Dreu and van Knippenberg (2008)", "De Dreu and van Knippenberg, 2008", "De Dreu & van Knippenberg (2008)", "De Dreu & van Knippenberg, 2008", "De Dreu et al. (2008)", "De Dreu et al., 2008", "De Dreu (2008)", "De Dreu, 2008"]}, {"id": "ref-16", "full": "Donald, M. (1991). Origins of the modern mind: Three stages in the evolution of culture and cognition. Harvard University Press.", "doi": "", "aliases": ["Donald et al. (1991)", "Donald et al., 1991", "Donald (1991)", "Donald, 1991"]}, {"id": "ref-17", "full": "Festinger, L. (1954). A theory of social comparison processes. Human Relations, 7(2), 117-140. https://doi.org/10.1177/001872675400700202", "doi": "https://doi.org/10.1177/001872675400700202", "aliases": ["Festinger et al. (1954)", "Festinger et al., 1954", "Festinger (1954)", "Festinger, 1954"]}, {"id": "ref-18", "full": "Fisher, M., Goddu, M. K., & Keil, F. C. (2015). Searching for explanations: How the Internet inflates estimates of internal knowledge. Journal of Experimental Psychology: General, 144(3), 674-687. https://doi.org/10.1037/xge0000070", "doi": "https://doi.org/10.1037/xge0000070", "aliases": ["Fisher and Keil (2015)", "Fisher and Keil, 2015", "Fisher & Keil (2015)", "Fisher et al. (2015)", "Fisher & Keil, 2015", "Fisher et al., 2015", "Fisher (2015)", "Fisher, 2015"]}, {"id": "ref-19", "full": "Heyes, C. (2020). Psychological mechanisms forged by cultural evolution. Current Directions in Psychological Science, 29(4), 399-404. https://doi.org/10.1177/0963721420917736", "doi": "https://doi.org/10.1177/0963721420917736", "aliases": ["Heyes et al. (2020)", "Heyes et al., 2020", "Heyes (2020)", "Heyes, 2020"]}, {"id": "ref-20", "full": "Hollan, J., Hutchins, E., & Kirsh, D. (2000). Distributed cognition: Toward a new foundation for human-computer interaction research. ACM Transactions on Computer-Human Interaction, 7(2), 174-196. https://doi.org/10.1145/353485.353487", "doi": "https://doi.org/10.1145/353485.353487", "aliases": ["Hollan and Kirsh (2000)", "Hollan and Kirsh, 2000", "Hollan & Kirsh (2000)", "Hollan & Kirsh, 2000", "Hollan et al. (2000)", "Hollan et al., 2000", "Hollan (2000)", "Hollan, 2000"]}, {"id": "ref-21", "full": "Hollingshead, A. B. (2000). Perceptions of expertise and transactive memory in work relationships. Group Processes & Intergroup Relations, 3(3), 257-267. https://doi.org/10.1177/1368430200033002", "doi": "https://doi.org/10.1177/1368430200033002", "aliases": ["Hollingshead et al. (2000)", "Hollingshead et al., 2000", "Hollingshead (2000)", "Hollingshead, 2000"]}, {"id": "ref-22", "full": "Hutchins, E. (1995). Cognition in the wild. MIT Press.", "doi": "", "aliases": ["Hutchins et al. (1995)", "Hutchins et al., 1995", "Hutchins (1995)", "Hutchins, 1995"]}, {"id": "ref-23", "full": "Janssen, J., Kirschner, F., Erkens, G., Kirschner, P. A., & Paas, F. (2010). Making the black box of collaborative learning transparent: Combining process-oriented and cognitive load approaches. Educational Psychology Review, 22(2), 139-154. https://doi.org/10.1007/s10648-010-9131-x", "doi": "https://doi.org/10.1007/s10648-010-9131-x", "aliases": ["Janssen and Paas (2010)", "Janssen and Paas, 2010", "Janssen & Paas (2010)", "Janssen et al. (2010)", "Janssen & Paas, 2010", "Janssen et al., 2010", "Janssen (2010)", "Janssen, 2010"]}, {"id": "ref-24", "full": "Janssen, J., & Kirschner, P. A. (2020). Applying collaborative cognitive load theory to computer-supported collaborative learning: Towards a research agenda. Educational Technology Research and Development, 68, 783-805. https://doi.org/10.1007/s11423-019-09729-5", "doi": "https://doi.org/10.1007/s11423-019-09729-5", "aliases": ["Janssen and Kirschner (2020)", "Janssen and Kirschner, 2020", "Janssen & Kirschner (2020)", "Janssen & Kirschner, 2020", "Janssen et al. (2020)", "Janssen et al., 2020", "Janssen (2020)", "Janssen, 2020"]}, {"id": "ref-25", "full": "Johnson, D. W., & Johnson, R. T. (2009). An educational psychology success story: Social interdependence theory and cooperative learning. Educational Researcher, 38(5), 365-379. https://doi.org/10.3102/0013189X09339057", "doi": "https://doi.org/10.3102/0013189X09339057", "aliases": ["Johnson and Johnson (2009)", "Johnson and Johnson, 2009", "Johnson & Johnson (2009)", "Johnson & Johnson, 2009", "Johnson et al. (2009)", "Johnson et al., 2009", "Johnson (2009)", "Johnson, 2009"]}, {"id": "ref-26", "full": "Kirschner, F., Paas, F., & Kirschner, P. A. (2011). Task complexity as a driver for collaborative learning efficiency: The collective working-memory effect. Applied Cognitive Psychology, 25(4), 615-624. https://doi.org/10.1002/acp.1730", "doi": "https://doi.org/10.1002/acp.1730", "aliases": ["Kirschner and Kirschner (2011)", "Kirschner and Kirschner, 2011", "Kirschner & Kirschner (2011)", "Kirschner & Kirschner, 2011", "Kirschner et al. (2011)", "Kirschner et al., 2011", "Kirschner (2011)", "Kirschner, 2011"]}, {"id": "ref-27", "full": "Kirschner, P. A., Sweller, J., Kirschner, F., & Zambrano, J. R. (2018). From cognitive load theory to collaborative cognitive load theory. International Journal of Computer-Supported Collaborative Learning, 13(2), 213-233. https://doi.org/10.1007/s11412-018-9277-y", "doi": "https://doi.org/10.1007/s11412-018-9277-y", "aliases": ["Kirschner and Zambrano (2018)", "Kirschner and Zambrano, 2018", "Kirschner & Zambrano (2018)", "Kirschner & Zambrano, 2018", "Kirschner et al. (2018)", "Kirschner et al., 2018", "Kirschner (2018)", "Kirschner, 2018"]}, {"id": "ref-28", "full": "Koriat, A. (1997). Monitoring one's own knowledge during study: A cue-utilization approach to judgments of learning. Journal of Experimental Psychology: General, 126(4), 349-370. https://doi.org/10.1037/0096-3445.126.4.349", "doi": "https://doi.org/10.1037/0096-3445.126.4.349", "aliases": ["Koriat et al. (1997)", "Koriat et al., 1997", "Koriat (1997)", "Koriat, 1997"]}, {"id": "ref-29", "full": "Kyndt, E., Raes, E., Lismont, B., Timmers, F., Cascallar, E., & Dochy, F. (2013). A meta-analysis of the effects of face-to-face cooperative learning: Do recent studies falsify or verify earlier findings? Educational Research Review, 10, 133-149. https://doi.org/10.1016/j.edurev.2013.02.002", "doi": "https://doi.org/10.1016/j.edurev.2013.02.002", "aliases": ["Kyndt and Dochy (2013)", "Kyndt and Dochy, 2013", "Kyndt & Dochy (2013)", "Kyndt & Dochy, 2013", "Kyndt et al. (2013)", "Kyndt et al., 2013", "Kyndt (2013)", "Kyndt, 2013"]}, {"id": "ref-30", "full": "Marchionini, G. (1995). Information seeking in electronic environments. Cambridge University Press.", "doi": "", "aliases": ["Marchionini et al. (1995)", "Marchionini et al., 1995", "Marchionini (1995)", "Marchionini, 1995"]}, {"id": "ref-31", "full": "Mellor, D. J., Beausoleil, N. J., Littlewood, K. E., McLean, A. N., McGreevy, P. D., Jones, B., & Wilkins, C. (2020). The 2020 Five Domains Model: Including human-animal interactions in assessments of animal welfare. Animals, 10(10), 1870. https://doi.org/10.3390/ani10101870", "doi": "https://doi.org/10.3390/ani10101870", "aliases": ["Mellor and Wilkins (2020)", "Mellor and Wilkins, 2020", "Mellor & Wilkins (2020)", "Mellor & Wilkins, 2020", "Mellor et al. (2020)", "Mellor et al., 2020", "Mellor (2020)", "Mellor, 2020"]}, {"id": "ref-32", "full": "Mercier, H., & Sperber, D. (2011). Why do humans reason? Arguments for an argumentative theory. Behavioral and Brain Sciences, 34(2), 57-74. https://doi.org/10.1017/S0140525X10000968", "doi": "https://doi.org/10.1017/S0140525X10000968", "aliases": ["Mercier and Sperber (2011)", "Mercier and Sperber, 2011", "Mercier & Sperber (2011)", "Mercier & Sperber, 2011", "Mercier et al. (2011)", "Mercier et al., 2011", "Mercier (2011)", "Mercier, 2011"]}, {"id": "ref-33", "full": "Nelson, T. O., & Narens, L. (1990). Metamemory: A theoretical framework and new findings. In G. H. Bower (Ed.), The psychology of learning and motivation (Vol. 26, pp. 125-173). Academic Press. https://doi.org/10.1016/S0079-7421(08)60053-5", "doi": "https://doi.org/10.1016/S0079-7421(08)60053-5", "aliases": ["Nelson and Narens (1990)", "Nelson and Narens, 1990", "Nelson & Narens (1990)", "Nelson & Narens, 1990", "Nelson et al. (1990)", "Nelson et al., 1990", "Nelson (1990)", "Nelson, 1990"]}, {"id": "ref-34", "full": "Perfetti, C. A., Rouet, J.-F., & Britt, M. A. (1999). Toward a theory of documents representation. In H. van Oostendorp & S. R. Goldman (Eds.), The construction of mental representations during reading (pp. 99-122). Lawrence Erlbaum Associates.", "doi": "", "aliases": ["Perfetti and Britt (1999)", "Perfetti and Britt, 1999", "Perfetti & Britt (1999)", "Perfetti & Britt, 1999", "Perfetti et al. (1999)", "Perfetti et al., 1999", "Perfetti (1999)", "Perfetti, 1999"]}, {"id": "ref-35", "full": "Petty, R. E., & Cacioppo, J. T. (1986). Communication and persuasion: Central and peripheral routes to attitude change. Springer. https://doi.org/10.1007/978-1-4612-4964-1", "doi": "https://doi.org/10.1007/978-1-4612-4964-1", "aliases": ["Petty and Cacioppo (1986)", "Petty and Cacioppo, 1986", "Petty & Cacioppo (1986)", "Petty & Cacioppo, 1986", "Petty et al. (1986)", "Petty et al., 1986", "Petty (1986)", "Petty, 1986"]}, {"id": "ref-36", "full": "Pirolli, P., & Card, S. K. (1999). Information foraging. Psychological Review, 106(4), 643-675. https://doi.org/10.1037/0033-295X.106.4.643", "doi": "https://doi.org/10.1037/0033-295X.106.4.643", "aliases": ["Pirolli and Card (1999)", "Pirolli and Card, 1999", "Pirolli et al. (1999)", "Pirolli & Card (1999)", "Pirolli & Card, 1999", "Pirolli et al., 1999", "Pirolli (1999)", "Pirolli, 1999"]}, {"id": "ref-37", "full": "Poore, J., & Nemecek, T. (2018). Reducing food's environmental impacts through producers and consumers. Science, 360(6392), 987-992. https://doi.org/10.1126/science.aaq0216", "doi": "https://doi.org/10.1126/science.aaq0216", "aliases": ["Poore and Nemecek (2018)", "Poore and Nemecek, 2018", "Poore & Nemecek (2018)", "Poore & Nemecek, 2018", "Poore et al. (2018)", "Poore et al., 2018", "Poore (2018)", "Poore, 2018"]}, {"id": "ref-38", "full": "Pustejovsky, J. E., & Tipton, E. (2018). Small-sample methods for cluster-robust variance estimation and hypothesis testing in fixed effects models. Journal of Business & Economic Statistics, 36(4), 672-683. https://doi.org/10.1080/07350015.2016.1247004", "doi": "https://doi.org/10.1080/07350015.2016.1247004", "aliases": ["Pustejovsky and Tipton (2018)", "Pustejovsky and Tipton, 2018", "Pustejovsky & Tipton (2018)", "Pustejovsky & Tipton, 2018", "Pustejovsky et al. (2018)", "Pustejovsky et al., 2018", "Pustejovsky (2018)", "Pustejovsky, 2018"]}, {"id": "ref-39", "full": "Rieh, S. Y., Collins-Thompson, K., Hansen, P., & Lee, H.-J. (2016). Towards searching as a learning process: A review of current perspectives and future directions. Journal of Information Science, 42(1), 19-34. https://doi.org/10.1177/0165551515615841", "doi": "https://doi.org/10.1177/0165551515615841", "aliases": ["Rieh and Lee (2016)", "Rieh and Lee, 2016", "Rieh et al. (2016)", "Rieh & Lee (2016)", "Rieh et al., 2016", "Rieh & Lee, 2016", "Rieh (2016)", "Rieh, 2016"]}, {"id": "ref-40", "full": "Risko, E. F., & Gilbert, S. J. (2016). Cognitive offloading. Trends in Cognitive Sciences, 20(9), 676-688. https://doi.org/10.1016/j.tics.2016.07.002", "doi": "https://doi.org/10.1016/j.tics.2016.07.002", "aliases": ["Risko and Gilbert (2016)", "Risko and Gilbert, 2016", "Risko & Gilbert (2016)", "Risko & Gilbert, 2016", "Risko et al. (2016)", "Risko et al., 2016", "Risko (2016)", "Risko, 2016"]}, {"id": "ref-41", "full": "Roediger, H. L., III, & Karpicke, J. D. (2006). Test-enhanced learning: Taking memory tests improves long-term retention. Psychological Science, 17(3), 249-255. https://doi.org/10.1111/j.1467-9280.2006.01693.x", "doi": "https://doi.org/10.1111/j.1467-9280.2006.01693.x", "aliases": ["Roediger and Karpicke (2006)", "Roediger and Karpicke, 2006", "Roediger & Karpicke (2006)", "Roediger & Karpicke, 2006", "Roediger et al. (2006)", "Roediger et al., 2006", "Roediger (2006)", "Roediger, 2006"]}, {"id": "ref-42", "full": "Rouet, J.-F. (2006). The skills of document use: From text comprehension to web-based learning. Lawrence Erlbaum Associates.", "doi": "", "aliases": ["Rouet et al. (2006)", "Rouet et al., 2006", "Rouet (2006)", "Rouet, 2006"]}, {"id": "ref-43", "full": "Salomon, G., Perkins, D. N., & Globerson, T. (1991). Partners in cognition: Extending human intelligence with intelligent technologies. Educational Researcher, 20(3), 2-9. https://doi.org/10.3102/0013189X020003002", "doi": "https://doi.org/10.3102/0013189X020003002", "aliases": ["Salomon and Globerson (1991)", "Salomon and Globerson, 1991", "Salomon & Globerson (1991)", "Salomon & Globerson, 1991", "Salomon et al. (1991)", "Salomon et al., 1991", "Salomon (1991)", "Salomon, 1991"]}, {"id": "ref-44", "full": "Schmuckler, M. A. (2001). What is ecological validity? A dimensional analysis. Infancy, 2(4), 419-436. https://doi.org/10.1207/S15327078IN020402", "doi": "https://doi.org/10.1207/S15327078IN020402", "aliases": ["Schmuckler et al. (2001)", "Schmuckler et al., 2001", "Schmuckler (2001)", "Schmuckler, 2001"]}, {"id": "ref-45", "full": "Simonsmeier, B. A., Flaig, M., Deiglmayr, A., Schalk, L., & Schneider, M. (2022). Domain-specific prior knowledge and learning: A meta-analysis. Educational Psychologist, 57(1), 31-54. https://doi.org/10.1080/00461520.2021.1939700", "doi": "https://doi.org/10.1080/00461520.2021.1939700", "aliases": ["Simonsmeier and Schneider (2022)", "Simonsmeier and Schneider, 2022", "Simonsmeier & Schneider (2022)", "Simonsmeier & Schneider, 2022", "Simonsmeier et al. (2022)", "Simonsmeier et al., 2022", "Simonsmeier (2022)", "Simonsmeier, 2022"]}, {"id": "ref-46", "full": "Sperber, D., Clément, F., Heintz, C., Mascaro, O., Mercier, H., Origgi, G., & Wilson, D. (2010). Epistemic vigilance. Mind & Language, 25(4), 359-393. https://doi.org/10.1111/j.1468-0017.2010.01394.x", "doi": "https://doi.org/10.1111/j.1468-0017.2010.01394.x", "aliases": ["Sperber and Wilson (2010)", "Sperber and Wilson, 2010", "Sperber & Wilson (2010)", "Sperber & Wilson, 2010", "Sperber et al. (2010)", "Sperber et al., 2010", "Sperber (2010)", "Sperber, 2010"]}, {"id": "ref-47", "full": "Tamim, R. M., Bernard, R. M., Borokhovski, E., Abrami, P. C., & Schmid, R. F. (2011). What forty years of research says about the impact of technology on learning: A second-order meta-analysis and validation study. Review of Educational Research, 81(1), 4-28. https://doi.org/10.3102/0034654310393361", "doi": "https://doi.org/10.3102/0034654310393361", "aliases": ["Tamim and Schmid (2011)", "Tamim and Schmid, 2011", "Tamim & Schmid (2011)", "Tamim & Schmid, 2011", "Tamim et al. (2011)", "Tamim et al., 2011", "Tamim (2011)", "Tamim, 2011"]}, {"id": "ref-48", "full": "Tomasello, M. (1999). The human adaptation for culture. Annual Review of Anthropology, 28, 509-529. https://doi.org/10.1146/annurev.anthro.28.1.509", "doi": "https://doi.org/10.1146/annurev.anthro.28.1.509", "aliases": ["Tomasello et al. (1999)", "Tomasello et al., 1999", "Tomasello (1999)", "Tomasello, 1999"]}, {"id": "ref-49", "full": "Vayre et al. (2026a). Prior knowledge and learning from open Web search \\[Preprint\\].", "doi": "", "aliases": ["Vayre et al et al. (2026a)", "Vayre et al et al., 2026a", "Vayre et al (2026a)", "Vayre et al, 2026a"]}, {"id": "ref-50", "full": "Vayre et al. (2026b). Epistemic credit in cooperative and competitive debate \\[Preprint\\].", "doi": "", "aliases": ["Vayre et al et al. (2026b)", "Vayre et al et al., 2026b", "Vayre et al (2026b)", "Vayre et al, 2026b"]}, {"id": "ref-51", "full": "Vayre et al. (2026c). CAVL: A cognitive architecture for vigilant learning \\[Preprint\\].", "doi": "", "aliases": ["Vayre et al et al. (2026c)", "Vayre et al et al., 2026c", "Vayre et al (2026c)", "Vayre et al, 2026c"]}, {"id": "ref-52", "full": "Vogel, F., Wecker, C., Kollar, I., & Fischer, F. (2017). Socio-cognitive scaffolding with computer-supported collaboration scripts: A meta-analysis. Educational Psychology Review, 29, 477-511. https://doi.org/10.1007/s10648-016-9361-7", "doi": "https://doi.org/10.1007/s10648-016-9361-7", "aliases": ["Vogel and Fischer (2017)", "Vogel and Fischer, 2017", "Vogel & Fischer (2017)", "Vogel & Fischer, 2017", "Vogel et al. (2017)", "Vogel et al., 2017", "Vogel (2017)", "Vogel, 2017"]}, {"id": "ref-53", "full": "Wecker, C., & Fischer, F. (2014). Where is the evidence? A meta-analysis on the role of argumentation for the acquisition of domain-specific knowledge in computer-supported collaborative learning. Computers & Education, 75, 218-228. https://doi.org/10.1016/j.compedu.2014.02.016", "doi": "https://doi.org/10.1016/j.compedu.2014.02.016", "aliases": ["Wecker and Fischer (2014)", "Wecker and Fischer, 2014", "Wecker & Fischer (2014)", "Wecker & Fischer, 2014", "Wecker et al. (2014)", "Wecker et al., 2014", "Wecker (2014)", "Wecker, 2014"]}, {"id": "ref-54", "full": "Wegner, D. M. (1987). Transactive memory: A contemporary analysis of the group mind. In B. Mullen & G. R. Goethals (Eds.), Theories of group behavior (pp. 185-208). Springer. https://doi.org/10.1007/978-1-4612-4634-39", "doi": "https://doi.org/10.1007/978-1-4612-4634-39", "aliases": ["Wegner et al. (1987)", "Wegner et al., 1987", "Wegner (1987)", "Wegner, 1987"]}];
</script>



</main> <!-- /main -->


<div id="movici-citation-tooltip" role="tooltip"></div>

<script>

(function () {

  function escRE(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }



  function run() {

    const refs = window.MOVICI_REFERENCES || [];

    if (!refs.length) return;



    const aliasMap = new Map();

    refs.forEach(ref => (ref.aliases || []).forEach(a => {

      if (a && !aliasMap.has(a)) aliasMap.set(a, ref);

    }));

    const aliases = Array.from(aliasMap.keys()).sort((a,b) => b.length - a.length);

    if (!aliases.length) return;



    const rx = new RegExp(aliases.map(escRE).join('|'), 'g');

    const root = document.querySelector('main.content') || document.querySelector('main') || document.body;

    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);

    const nodes = [];

    let node;

    while ((node = walker.nextNode())) {

      const p = node.parentElement;

      if (!p) continue;

      if (p.closest('#movici-references, script, style, pre, code, a, .movici-citation-hover')) continue;

      if (rx.test(node.nodeValue)) nodes.push(node);

      rx.lastIndex = 0;

    }



    nodes.forEach(textNode => {

      const text = textNode.nodeValue;

      let last = 0, match;

      rx.lastIndex = 0;

      const frag = document.createDocumentFragment();

      while ((match = rx.exec(text))) {

        if (match.index > last) frag.appendChild(document.createTextNode(text.slice(last, match.index)));

        const ref = aliasMap.get(match[0]);

        const el = ref && ref.doi ? document.createElement('a') : document.createElement('span');

        el.className = 'movici-citation-hover';

        el.textContent = match[0];

        el.dataset.full = (ref && ref.full) || '';

        el.dataset.doi = (ref && ref.doi) || '';

        if (ref && ref.doi) {

          el.href = ref.doi;

          el.target = '_blank';

          el.rel = 'noopener';

          el.setAttribute('aria-label', match[0] + ' — open DOI');

        }

        frag.appendChild(el);

        last = rx.lastIndex;

      }

      if (last < text.length) frag.appendChild(document.createTextNode(text.slice(last)));

      textNode.replaceWith(frag);

    });



    const tip = document.getElementById('movici-citation-tooltip');

    let hideTimer = null;



    function show(el) {

      clearTimeout(hideTimer);

      const full = el.dataset.full || '';

      const doi = el.dataset.doi || '';

      tip.innerHTML = '';

      const txt = document.createElement('div');

      txt.textContent = full;

      tip.appendChild(txt);

      if (doi) {

        const a = document.createElement('a');

        a.href = doi;

        a.target = '_blank';

        a.rel = 'noopener';

        a.textContent = 'Open DOI';

        tip.appendChild(a);

      }

      tip.style.display = 'block';

      const r = el.getBoundingClientRect();

      const w = Math.min(460, window.innerWidth - 24);

      tip.style.maxWidth = w + 'px';

      let left = Math.min(r.left, window.innerWidth - w - 12);

      left = Math.max(12, left);

      let top = r.bottom + 8;

      requestAnimationFrame(() => {

        const th = tip.getBoundingClientRect().height;

        if (top + th > window.innerHeight - 12) top = Math.max(12, r.top - th - 8);

        tip.style.left = left + 'px';

        tip.style.top = top + 'px';

      });

    }



    function scheduleHide() {

      hideTimer = setTimeout(() => { tip.style.display = 'none'; }, 180);

    }



    document.querySelectorAll('.movici-citation-hover').forEach(el => {

      el.addEventListener('mouseenter', () => show(el));

      el.addEventListener('mouseleave', scheduleHide);

      el.addEventListener('focus', () => show(el));

      el.addEventListener('blur', scheduleHide);

      el.tabIndex = 0;

    });

    tip.addEventListener('mouseenter', () => clearTimeout(hideTimer));

    tip.addEventListener('mouseleave', scheduleHide);

  }



  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', run);

  else run();

})();

</script>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>MOVICI Research Programme · Working papers and research materials</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>